- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:54:43'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: A generalist AI agent for 3D virtual environments - Google DeepMind
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://deepmind.google/discover/blog/sima-generalist-ai-agent-for-3d-virtual-environments/](https://deepmind.google/discover/blog/sima-generalist-ai-agent-for-3d-virtual-environments/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'We would like to thank all the paper authors: Maria Abi Raad, Arun Ahuja, Catarina
    Barros, Frederic Besse, Andrew Bolt, Adrian Bolton, Bethanie Brownfield, Gavin
    Buttimore, Max Cant, Sarah Chakera, Stephanie Chan, Jeff Clune, Adrian Collister,
    Vikki Copeman, Alex Cullum, Ishita Dasgupta, Julia Di Trapani, Yani Donchev, Martin
    Engelcke, Ryan Faulkner, Frankie Garcia, Charles Gbadamosi, Zhitao Gong, Lucy
    Gonzales, Karol Gregor, Kshitij Gupta, Arne Olav Hallingstad, Tim Harley, Sam
    Haves, Felix Hill, Ed Hirst, Drew Hudson, Jony Hudson, Steph Hughes-Fitt, Danilo
    J. Rezende,Mimi Jasarevic, Laura Kampis, Rosemary Ke, Thomas Keck, Junkyung Kim,
    Oscar Knagg, Kavya Kopparapu,Andrew Lampinen, Shane Legg, Alexander Lerchner,
    Marjorie Limont, Yulan Liu, Maria Loks-Thompson, Joseph Marino, Kathryn Martin
    Cussons, Loic Matthey, Siobhan Mcloughlin, Piermaria Mendolicchio, Hamza Merzic,
    Anna Mitenkova, Alexandre Moufarek, Valeria Oliveira, Yanko Oliveira, Hannah Openshaw,
    Renke Pan, Aneesh Pappu, Alex Platonov, Ollie Purkiss, David Reichert, John Reid,
    Pierre Harvey Richemond, Tyson Roberts, Giles Ruscoe, Jaume Sanchez Elias, Tasha
    Sandars, Daniel P. Sawyer, Tim Scholtes, Guy Simmons, Daniel Slater, Hubert Soyer,
    Heiko Strathmann, Peter Stys, Allison Tam, Tayfun Terzi, Davide Vercelli, Bojan
    Vujatovic, Marcus Wainwright, Jane X. Wang, Zhengdong Wang, Daan Wierstra, Duncan
    Williams, Nathaniel Wong, Sarah York, and Nick Young.'
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: 'Special thanks to all of the game developers who partnered with us: Coffee
    Stain (*Valheim, Satisfactory, Goat Simulator 3),* Foulball Hangover (*Hydroneer),*
    Hello Games (*No Man''s Sky),* Keen Software House (*Space Engineers),* RubberbandGames
    (*Wobbly Life),* Strange Loop Games (*Eco) and* Tuxedo Labs & Saber Interactive
    (*Teardown).*'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
