- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-29 12:48:47'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-29 12:48:47
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Chris''s Wiki :: blog/web/FirefoxMediaAutoplaySettingsIV'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 'Chris''s Wiki :: blog/web/FirefoxMediaAutoplaySettingsIV'
- en: 来源：[https://utcc.utoronto.ca/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIV](https://utcc.utoronto.ca/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIV)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://utcc.utoronto.ca/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIV](https://utcc.utoronto.ca/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIV)
- en: I've been buying digital music from one of the reasonably good online sources
    of it (the one that recently got acquired, again, making people nervous about
    its longer term future). In addition to the DRM-free lossless downloads of your
    purchases, this place lets you stream albums through your web browser, which in
    my case is an instance of Firefox. Recently, I noticed that my Firefox instance
    at work would seamlessly transition from one track to the next track of an album
    I was streaming, regardless of which label's sub-site I was on, while my home
    Firefox would not; when one track ended, the home Firefox would normally pause
    rather than start playing the next track.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 我一直在一个相当不错的在线音乐资源中购买数字音乐（最近被收购了，再次使人们对其长期未来感到紧张）。除了你购买的无 DRM 无损下载外，这个地方还允许你通过
    Web 浏览器流式传输专辑，我的情况是 Firefox 的一个实例。最近，我注意到，我的工作 Firefox 实例可以无缝地从我正在流式传输的专辑的一首曲目过渡到下一首曲目，无论我在哪个唱片公司的子站点上，而我的家用
    Firefox 则不会；当一首曲目结束时，家用 Firefox 通常会暂停而不是开始播放下一首曲目。
- en: (I listen to both albums I've purchased and albums I haven't and I'm just checking
    out. The former play through the main page for my collection, while the latter
    are scattered around various URLs, because each label or artist gets a <label>.<mumble>.com
    sub-domain for its releases, and then each release has its own page. For the obvious
    reasons, I long ago set my home Firefox to allow my collection's main page to
    autoplay music so it could seamlessly move from one track to the next.)
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: （我听了我购买的专辑和我还没有听过的专辑。前者通过我的集合主页播放，而后者则散布在各种不同的 URL 上，因为每个唱片公司或艺术家都会为其发行的唱片设置一个
    <label>.<mumble>.com 子域名，然后每张唱片都有自己的页面。出于明显的原因，我很久以前就设置了我的家用 Firefox，允许我的集合主页自动播放音乐，这样可以无缝地从一首曲目过渡到下一首。）
- en: Both browser instances were set to disallow autoplay in general in the Preferences
    → Privacy & Security (see [Allow or block media autoplay in Firefox](https://support.mozilla.org/en-US/kb/block-autoplay)),
    and inspection of the per-site settings showed that my work Firefox actually had
    granted no autoplay permissions to sites while my home Firefox had a list of various
    subdomains for this particular vendor that were allowed to autoplay. After spelunking
    my about:config, I identified this as a difference in [`media.autoplay.blocking_policy`](/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIII),
    where the work Firefox had this set to the default of '0' while my home Firefox
    had a [long-standing setting of '2'](/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIII).
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 两个浏览器实例通常在偏好设置 → 隐私和安全中设置禁止自动播放（参见[允许或阻止 Firefox 中的媒体自动播放](https://support.mozilla.org/en-US/kb/block-autoplay)），检查每个站点的设置显示，我的工作
    Firefox 实际上没有授予任何站点自动播放权限，而我的家用 Firefox 则有一个特定供应商的各种子域名列表，允许其自动播放。在 spelunking
    我的 about:config 后，我确定这是一个 [`media.autoplay.blocking_policy`](/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIII)
    的差异，工作 Firefox 将其设置为默认值 '0'，而我的家用 Firefox 则有一个 [长期设置为 '2'](/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIII)。
- en: As discussed in [Mozilla's wiki page on blocking media autoplay](https://wiki.mozilla.org/Media/block-autoplay),
    the default setting for this preference [allows autoplay once you've interacted
    with that tab](https://wiki.mozilla.org/Media/block-autoplay#Sticky_user_gesture_activation_.28default.29),
    while my setting of '2' requires that you always click to (re)start audio or video
    playing (unless the site has been granted autoplay permissions). Historically
    I set this to '2' to try to stop Youtube from autoplaying a second video after
    my first one had finished. In practice this usage has been rendered functionally
    obsolete by Youtube's own 'disable autoplay' setting in its video player (although
    it still works to prevent autoplay if I've forgotten to turn that on in this Firefox
    session or if Youtube is in a playlist and ignores that setting).
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: 正如[Mozilla关于阻止媒体自动播放的wiki页面](https://wiki.mozilla.org/Media/block-autoplay)中所讨论的，默认设置允许您与该选项卡进行交互后自动播放，而我的设置为'2'要求您始终点击才能（重新）开始音频或视频播放（除非该网站已被授予自动播放权限）。从历史上看，我将其设置为'2'是为了阻止Youtube在我的第一个视频播放结束后自动播放第二个视频。实际上，由于Youtube自己的视频播放器中的“禁用自动播放”设置，这种用法在实践中已经被功能上废弃了（尽管如果我忘记在此Firefox会话中打开该设置或Youtube在播放列表中并忽略该设置时，它仍然可以防止自动播放）。
- en: (For both Youtube and this digital music source, a setting of '1', a [transient
    user gesture activation](https://wiki.mozilla.org/Media/block-autoplay#Transient_user_gesture_activation),
    is functionally equivalent to '2' for me because it will normally be more than
    five seconds before the video or track finishes playing, which means that the
    permission will have expired by the time the site wants to advance to the next
    thing.)
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: （对于Youtube和这个数字音乐源，设置为'1'，即[短暂用户手势激活](https://wiki.mozilla.org/Media/block-autoplay#Transient_user_gesture_activation)，对我来说在功能上等同于'2'，因为视频或音轨完成播放通常会超过五秒，这意味着在网站希望进入下一个内容时权限已经过期。）
- en: Since I check out multi-track albums much more often than I look at Youtube
    videos (in this Firefox), and Youtube these days does have a reliable 'disable
    autoplay' setting, I opted to leave `media.autoplay.blocking_policy` set to '0'
    in the work Firefox instance I use for this stuff and I've just changed it to
    '0' in my home one as well. I could avoid this if I set up [a custom profile for
    this music source](/~cks/space/blog/web/FirefoxExtraProfilesHack), but I haven't
    quite gotten to that point yet.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 由于我更频繁地查看多轨专辑而不是观看Youtube视频（在这个Firefox上），而且如今的Youtube确实有可靠的“禁用自动播放”设置，因此我选择将`media.autoplay.blocking_policy`设置为'0'，在我用于这些内容的工作Firefox实例中，我已经将其更改为'0'，并且我在家里的Firefox中也做了同样的更改。如果我为这个音乐源设置了[自定义配置文件](/~cks/space/blog/web/FirefoxExtraProfilesHack)，我可以避免这种情况，但我还没有完全达到那个程度。
- en: (I do wish Firefox allowed, effectively, per-site settings of this as part of
    the per-site autoplay permissions, but I also understand why they don't; I'm sure
    the Preferences and per-site settings UI complexity would be something to see.)
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: （我确实希望Firefox允许，有效地，作为每个站点自动播放权限的一部分，这样的站点设置，但我也理解为什么他们不这样做；我相信偏好和每个站点设置的用户界面复杂性会是一个值得一看的东西。）
- en: (If I'd thought to check [my previous notes on this](/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIII)
    I probably would have been led to `media.autoplay.blocking_policy` right away,
    but it didn't occur to me to check here, even though I knew I'd fiddled a lot
    with Firefox media autoplay over the years. My past self writing things down here
    doesn't guarantee that my future (present) self will remember that they exist.)
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: （如果我当时想去查看[我之前关于此事的笔记](/~cks/space/blog/web/FirefoxMediaAutoplaySettingsIII)，我可能会立即找到`media.autoplay.blocking_policy`，但是我没有想到去这里查看，尽管我知道多年来我已经对Firefox媒体自动播放进行了很多调整。我过去的自己在这里写下的东西并不保证我的未来（现在）的自己会记得它们的存在。）
- en: 'PS: I actually go back and forth on automatically moving on to the next track
    of an album I''m checking out, because the current ''stop after one track'' behavior
    does avoid me absently listening to the whole thing. If I find myself unintentionally
    listening to too many albums that in theory I''m only checking out, I''ll change
    the setting back.'
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
  zh: PS：实际上，我在自动转到我正在查看的专辑的下一首曲目方面来回移动，因为当前的“一首歌结束后停止”行为确实避免了我不经意地听完整个专辑。如果我发现自己无意中听太多理论上我只是在查看的专辑，我会把设置改回来。
