- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-27 14:39:54'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年5月27日14:39:54
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Flipper Zero's Co-Founder Says the Hacking Tool Is All About Exposing Big Tech's
    Shoddy Security
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Flipper Zero的联合创始人说，这款黑客工具的一切都关乎揭示大科技公司脆弱的安全性。
- en: 来源：[https://gizmodo.com/flipper-zeros-co-founder-says-the-hacking-tool-is-all-a-1851279603](https://gizmodo.com/flipper-zeros-co-founder-says-the-hacking-tool-is-all-a-1851279603)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://gizmodo.com/flipper-zeros-co-founder-says-the-hacking-tool-is-all-a-1851279603](https://gizmodo.com/flipper-zeros-co-founder-says-the-hacking-tool-is-all-a-1851279603)
- en: The [Flipper Zero may be one of the most versatile, and most controversial](https://gizmodo.com/flipper-zero-videogame-module-1851300303)
    keychain-sized devices ever put to market. The device can scan, receive, send,
    and mimic several types of signals. It can scan NFC and RFID signals used by many
    common products. It can replicate the frequency used for your workplace’s ID card.
    It’s a $169 doohickey [useful for everyday operations like opening your garage
    door](https://gizmodo.com/flipper-zero-10-useful-things-1851247732) or pen-testing
    security systems. It’s also been accused by the Canadian government of being [capable
    of replicating vehicle key fobs](https://gizmodo.com/canada-moves-to-ban-the-flipper-zero-over-car-hacking-f-1851242790)
    or even [shutting down iPhones with DDoS attacks](https://gizmodo.com/apple-fixes-flipper-zero-shutting-down-iphones-1851102972).
    Apple fixed that issue so the Flipper arguably did its job as a testing tool.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: '[Flipper Zero可能是市场上最多才多艺、也最具争议](https://gizmodo.com/flipper-zero-videogame-module-1851300303)的钥匙链大小设备之一。该设备可以扫描、接收、发送和模仿多种类型的信号。它可以扫描许多常见产品使用的NFC和RFID信号。它可以复制你工作场所ID卡使用的频率。这是一个价值$169的小玩意，[用于日常操作，如打开车库门](https://gizmodo.com/flipper-zero-10-useful-things-1851247732)或对安全系统进行渗透测试。加拿大政府甚至指控它[能够复制车辆钥匙](https://gizmodo.com/canada-moves-to-ban-the-flipper-zero-over-car-hacking-f-1851242790)，甚至[通过DDoS攻击关闭iPhone](https://gizmodo.com/apple-fixes-flipper-zero-shutting-down-iphones-1851102972)。苹果已解决了这个问题，因此Flipper可以说完成了作为测试工具的任务。'
- en: Why Former Employees & Scarlett Johansson Are Questioning OpenAI
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 为什么前员工和斯嘉丽·约翰逊在质疑OpenAI？
- en: <track kind="captions" label="English" src="https://kinja.com/api/videoupload/caption/22550.vtt"
    srclang="en">
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: <track kind="captions" label="English" src="https://kinja.com/api/videoupload/caption/22550.vtt"
    srclang="en">
- en: Flipper cofounder and COO Alex Kulagin has heard much of the controversy, but
    he still sees the product as more than the layman’s idea of a go-to device for
    the *Mr. Robot*-style hackerman. With [Flipper releasing its game controller add-on](https://gizmodo.com/flipper-zero-game-module-controller-raspberry-pi-1851248496)
    this month, Kulagin sees the Zero as a Swiss army knife for the extra geeky or
    the merely tech-curious. To him, the Flipper Zero is a whistleblower for the world’s
    security systems that rely on old, shoddy, and easily hacked tech. Gizmodo spoke
    with Kulagin at length about what plans Flipper has to expand their premiere product
    beyond its Tamagotchi-sized body and his hopes to move beyond the wide-ranging
    controversy that continues to follow it.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: Flipper的联合创始人兼首席运营官Alex Kulagin听说过很多争议，但他仍然认为这款产品不仅仅是普通人心目中的《黑客军团》式黑客设备。随着[Flipper本月发布其游戏控制器附加模块](https://gizmodo.com/flipper-zero-game-module-controller-raspberry-pi-1851248496)，Kulagin认为Zero是专为超级极客或仅仅对技术感兴趣的人设计的瑞士军刀。对他来说，Flipper
    Zero是世界安全系统的告密者，这些系统依赖于老旧、脆弱且容易被黑客攻击的技术。Gizmodo与Kulagin进行了深入交谈，探讨了Flipper计划如何将其首款产品扩展到Tamagotchi大小之外，并希望能够摆脱继续跟随它的广泛争议。
- en: '*This interview has been edited for clarity and brevity.*'
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: '*本次采访已经过编辑，以增加清晰度和简洁度。*'
- en: '**Gizmodo:** So can you give me a rundown of what the Video Game Module is
    and what it adds to the Flipper Zero that’s not already there.'
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: '**Gizmodo：** 那么你能给我简要介绍一下视频游戏模块是什么，以及它在Flipper Zero上增加了哪些功能？'
- en: '**Alex Kulagin:** We’re very excited because it’s our first collaboration or
    partnership of such scale. Raspberry Pi are legends in this world. The Video Game
    Model brings entertainment capabilities, as the Flipper lacked some of those important
    features. First of all, with video outputs, you can actually now mirror the Flipper
    screen to a bigger TV. It’s very fun to see. It’s weird, because the Flipper screen
    is super small. It’s like 640х480 resolution, but we are able to scale it up.
    And it’s fun to see it on a huge 4K TV. So the Flipper becomes very big, but it’s
    very sharp. We built in a motion sensor, the IMU, so you can play by tilting the
    device. One of the first demo games built for this is the *Air Arkanoid* game,
    which is very fun.'
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: '**Alex Kulagin:** 我们非常激动，因为这是我们首次在这个规模上的合作或伙伴关系。树莓派在这个领域是传奇。视频游戏模型带来了娱乐功能，因为
    Flipper 缺少一些重要的功能。首先，通过视频输出，你现在可以将 Flipper 屏幕镜像到更大的电视上。看起来非常有趣。有点奇怪，因为 Flipper
    屏幕非常小。像是 640x480 的分辨率，但我们能够放大它。在巨大的 4K 电视上看到它非常有趣。因此，Flipper 变得非常大，但非常清晰。我们内置了一个运动传感器，IMU，所以你可以通过倾斜设备来玩游戏。其中为此开发的第一个演示游戏是
    *Air Arkanoid* 游戏，非常有趣。'
- en: '**Giz:** Like a Wii controller?'
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 就像 Wii 控制器一样吗？'
- en: '**AK:** Yeah. The third main feature, though it’s not less important, is that
    it’s built on the Raspberry Pi microcontroller. It can use the existing library
    of apps and code that’s already there and built for the Raspberry Pi Pico. The
    chip is quite powerful and has some unique features. For example, you can run
    Python on it. The Flipper can normally only run C [the coding language], and Python
    is much easier to understand.'
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** 是的。尽管它并不是不重要的第三个主要功能，但它是基于树莓派微控制器构建的。它可以使用已有的应用程序和代码库，这些代码已经为树莓派 Pico
    构建。该芯片相当强大，并具有一些独特的功能。例如，你可以在上面运行 Python。Flipper 通常只能运行 C 语言，而 Python 更容易理解。'
- en: '**Giz:** So it could already connect to TVs [through IR signals] and other
    IoT tech, but will you be able to cast your own video from a separate device to
    another screen through the Flipper. Even go so far as to cast it onto the screens
    of Times Square?'
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 所以它已经可以通过电视（通过红外信号）和其他物联网技术进行连接，但你是否能够通过 Flipper 从另一台设备投射自己的视频到另一个屏幕上？甚至远至在时代广场的屏幕上投射？'
- en: '**AK:** No, it actually requires the cable connection to do so. It’s like a
    standard DVI-D output, which many TVs support. I don’t think you can do anything
    in that area with this, but you never know. Sometimes the community comes up with
    some crazy abilities. But, by design, it’s more for entertainment and not for
    hacking stuff.'
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** 不是，实际上需要连接电缆才能这样做。就像标准的 DVI-D 输出，许多电视支持。我不认为你可以在这个领域做任何事情，但你永远不知道。有时社区会提出一些疯狂的能力。但从设计上来看，它更多用于娱乐，而不是黑客活动。'
- en: '**Giz:** Gotcha. That kind of points to your company’s philosophy. You guys
    create this tech very much for the DIYers and the people are just making their
    own stuff. When you’re designing something like this, where does your mind go?
    How did this kind of thing come together in the way that it did?'
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 明白了。这种情况指向了你们公司的理念。你们非常注重为 DIY 爱好者和那些自己制作东西的人创造这种技术。当你设计这样的产品时，你的思路是怎样的？这种东西是如何如此完美地结合在一起的？'
- en: '**AK:** Flipper is a very expandable thing. So its core invites design. We
    made it open source, it has all these GPIO pins, it has many features out of the
    box already. But we designed it that way to expand it even more. So often, we
    have some internal hardware and software we need for work, or it’s just fun to
    do. This idea of outputting the video from Flipper to an external monitor actually
    started as a project from one of our developers because we wanted to show the
    Flipper screen on the front door of our office. They were using a Raspberry Pi
    Pico for this, and we had some testing that showed it actually works. So we hacked
    some things to do it. Then it became like this idea that we can actually make
    a product out of it. It’s similar to how we came up with the WiFi dev board we
    sell because our supplier didn’t have this debugging hardware in stock because
    of the chip shortage. So we had to come up with our hardware to actually debug
    and use it inside the team.'
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK：** Flipper 是一个非常可扩展的东西。因此，它的核心邀请设计。我们将其开源，它已经有了许多GPIO引脚，已经具备了许多功能。但我们设计它的方式是为了更进一步扩展它。所以通常，我们需要一些内部硬件和软件来完成工作，或者只是为了好玩。实际上，从Flipper输出视频到外部监视器的想法最初是我们的一个开发人员的项目，因为我们想要在办公室的前门上展示Flipper屏幕。他们使用了树莓派Pico进行这项工作，我们进行了一些测试，结果表明它确实可行。所以我们对一些事情进行了一些修改来实现它。然后它变成了这样一个想法，我们实际上可以把它做成一个产品。这与我们如何推出我们销售的WiFi开发板类似，因为由于芯片短缺，我们的供应商没有这种调试硬件库存。所以我们不得不想出我们自己的硬件来实际上进行调试和在团队内部使用它。'
- en: '**Giz:** How did you get connected to Raspberry Pi? Did you reach out to them
    or had you been in communication with them for a while for some sort of partnership?'
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz：** 你是如何接触到树莓派的？是你主动联系他们，还是你们之间已经有了一段时间的沟通，准备进行某种形式的合作？'
- en: '**AK:** I think they reached out to us first. At some point, we just started
    talking about what we could do together. Because for them, before they were buying
    chips from other vendors, and now they’re trying to make their own chips. And
    it’s an important area of business for them. So we were trying to find where we
    can be connected so their audience and our audience will be happy about the products.'
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK：** 我认为他们最先联系了我们。在某个时候，我们开始讨论我们可以一起做什么。因为对于他们来说，在他们以前是从其他供应商购买芯片，现在他们正在尝试制造自己的芯片。这对他们来说是一个重要的业务领域。所以我们试图找到我们可以连接的地方，以便他们的观众和我们的观众都对产品感到满意。'
- en: '**Giz:** You guys are in an interesting place. The devices are legal pretty
    much everywhere, but you’ve caught flak from people who I don’t know if they really
    understand what the device is, or how it’s used. What are your thoughts on the
    current discussions about the Flipper itself and how people are using it now,
    for both “legitimate uses” or just penetrating different systems to prove that
    they can?'
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz：** 你们处于一个有趣的位置。这些设备在几乎所有地方都是合法的，但你们却受到了一些人的批评，我不知道他们是否真正了解这个设备，或者它如何被使用。关于Flipper本身及人们如何使用它进行“合法用途”或者只是为了证明他们可以渗透不同系统的当前讨论，你有什么想法？'
- en: '**AK:** It’s important to know that Flipper is actually not, you know, cutting
    edge technology. We packed all this technology, all this, like access control
    technologies that we use every day, in one device. But it’s not like it can interact
    with most of the super modern, cutting-edge technologies, right? Like a modern
    car, the Flipper can’t actually do anything with that. I think it’s important
    to understand there are a lot of things around us that are really outdated and
    old, something people don’t really think about a lot. Like, you try to put the
    most secure key lock in your door, but many people don’t think that you should
    have a secure garage door as well, and they have a garage opening device from
    the 2000s. People just don’t think that it can be hacked in any way, but people
    use these cheap products that are not encrypted, and these vulnerabilities have
    been known for decades. We don’t do anything new in this area. But the awareness
    of users who possess these devices is very low.'
  id: totrans-split-22
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK：** 重要的是要知道，Flipper 实际上并不是什么尖端技术。我们将所有这些技术，所有这些像我们每天使用的访问控制技术，都集成到了一个设备中。但它并不能与大多数超现代、尖端的技术互动，对吧？比如现代汽车，Flipper
    实际上无法与之做任何互动。我认为重要的是要理解，我们周围有很多真的非常过时和老旧的东西，这些东西人们并不经常考虑。比如，你尝试在门上安装最安全的钥匙锁，但许多人并不觉得你的车库门也应该安全，他们在2000年代就使用了一个不加密的车库开启设备。人们只是不认为它可能以任何方式被入侵，但人们使用这些廉价的产品，这些漏洞几十年来一直存在。在这个领域，我们并没有做任何新的事情。但拥有这些设备的用户的意识非常低。'
- en: '**Giz:** So you see yourselves as bringing awareness to these issues?'
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 所以你们认为自己正在提高人们对这些问题的意识？'
- en: '**AK:** What Flipper brings is awareness that, guys, this thing is not secure,
    like if you should actually think if something can be hacked by a $100 toy, maybe
    it’s too old. This is important for us to do. Now we see some vendors who sell
    NFC readers actually bring new products to market with Flipper Zero-proof advertisements.
    They use it as a marketing thing, which is a win for us, right? That means we
    did something good. This is the philosophy we stick to it.'
  id: totrans-split-24
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** Flipper带来的意识是，伙计们，这个东西并不安全，如果一个$100的玩具可以被黑客攻击，也许它太老了。这对我们来说很重要。现在我们看到一些销售NFC读卡器的供应商实际上在市场上推出了基于Flipper
    Zero的广告。他们将其用作营销工具，这对我们来说是一个胜利，对吧？这意味着我们做了一些好事。这是我们坚持的哲学。'
- en: '**Giz:** What about the people who don’t use it in the prescribed way? There’s
    several other firmwares that support the Flipper Zero'
  id: totrans-split-25
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 那些不按规定方式使用的人怎么办？还有几个其他支持Flipper Zero的固件'
- en: '**AK:** We monitor a lot of stuff that happens with a device. We have Discord
    and we have a Reddit to see what’s happening. We monitor alternative firmwares
    and what’s happening there because it’s also open-sourced. And if we see that
    something can be sensitive enough, we try to contain it. Like with sub-Ghz frequencies
    and login codes. Even if it’s really old and hacked in many ways, even if it’s
    technically possible to replay it, we don’t let users do it, there’s no button.
    The analogy I have is if it’s like a keylock or a doorknob. If it’s a doorknob,
    it’s not encrypted in any way. It’s not actually hacking something, you’re just
    making people realize that your thing is not secure at all.'
  id: totrans-split-26
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** 我们监控设备发生的许多事情。我们有Discord和Reddit来了解发生的情况。我们监控替代固件和那里的情况，因为它也是开源的。如果我们发现某些东西可能足够敏感，我们会试图控制它。比如次Ghz频率和登录代码。即使它很老旧并且已经被多种方式黑过，即使从技术上讲重新播放是可能的，我们也不会让用户这样做，没有按钮。我有一个类比，就像一个钥匙锁或者门把手。如果是门把手，它完全没有加密。实际上你并没有黑客什么，你只是让人们意识到你的东西根本不安全。'
- en: '**Giz:** I think that goes back to the very minimal way that some people think
    of hacking, especially when most hacking is literally just social engineering.
    Do you feel like sometimes that you’re almost on a mission to educate the world
    about what these definitions mean from a technical stance?'
  id: totrans-split-27
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 我认为这追溯到某些人对黑客行为非常极简的看法，特别是大部分黑客其实只是社会工程学而已。你是否觉得有时候你几乎是在一种使命中，从技术角度教育世界这些定义的含义？'
- en: '**AK:** Many people buy Flipper without knowing anything. They see a TikTok
    and think its cool, they see it do something weird like opening a Tesla charging
    port and they think what is this cyberpunk device? They buy it, and they say “okay,
    what can I do with it.” This is just tech-curious people, not established geeks,
    who never touched a Raspberry Pi or Arduino stuff. But these little hacks bring
    them to an awareness of how it actually works. We think it’s important to educate
    people about how this stuff works and what the risks are. There are many people
    with much more sophisticated devices. There’s stuff sold on Amazon [Flipper has
    been banned from the site] that is far more capable. We don’t see it as creating
    more risk. We see it as we’re reducing the risk for many people just by letting
    them know their stuff has flaws.'
  id: totrans-split-28
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** 许多人购买Flipper而不知道任何事情。他们在TikTok上看到觉得很酷，看它做一些奇怪的事情，比如打开特斯拉充电口，他们就觉得这是什么赛博朋克设备？他们买了，然后说“好的，我能用它做什么。”这些只是对技术感兴趣的人，不是成熟的极客，从未接触过树莓派或Arduino之类的东西。但这些小小的黑客行为让他们意识到实际上它是如何工作的。我们认为向人们教育这些东西如何工作及其风险是很重要的。有许多人拥有更复杂的设备。亚马逊上售卖的一些东西[Flipper已经被禁止在网站上出售]，功能更加强大。我们不认为这会增加风险。我们认为通过让他们知道他们的设备存在缺陷，我们正在减少风险。'
- en: '**Giz:** Will we ever reach a point when our technical ability is equivalent
    to our technical knowledge as a society?'
  id: totrans-split-29
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 我们会不会有一天技术能力与我们社会的技术知识水平达到等同？'
- en: '**AK:** I think with enough publicity about it. Before 2015, nobody was thinking
    about data privacy too much. We were just putting things on Facebook and didn’t
    think about what happened next. For the last eight years, it’s become a very big
    thing to talk about. And now everybody’s thinking about privacy, about cookies,
    all this stuff. It’s become so big because the media is talking about it so much
    and Flipper makes the media talk about these things too. For example this Apple
    DDoS thing. It was there for a long time, you could do it with many devices, but
    Flipper made it more accessible and people started talking about it, and Apple
    had to actually fix it, which is a good thing. You cannot reach maximum awareness.
    It’s not possible to have total awareness, but maybe we could have it at some
    basic level, at least.'
  id: totrans-split-30
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** 我认为只要有足够的宣传。在2015年之前，没有人太在意数据隐私。我们只是把东西放在Facebook上，没有考虑接下来会发生什么。在过去的八年里，隐私问题成为了一个非常重要的话题。现在每个人都在关注隐私，关注Cookie等等。这些话题之所以变得如此重要，是因为媒体谈论得很多，而
    Flipper 也让媒体开始谈论这些问题。例如这个苹果的DDoS事件。这个问题已经存在了很长时间，你可以用许多设备来做，但Flipper使它变得更容易实现，人们开始谈论它，而苹果不得不实际修复它，这是一件好事。你无法达到最大的意识。完全意识是不可能的，但也许我们可以在某种基本水平上拥有它，至少是这样。'
- en: '**Giz:** What are your future plans? Are you going to keep expanding the Flipper’s
    capabilities with more modules?'
  id: totrans-split-31
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 你们未来有什么计划？会继续通过更多模块扩展 Flipper 的功能吗？'
- en: '**AK:** In terms of models, we have a few in development right now. It’s going
    to be low in terms of other things coming out this year, less significant than
    [the Video Game Module], but we have some important technologies we always wanted
    to do on paper, but there’s no physical hardware to do it with yet. Our ultimate
    goal is to make a market for it. We didn’t restrict people from making and selling
    their own modules. We want to be like the Arduino market, which has tons and tons
    of models and people can buy from different vendors. The greater goal is to show
    what you actually can do. But we’ll launch a couple more modules and we’ll see.
    We also have our attention on new devices we built outside of Flipper Zero.'
  id: totrans-split-32
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** 在模型方面，我们目前有几个正在开发中。今年其他事物的推出将较少，比如[视频游戏模块]不那么重要，但我们有一些重要的技术一直想在纸上做，但还没有物理硬件来实现。我们的最终目标是为此打造一个市场。我们并没有限制人们制作和销售自己的模块。我们希望成为像
    Arduino 市场那样，有大量的模型可以从不同的供应商购买。更大的目标是展示你实际可以做什么。但我们会推出几个新模块，然后看看情况。我们还关注我们在 Flipper
    Zero 之外构建的新设备。'
- en: '**Giz:** Any chance you can give me a hint on those plans for future, non-Flipper
    devices?'
  id: totrans-split-33
  prefs: []
  type: TYPE_NORMAL
  zh: '**Giz:** 你能给我透露一些关于未来非 Flipper 设备计划的提示吗？'
- en: '**AK:** Ehh, not really, not at the moment. But we’ll let you know.'
  id: totrans-split-34
  prefs: []
  type: TYPE_NORMAL
  zh: '**AK:** 嗯，目前不是。但是我们会通知你的。'
