- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-29 12:31:26'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-29 12:31:26'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'GitHub - rstudio/rstudio: RStudio is an integrated development environment
    (IDE) for R'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 'GitHub - rstudio/rstudio: RStudio是用于R语言的集成开发环境（IDE）。'
- en: 来源：[https://github.com/rstudio/rstudio](https://github.com/rstudio/rstudio)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://github.com/rstudio/rstudio](https://github.com/rstudio/rstudio)
- en: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: '`<include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>`'
- en: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># rstudio/rstudio
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: '`<main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># rstudio/rstudio'
- en: This commit does not belong to any branch on this repository, and may belong
    to a fork outside of the repository.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 这个提交不属于仓库中的任何分支，并可能属于仓库外的一个分叉。
- en: <include-fragment src="/rstudio/rstudio/spoofed_commit_check/62afebb1eb74c6e36fd70d5dfd3657b745f18e90"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: '`<include-fragment src="/rstudio/rstudio/spoofed_commit_check/62afebb1eb74c6e36fd70d5dfd3657b745f18e90"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>`'
- en: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: '`<ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.`'
- en: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: '`<template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>`'
