- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:50:57'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Global rate-limiting API for distributed applications - rlimit.com - rlimit.com
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://rlimit.com](https://rlimit.com)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Global
  id: totrans-split-6
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: rate limiting
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: API
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: for distributed applications
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: Start rate limiting user actions with a couple of lines.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: Protect your applications from abuse and ensure high availability for all users.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: '**Works everywhere** - our API can be used with any language and framework'
  id: totrans-split-12
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Flexible** - rate limit by your internal metadata, like account/user ID per
    operation'
  id: totrans-split-13
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Highly available** - deployed across multiple regions, low latency, high
    availability'
  id: totrans-split-14
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Real-time events** - see rate limit requests as they happen'
  id: totrans-split-15
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
