- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:50:57'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Global rate-limiting API for distributed applications - rlimit.com - rlimit.com
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://rlimit.com](https://rlimit.com)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Global
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: rate limiting
  prefs: []
  type: TYPE_NORMAL
- en: API
  prefs: []
  type: TYPE_NORMAL
- en: for distributed applications
  prefs: []
  type: TYPE_NORMAL
- en: Start rate limiting user actions with a couple of lines.
  prefs: []
  type: TYPE_NORMAL
- en: Protect your applications from abuse and ensure high availability for all users.
  prefs: []
  type: TYPE_NORMAL
- en: '**Works everywhere** - our API can be used with any language and framework'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Flexible** - rate limit by your internal metadata, like account/user ID per
    operation'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Highly available** - deployed across multiple regions, low latency, high
    availability'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Real-time events** - see rate limit requests as they happen'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
