- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:45:04'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Heresy II – Comments Are Code – Responsible Automation
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://responsibleautomation.wordpress.com/2018/02/01/heresy-ii-comments-are-code/](https://responsibleautomation.wordpress.com/2018/02/01/heresy-ii-comments-are-code/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'I hold an unpopular stance: code comments are as important as the code itself.
    OK, maybe that’s a little overstated, but I maintain that code comments are critical
    to code readability and maintainability.'
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: Before you see if I weigh more than a duck, please hear me out…
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: When I was a college undergrad, I had the privilege of working on a project
    with a graduate professor and some grad students. The core of the project was
    creating a software package to perform type checking on a non-typed, functional
    language; this was both weird and cool…but I digress. As part of the project,
    we were required to comment our code. My teammates and I diligently went about
    documenting each function and other interesting parts of the code we’d created.
    When we’re finished, we proudly submitted our code to the professor.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: 'The next day, the professor asked us to come to her office. She proceeded to
    scold us on our commenting…I’ll paraphrase: I can read code, don’t tell me what
    the code is doing, tell me why the code is doing that. She sent us home to think
    and told us to come back the next day and re-comment everything.'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: This was some of the best advice I’ve ever received regarding coding. Let me
    tell you why.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: As you can probably deduce, our code comment explained *what* the code was doing.
    “Go through the list, added each name to the pending transaction list” or some
    such literal thing. As my professor correctly stated, she (and presumably whoever
    else is looking at the code) can read code; she understood what it was doing,
    but not necessarily *why*. The comments were missing *context*; they didn’t explain
    why we’d chosen that implementation and, just as importantly, why we’d not chosen
    a different implementation.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: Please, before you get out the duck-weighing equipment, allow me to continue…
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: 'I’m a big fan of self-documenting code. I’m like most developers: I don’t want
    to document my code. I want to write code that is self-explanatory, straightforward,
    easy to use, and to maintain. One of the last things I want to do with code is
    go through and write a bunch of comments. Self-documenting code is nice and all,
    but at some point, as with most things it can be taken to extremes. For example,
    I could write a method name something like'
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  id: totrans-split-14
  prefs: []
  type: TYPE_PRE
- en: I consider that a preposterous function or method name. Sure, it’s descriptive.
    Sure, nowadays, most of us use IDEs that have code completion so we don’t really
    need to type all those characters. I still think, however, that it is far clearer
    to include a comment before that “reverse search” loop that says something like
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  id: totrans-split-16
  prefs: []
  type: TYPE_PRE
- en: What’s the big deal about going through the list backward anyway? Perhaps nothing.
    But if it’s not important, then why not go through the list in a more intuitive
    way, i.e. starting at index 0? If it is important to go through backward, perhaps
    it’s important enough to document why. If we don’t comment the why, the reason,
    the context, we run the risk of a future author changing the algorithm and unwittingly
    causing some kind of issue because the algorithm ran “better” when searching the
    list in reverse.
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: But wait! The comments will get out of sync with the code! Well, they shouldn’t.
    When we perform our code reviews, we need to review the comments as well as the
    code. Comments should be correct, understandable, and valuable; we need to keep
    these points in mind during our reviews.
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
- en: When should we consider using code comments?
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
- en: The code is straightforward but not intuitive (e.g. the *why* is not evident
    from the code itself)
  id: totrans-split-20
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: When the code is not straightforward for deliberate reasons, such as writing
    it in a more straightforward or self-documenting manner would sacrifice performance
  id: totrans-split-21
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: A comment will increase readability or maintainability
  id: totrans-split-22
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: A comment will remind us where the code came from, such as a book or StackOverflow
    URL.
  id: totrans-split-23
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Generating documentation (see example below)
  id: totrans-split-24
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: When should we consider not commenting?
  id: totrans-split-25
  prefs: []
  type: TYPE_NORMAL
- en: When both the behavior and the context are evident in the code
  id: totrans-split-26
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: When simplifying the code or abstracting into a “helper” method would make the
    code self-documenting without sacrificing value (e.g. performance, maintainability,
    readability, etc.)
  id: totrans-split-27
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'At the risk of being hypocritical, I detest standard comment blocks at the
    beginning of each file, class, and method. It seems like valueless busy work,
    especially since I do try to make my code rather descriptive. Then one day, when
    I was grousing about this subject, a less experienced member of my team (yes,
    we can learn from people of all experience levels) said: “you know, those comment
    blocks are where that convenient IntelliSense documentation comes from, right?”
    I’d not considered that. I silently cursed him for being right. I still detest
    doing that kind of commenting, but I now understand the value it provides, so
    I keep the grousing to myself…well, except for now.'
  id: totrans-split-28
  prefs: []
  type: TYPE_NORMAL
- en: Yes, it’s generally better for code to be self-documenting. In lieu of being
    dumb for dumb’s sake, however, perhaps add some code comments to provide context
    for others…or perhaps your future self.
  id: totrans-split-29
  prefs: []
  type: TYPE_NORMAL
- en: '*Like this? Catch me at an [upcoming event](https://responsibleautomation.wordpress.com/upcoming-events/)!*'
  id: totrans-split-30
  prefs: []
  type: TYPE_NORMAL
