- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:42:10'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'No deployments on Fridays: A good practice for software development teams'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://deploybot.com/blog/no-deployments-on-fridays-a-good-practice-for-software-development-teams](https://deploybot.com/blog/no-deployments-on-fridays-a-good-practice-for-software-development-teams)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'No deployments on Fridays: A good practice for software development teams'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: Deploying new code to production can be a stressful experience, especially if
    it's done at the end of the week. That's why many software development teams follow
    a practice called "no deployments on Fridays."
  prefs: []
  type: TYPE_NORMAL
- en: There are a few reasons why this is a good practice. First, it gives teams more
    time to test and troubleshoot their code before it goes live. Second, it reduces
    the risk of deploying code that contains bugs or errors. Third, it gives team
    members more time to relax and enjoy their weekends without having to worry about
    work.
  prefs: []
  type: TYPE_NORMAL
- en: Of course, there are some cases where it may be necessary to deploy code on
    a Friday. For example, if a critical bug is discovered, or if a new feature is
    absolutely needed for the business. However, in general, it's best to avoid deploying
    code on Fridays if possible.
  prefs: []
  type: TYPE_NORMAL
- en: DeployBot worried about Fridays deployments.
  prefs: []
  type: TYPE_NORMAL
- en: 'If you’ve read this far, you’re probably a DeployBot user and familiar with
    version control systems, CI/CD, and other related topics. If not, we’ve compiled
    several beginner’s guides: [Laravel, Digital Ocean](https://deploybot.com/guides-code-deployment-tools/deploy-a-laravel-app-to-digitalocean),
    [Ruby on Rails](https://deploybot.com/guides-code-deployment-tools/deploy-ruby-on-rails-to-digitalocean),
    [Docker](https://deploybot.com/guides-code-deployment-tools/getting-started-using-docker-with-deploybot),
    [Craft CMS](https://deploybot.com/guides-code-deployment-tools/deploy-craft-cms-to-digitalocean),
    [Ghost CMS](https://deploybot.com/guides-code-deployment-tools/deploy-ghost-themes),
    [Google Web Starter Kit](https://deploybot.com/guides-code-deployment-tools/deploy-google-web-starter-kit-to-digitalocean),
    [Grunt](https://deploybot.com/guides-code-deployment-tools/building-assets-with-grunt-or-gulp-during-deployment)
    or [Gulp](https://deploybot.com/guides-code-deployment-tools/building-assets-with-grunt-or-gulp-during-deployment),
    [Slack](https://deploybot.com/guides-code-deployment-tools/chatops-deploybot-slack),
    [Python, Heroku](https://deploybot.com/guides-code-deployment-tools/deploy-a-python-application-to-heroku-with-deploybot)
    and many more.'
  prefs: []
  type: TYPE_NORMAL
- en: '[Learn how to get started with DeployBot here.](https://deploybot.com/guides-code-deployment-tools/getting-started-with-deploybot)'
  prefs: []
  type: TYPE_NORMAL
- en: Tips for a "no deployments on Fridays" policy
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '**Plan your deployments ahead of time.** This will give you plenty of time
    to test and troubleshoot your code before the end of the week.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Set up a continuous integration and continuous delivery (CI/CD) pipeline.**
    This will automate your testing and deployment process, making it easier to deploy
    code quickly and safely.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Have a rollback plan in place.** In case something goes wrong with a deployment,
    you should be able to quickly roll back to the previous version of your code.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Communicate your policy to your team and stakeholders**. This will help everyone
    understand why you''re following a "no deployments on Fridays" policy and what
    to expect.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Following a "no deployments on Fridays" policy can help you reduce stress, improve
    your code quality, and protect your business from costly outages.
  prefs: []
  type: TYPE_NORMAL
- en: Benefits of no deployments on Fridays
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'Here are some of the benefits of following a "no deployments on Fridays" policy:'
  prefs: []
  type: TYPE_NORMAL
- en: '**Reduces stress:** Deploying new code to production can be a stressful experience,
    especially if it''s done at the end of the week. By following a "no deployments
    on Fridays" policy, teams can reduce their stress levels and focus on other tasks.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Improves code quality:** Having more time to test and troubleshoot code before
    it''s deployed can help to improve code quality. This can lead to fewer bugs and
    errors, which can save teams time and money in the long run.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Protects businesses from costly outages:** Deploying code that contains bugs
    or errors can lead to costly outages. By following a "no deployments on Fridays"
    policy, teams can reduce the risk of deploying code that contains bugs and errors.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Challenges of no deployments on Fridays
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'There are a few challenges that teams may face when following a "no deployments
    on Fridays" policy:'
  prefs: []
  type: TYPE_NORMAL
- en: '**Pressure to deploy code:** In some cases, teams may feel pressure to deploy
    code on a Friday, even if they don''t have enough time to test it thoroughly.
    It''s important for teams to resist this pressure and stick to their policy of
    no deployments on Fridays.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Unexpected problems:** Sometimes, unexpected problems can arise that require
    teams to deploy code on a Friday. For example, a critical bug may be discovered,
    or a new feature may be absolutely needed for the business. In these cases, teams
    should carefully weigh the risks and benefits of deploying code on a Friday before
    making a decision.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Communicating the policy:** It''s important for teams to communicate their
    "no deployments on Fridays" policy to their team and stakeholders. This will help
    everyone understand why the policy is in place and what to expect.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Conclusion
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Following a "no deployments on Fridays" policy can help software development
    teams reduce stress, improve their code quality, and protect their businesses
    from costly outages. While there are some challenges that teams may face when
    following this policy, the benefits outweigh the risks.
  prefs: []
  type: TYPE_NORMAL
