- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 14:53:39'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 14:53:39'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Product - Chip - Cerebras
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 产品 - 芯片 - Cerebras
- en: 来源：[https://www.cerebras.net/product-chip/](https://www.cerebras.net/product-chip/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.cerebras.net/product-chip/](https://www.cerebras.net/product-chip/)
- en: To provide the best experiences, we use technologies like cookies to store and/or
    access device information. Consenting to these technologies will allow us to process
    data such as browsing behavior or unique IDs on this site. Not consenting or withdrawing
    consent, may adversely affect certain features and functions.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 为了提供最佳体验，我们使用诸如 cookie 之类的技术来存储和/或访问设备信息。同意这些技术将允许我们处理例如在本网站上的浏览行为或唯一标识的数据。不同意或撤销同意可能会对某些功能和功能产生不利影响。
- en: <details class="cmplz-category cmplz-functional"><summary></summary>
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: <details class="cmplz-category cmplz-functional"><summary></summary>
- en: The technical storage or access is strictly necessary for the legitimate purpose
    of enabling the use of a specific service explicitly requested by the subscriber
    or user, or for the sole purpose of carrying out the transmission of a communication
    over an electronic communications network.</details> <details class="cmplz-category
    cmplz-preferences"><summary></summary>
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 用于明确请求的特定服务的使用或用于在电子通信网络上进行通信传输的唯一目的的合法目的需要技术存储或访问。</details> <details class="cmplz-category
    cmplz-preferences"><summary></summary>
- en: The technical storage or access is necessary for the legitimate purpose of storing
    preferences that are not requested by the subscriber or user.</details> <details
    class="cmplz-category cmplz-statistics"><summary></summary>
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: 用于存储未由订阅者或用户请求的偏好项的合法目的需要技术存储或访问。</details> <details class="cmplz-category cmplz-statistics"><summary></summary>
- en: The technical storage or access that is used exclusively for statistical purposes.
    The technical storage or access that is used exclusively for anonymous statistical
    purposes. Without a subpoena, voluntary compliance on the part of your Internet
    Service Provider, or additional records from a third party, information stored
    or retrieved for this purpose alone cannot usually be used to identify you.</details>
    <details class="cmplz-category cmplz-marketing"><summary></summary>
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: 用于纯粹统计目的的技术存储或访问。用于纯粹匿名统计目的的技术存储或访问。在没有传票、互联网服务提供商的自愿合规或第三方的额外记录的情况下，仅为此目的存储或检索的信息通常不能用于识别您。</details>
    <details class="cmplz-category cmplz-marketing"><summary></summary>
- en: The technical storage or access is required to create user profiles to send
    advertising, or to track the user on a website or across several websites for
    similar marketing purposes.</details>
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 用于创建用户配置文件以发送广告或跟踪用户在一个网站或多个网站上的活动，以实现类似营销目的的技术存储或访问。</details>
