- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 14:37:05'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 14:37:05'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Product Analyst Intern at SuperKalam | Y Combinator
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 超级卡拉姆产品分析师实习生 | Y Combinator
- en: 来源：[https://www.ycombinator.com/companies/kalam/jobs/R4P4ZvJ-product-analyst](https://www.ycombinator.com/companies/kalam/jobs/R4P4ZvJ-product-analyst)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.ycombinator.com/companies/kalam/jobs/R4P4ZvJ-product-analyst](https://www.ycombinator.com/companies/kalam/jobs/R4P4ZvJ-product-analyst)
- en: '**Fill your details** [**here**](https://forms.gle/t7gBmjL2CNj44JSX7) when
    you apply.'
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: '**填写您的详细信息** [**此处**](https://forms.gle/t7gBmjL2CNj44JSX7) 在您申请时。'
- en: Your resume will be short listed as per your **projects or prior internship
    experience**. After this, an introductory call will be set.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 您的简历将根据**项目或之前的实习经历**进行初步筛选。之后，将安排一次介绍性电话。
- en: '**Introductory call (20 min)** - We will discuss your work in detail. You can
    ask relevant questions. Accordingly, the next steps will be discussed.'
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: '**介绍性电话（20 分钟）** - 我们将详细讨论您的工作。您可以提出相关问题。接下来的步骤将相应讨论。'
- en: '**Analytics assessment**, 1 hour F2F, This is to evaluate your analytical prowess.'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: '**分析评估**，1 小时面对面，这是为了评估您的分析能力。'
- en: '**Product and insights**, 1 hour F2F. This is to evaluate how to you can use
    insights to shape the product better.'
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: '**产品和见解**，1 小时面对面。这是为了评估如何利用见解更好地塑造产品。'
- en: '**Final discussion round**'
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: '**最终讨论环节**'
