- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:37:05'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Product Analyst Intern at SuperKalam | Y Combinator
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.ycombinator.com/companies/kalam/jobs/R4P4ZvJ-product-analyst](https://www.ycombinator.com/companies/kalam/jobs/R4P4ZvJ-product-analyst)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: '**Fill your details** [**here**](https://forms.gle/t7gBmjL2CNj44JSX7) when
    you apply.'
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: Your resume will be short listed as per your **projects or prior internship
    experience**. After this, an introductory call will be set.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: '**Introductory call (20 min)** - We will discuss your work in detail. You can
    ask relevant questions. Accordingly, the next steps will be discussed.'
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: '**Analytics assessment**, 1 hour F2F, This is to evaluate your analytical prowess.'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: '**Product and insights**, 1 hour F2F. This is to evaluate how to you can use
    insights to shape the product better.'
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: '**Final discussion round**'
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
