- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-29 12:35:59'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Sam Altman may have Siri and Alexa in his sights after OpenAI filed a 'digital
    voice assistant' trademark application
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.businessinsider.nl/sam-altman-may-have-siri-and-alexa-in-his-sights-after-openai-filed-a-digital-voice-assistant-trademark-application/](https://www.businessinsider.nl/sam-altman-may-have-siri-and-alexa-in-his-sights-after-openai-filed-a-digital-voice-assistant-trademark-application/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: OpenAI filed a trademark application for a "voice engine" and to build "digital
    voice assistants."
  id: totrans-split-6
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: The application came a day after Sam Altman hinted at other releases before
    the upcoming GPT-5.
  id: totrans-split-7
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: OpenAI also filed trademark applications in October for future models like GPT-6
    and GPT-7.
  id: totrans-split-8
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '[Sam Altman](https://www.businessinsider.com/sam-altman-chatgpt-openai-ceo-career-net-worth-ycombinator-prepper-2023-1)
    might be striving to take on Apple''s Siri and Amazon''s Alex voice assistants.'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: OpenAI has [filed](https://tsdr.uspto.gov/#caseNumber=98456635&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch)
    a trademark application to build "digital voice assistants" and a "voice engine",
    which signals that it may be set to release a new product.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: The application was filed with the US Patent and Trademark Office on Tuesday,
    a day after an interview with Sam Altman was broadcast in which he said OpenAI
    has "a lot of other important things to release" before its upcoming GPT-5.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: Those features might not come to fruition as companies often file trademark
    applications for ideas that never see the light of day. OpenAI is, however, expected
    to release a "materially better" upgrade of its ChatGPT model mid-year, as [Business
    Insider previously](https://www.businessinsider.com/openai-launch-better-gpt-5-chatbot-2024-3)
    [reported.](http://reported.In)
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: 'In an [interview](https://www.youtube.com/watch?v=jvqFAi7vkBc) with podcaster
    Lex Fridman, Altman said: "We will release an amazing new model this year. I don''t
    know what we''ll call it. We''ll release over in the coming months many different
    things, I think they''ll be very cool."'
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: 'He added: "I think before we talk about a GPT-5 like model called that or not
    called that or a little bit worse or little bit better than what you''d expect
    from a GPT-5, I think we have a lot of other important things to release first."'
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
- en: The company doesn't yet offer a digital voice assistant to its users, although
    it does have an API that converts speech to text called TTS, according to its
    [website](https://platform.openai.com/docs/models/tts). It also has a general-purpose
    speech recognition model called Whisper.
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
- en: OpenAI also filed trademark applications for its future models, including [GPT-6](https://tsdr.uspto.gov/#caseNumber=98233550&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch)
    and [GPT-7](https://tsdr.uspto.gov/#caseNumber=98233552&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch)
    in October.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
- en: The filing for GPT-6 includes simulating conversations, sharing datasets for
    the purpose of machine learning, predictive analytics, and "analyzing algorithms
    that are able to learn to analyze, classify, and take actions in response to exposure
    to data."
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: The GPT-7 trademark application covers software using artificial intelligence
    for music generation, conversion of text and data files into software code, and
    creating and generating software code. Both applications are still under examination.
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
- en: The Patent Office might not grant those trademarks, though, as in February,
    it [rejected](https://tsdr.uspto.gov/documentviewer?caseId=sn97733259&docId=FREF20240206125856&linkId=1#docIndex=0&page=1)
    OpenAI's attempts to trademark "GPT." The agency said it's a "widely used acronym"
    that's "merely descriptive" as it means "generative pre-trained transformers."
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
- en: 'The "voice engineer" trademark application, which is pending a review from
    an examiner, intends to cover software for the following 10 areas:'
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
- en: Building digital voice assistants
  id: totrans-split-21
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Voice and speech recognition, processing voice commands, and converting between
    text and speech
  id: totrans-split-22
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Processing voice commands, and converting between text and speech
  id: totrans-split-23
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: automatic speech and voice recognition and generation
  id: totrans-split-24
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Generating voice and audio outputs based on natural language prompts, text,
    speech, visual prompts, images, and/or video
  id: totrans-split-25
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Generation of audio and/or voice in response to user prompts
  id: totrans-split-26
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Machine learning-based natural language and speech processing
  id: totrans-split-27
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Multilingual speech recognition, translation, and transcription
  id: totrans-split-28
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Using artificial intelligence for automatic text-to-voice and text-to-audio
    conversion
  id: totrans-split-29
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Development of voice service delivery
  id: totrans-split-30
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: OpenAI didn't immediately respond to a request for comment from Business Insider.
  id: totrans-split-31
  prefs: []
  type: TYPE_NORMAL
