- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 15:01:58'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Stanford Engineering Everywhere | EE261 - The Fourier Transform and its Applications
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://see.stanford.edu/course/ee261](https://see.stanford.edu/course/ee261)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: The goals for the course are to gain a facility with using the Fourier transform,
    both specific techniques and general principles, and learning to recognize when,
    why, and how it is used. Together with a great variety, the subject also has a
    great coherence, and the hope is students come to appreciate both.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: 'Topics include: The Fourier transform as a tool for solving physical problems.
    Fourier series, the Fourier transform of continuous and discrete signals and its
    properties. The Dirac delta, distributions, and generalized transforms. Convolutions
    and correlations and applications; probability distributions, sampling theory,
    filters, and analysis of linear systems. The discrete Fourier transform and the
    FFT algorithm. Multidimensional Fourier transform and use in imaging. Further
    applications to optics, crystallography. Emphasis is on relating the theoretical
    principles to solving practical engineering and science problems.'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
