- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 15:01:58'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 15:01:58'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Stanford Engineering Everywhere | EE261 - The Fourier Transform and its Applications
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 斯坦福工程学无处不在 | EE261 - Fourier 变换及其应用
- en: 来源：[https://see.stanford.edu/course/ee261](https://see.stanford.edu/course/ee261)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://see.stanford.edu/course/ee261](https://see.stanford.edu/course/ee261)
- en: The goals for the course are to gain a facility with using the Fourier transform,
    both specific techniques and general principles, and learning to recognize when,
    why, and how it is used. Together with a great variety, the subject also has a
    great coherence, and the hope is students come to appreciate both.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 课程的目标是熟练掌握使用 Fourier 变换的技能，包括具体技术和一般原则，并学会识别何时、为什么以及如何使用它。与各种各样性相当的主题还有很大的连贯性，希望学生能够充分欣赏。
- en: 'Topics include: The Fourier transform as a tool for solving physical problems.
    Fourier series, the Fourier transform of continuous and discrete signals and its
    properties. The Dirac delta, distributions, and generalized transforms. Convolutions
    and correlations and applications; probability distributions, sampling theory,
    filters, and analysis of linear systems. The discrete Fourier transform and the
    FFT algorithm. Multidimensional Fourier transform and use in imaging. Further
    applications to optics, crystallography. Emphasis is on relating the theoretical
    principles to solving practical engineering and science problems.'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 主题包括：Fourier 变换作为解决物理问题的工具。Fourier 级数，连续和离散信号的 Fourier 变换及其性质。Dirac δ 函数，分布和广义变换。卷积和相关及其应用；概率分布，采样理论，滤波器和线性系统分析。离散
    Fourier 变换和 FFT 算法。多维 Fourier 变换及其在成像中的应用。进一步应用于光学，晶体学。重点是将理论原理与解决实际工程和科学问题联系起来。
