- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 14:49:59'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 14:49:59'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Tech Still Isn’t Doing Enough to Care for the Environment | WIRED
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Tech Still Isn’t Doing Enough to Care for the Environment | WIRED
- en: 来源：[https://www.wired.com/story/tech-environment-greenpeace-social/](https://www.wired.com/story/tech-environment-greenpeace-social/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.wired.com/story/tech-environment-greenpeace-social/](https://www.wired.com/story/tech-environment-greenpeace-social/)
- en: We are in a climate crisis, and technology can be either a part of the problem
    or a force for good, says Greenpeace CTO Priscilla Chomba-Kinywa. According to
    the International Panel on Climate Change, she explains, we have “less than seven
    years before Earth becomes really difficult to live on.” Last year alone, the
    world witnessed [wildfires in North America](https://www.wired.com/story/canada-wildfires-future/),
    floods in Southern Africa, and even the double tragedy of floods and fires in
    places like Greece, she says.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 绿色和平首席技术官普里西拉·琼巴-基尼瓦表示，我们正处于气候危机中，技术可以成为问题的一部分，也可以成为积极力量。根据气候变化国际专门委员会的数据，她解释说，地球只有“不到七年的时间变得非常难以居住”。她说，仅去年，世界就目睹了北美的[森林大火](https://www.wired.com/story/canada-wildfires-future/)、南非的洪水，以及希腊等地的洪水和火灾双重悲剧。
- en: Social media allows people from across the world to communicate, but “we’re
    seeing misinformation, disinformation, and a wanton disregard for sustainability
    by some of these platforms—and unfortunately, people don’t have many other options.”
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 社交媒体使全世界的人们可以交流，但“我们看到了一些平台的错误信息、虚假信息，以及对可持续性的肆意忽视，而不幸的是，人们并没有太多其他选择”。
- en: Chomba-Kinywa says that VCs, startups, investors, and technologists should invest
    in alternative platforms “that are green, that are ethical, that are value-based,
    and that give us an alternative to what we have right now, being built by people
    so passionate about the environment that they will not sell out in the name of
    profits.”
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: Chomba-Kinywa表示，风险投资公司、初创企业、投资者和技术人员应该投资于“绿色、道德、基于价值观的替代平台”，这样我们就有了一个替代现有平台的选择，由于这些人对环境充满激情，他们不会为了利润而出卖自己。
- en: Even though conventional investment is supposed to maximize shareholder value,
    she argues, investing in these platforms is a price worth paying, as customers
    will soon be demanding action.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: 她认为，尽管传统投资应该最大化股东价值，但投资于这些平台是一个值得付出代价的行为，因为客户很快将要求采取行动。
- en: Chomba-Kinywa salutes companies already taking action—such as [Hyundai](https://www.wired.com/tag/hyundai/),
    which recently committed to stop supplying the heavy machinery used for illegal
    mining in the Amazon. This was possible, she says, through the use of satellite
    imagery and pressure from leaders in Indigenous communities, which led to a report
    that Hyundai couldn’t ignore.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: Chomba-Kinywa赞扬那些已经采取行动的公司，比如[现代](https://www.wired.com/tag/hyundai/)，最近承诺停止向亚马逊非法采矿使用的重型机械供应。她说，通过卫星图像和土著社区领导人的压力，这一举措得以实现，这促使现代公司不能忽视这一报告。
- en: Good data, she explains, is vital—Greenpeace has been using it since 2009 to
    persuade some tech giants to switch to 100 percent [renewable energy](https://www.wired.com/tag/renewable-energy/).
    For those that refused, the campaigning NGO just walked away. Other organizations
    should do the same, she says.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 良好的数据至关重要，她解释道，自2009年以来，绿色和平一直在使用它来说服一些科技巨头转向100% [可再生能源](https://www.wired.com/tag/renewable-energy/)。对于那些拒绝的公司，这家运动组织只是选择了离开。其他组织也应该效仿，她说。
- en: “What if you could use your influence to apply pressure on these organizations
    to change?” she asks. “Say, ‘We’ve looked at the data, we’ve looked at your plans.
    You’re not doing enough, and we won’t give you our money.’ Then maybe we can make
    a little bit more of a change.”
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: “如果你能利用你的影响力向这些组织施加压力，要求它们做出改变，那会怎么样？”她问道。“说，‘我们已经查看了数据，查看了你们的计划。你们做得不够，我们不会给你们我们的钱。’也许我们可以做出更多的改变。”
- en: Finally, she says businesses need to work with communities from places like
    Senegal, Zambia, Nigeria, Bangladesh, and Mexico to understand and support their
    movements. “Sit with the elders in their communities, listen to the Indigenous
    knowledge that allowed them to coexist with nature, and start to reapply some
    of those principles,” she suggests. “They are scrambling for their lives.”
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: 最后，她说，企业需要与塞内加尔、赞比亚、尼日利亚、孟加拉国和墨西哥等地的社区合作，了解并支持他们的运动。“与他们社区中的长者坐在一起，倾听让他们与自然共存的土著知识，并开始重新应用其中的一些原则，”她建议说。“他们正在为生存而挣扎。”
- en: Chomba-Kinywa also says that conversations on AI need to focus on the planet.
    “We’re talking about values, ethics, and putting guardrails in place—but we can’t
    do that without talking about the environment,” she argues. “We need to think
    through the environmental cost of AI. It has the potential to help us solve some
    of humanity’s grand challenges, but that’s only useful if humanity has a livable
    planet.”
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
  zh: Chomba-Kinywa 还表示，关于人工智能的对话需要关注地球。“我们谈论价值观、伦理，以及设置防护栏，但如果不谈论环境，这些都无法实现，”她说道。“我们需要深思人工智能的环境成本。它有潜力帮助我们解决人类的一些重大挑战，但仅当人类拥有可居住的地球时才有用。”
- en: '*This article appears in the March/April 2024 issue of* *WIRED UK magazine.*'
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
  zh: '*这篇文章出现在* *2024年3月/4月号的* *WIRED UK杂志上*。'
