- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:49:59'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Tech Still Isn’t Doing Enough to Care for the Environment | WIRED
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.wired.com/story/tech-environment-greenpeace-social/](https://www.wired.com/story/tech-environment-greenpeace-social/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: We are in a climate crisis, and technology can be either a part of the problem
    or a force for good, says Greenpeace CTO Priscilla Chomba-Kinywa. According to
    the International Panel on Climate Change, she explains, we have “less than seven
    years before Earth becomes really difficult to live on.” Last year alone, the
    world witnessed [wildfires in North America](https://www.wired.com/story/canada-wildfires-future/),
    floods in Southern Africa, and even the double tragedy of floods and fires in
    places like Greece, she says.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: Social media allows people from across the world to communicate, but “we’re
    seeing misinformation, disinformation, and a wanton disregard for sustainability
    by some of these platforms—and unfortunately, people don’t have many other options.”
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: Chomba-Kinywa says that VCs, startups, investors, and technologists should invest
    in alternative platforms “that are green, that are ethical, that are value-based,
    and that give us an alternative to what we have right now, being built by people
    so passionate about the environment that they will not sell out in the name of
    profits.”
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: Even though conventional investment is supposed to maximize shareholder value,
    she argues, investing in these platforms is a price worth paying, as customers
    will soon be demanding action.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: Chomba-Kinywa salutes companies already taking action—such as [Hyundai](https://www.wired.com/tag/hyundai/),
    which recently committed to stop supplying the heavy machinery used for illegal
    mining in the Amazon. This was possible, she says, through the use of satellite
    imagery and pressure from leaders in Indigenous communities, which led to a report
    that Hyundai couldn’t ignore.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: Good data, she explains, is vital—Greenpeace has been using it since 2009 to
    persuade some tech giants to switch to 100 percent [renewable energy](https://www.wired.com/tag/renewable-energy/).
    For those that refused, the campaigning NGO just walked away. Other organizations
    should do the same, she says.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: “What if you could use your influence to apply pressure on these organizations
    to change?” she asks. “Say, ‘We’ve looked at the data, we’ve looked at your plans.
    You’re not doing enough, and we won’t give you our money.’ Then maybe we can make
    a little bit more of a change.”
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: Finally, she says businesses need to work with communities from places like
    Senegal, Zambia, Nigeria, Bangladesh, and Mexico to understand and support their
    movements. “Sit with the elders in their communities, listen to the Indigenous
    knowledge that allowed them to coexist with nature, and start to reapply some
    of those principles,” she suggests. “They are scrambling for their lives.”
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: Chomba-Kinywa also says that conversations on AI need to focus on the planet.
    “We’re talking about values, ethics, and putting guardrails in place—but we can’t
    do that without talking about the environment,” she argues. “We need to think
    through the environmental cost of AI. It has the potential to help us solve some
    of humanity’s grand challenges, but that’s only useful if humanity has a livable
    planet.”
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
- en: '*This article appears in the March/April 2024 issue of* *WIRED UK magazine.*'
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
