- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-27 14:34:18'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-27 14:34:18
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'The unreasonable effectiveness of i3, or: ten years of a boring desktop environment'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: i3的不合理有效性，或者说：十年来的无聊桌面环境
- en: 来源：[https://blog.waleson.com/2024/03/the-unreasonable-effectiveness-of-i3-or.html](https://blog.waleson.com/2024/03/the-unreasonable-effectiveness-of-i3-or.html)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://blog.waleson.com/2024/03/the-unreasonable-effectiveness-of-i3-or.html](https://blog.waleson.com/2024/03/the-unreasonable-effectiveness-of-i3-or.html)
- en: My wife uses Windows and over the years I've helped her move things to new systems.
    Win8, 10 and now 11\. With every change the UI changes. Now I can't right click
    the bottom right corner anymore to open Task Manager. The UI feels "fresh" and
    up-to-date I guess, but does it really matter?
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 我妻子使用Windows，多年来我帮助她将东西移到新系统上。Win8，10，现在是11。随着每次改变，界面也改变了。现在我不能右键单击右下角打开任务管理器了。界面感觉“新鲜”和最新，我猜，但真的重要吗？
- en: My desktop has looked like this since 2008\. I love the picture of the gearbox,
    it's a testament to the hidden precision engineering that goes on inside the built
    world all the time.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 自2008年以来，我的桌面就是这样。我喜欢齿轮箱的图片，这是对建筑世界内部隐藏的精密工程的证明，它们一直在运行。
- en: 'I don''t see much of the gearbox though, because most of the time my screens
    look like this:'
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 我虽然没有经常看齿轮箱，因为大部分时间我的屏幕看起来像这样：
- en: The environment around my background picture has changed a little more, but
    has been stable for the last 10 years. My experience is very different to my wife's
    constantly changing system. In 2009 I moved from Windows to Ubuntu, then to Debian
    using Gnome. Then finally to i3 in 2013 after a brief affair with XMonad in 2012\.
    So by now in early 2024, I've had the same minimal UI for more than 10 years,
    and if I'd only had the guts to adopt i3 earlier it could have been 15\. I have
    made small changes but if I didn't like it I would revert back to the previous
    version. All the changes were conscious efforts and I had the freedom to go back
    when I wanted to.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: 我的桌面背景周围的环境有些变化，但过去10年一直很稳定。我的经历与我妻子经常变化的系统非常不同。2009年，我从Windows转到Ubuntu，然后使用Gnome转到Debian。最后在2013年转到i3，在2012年短暂地尝试过XMonad。所以到了2024年初，我已经使用相同的简约UI超过10年了，如果我更早地采用i3，可能已经是15年了。我做了一些小改变，但如果我不喜欢，我会回到以前的版本。所有的变化都是有意识的努力，我有自由在想要时回到以前。
- en: This short post is in praise to boring stable systems, and a thank you to all
    the open source contributors that made my desktop environment possible.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: 这篇简短的文章是赞扬无聊但稳定的系统，并感谢所有使我的桌面环境成为可能的开源贡献者。
- en: 'OS: Debian (since 2011)'
  id: totrans-split-11
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 操作系统：Debian（自2011年起）
- en: 'Window manager: i3 (since 2013)'
  id: totrans-split-12
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 窗口管理器：i3（自2013年起）
- en: 'Browser: Chrome (since 2008)'
  id: totrans-split-13
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 浏览器：Chrome（自2008年起）
- en: 'Editor: vim (since 2011, now actually neovim but I haven''t noticed a difference
    with vim)'
  id: totrans-split-14
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 编辑器：vim（自2011年起，现在实际上是neovim，但我没有注意到与vim的区别）
- en: 'Terminal: gnome-terminal (since 2009)'
  id: totrans-split-15
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 终端：gnome-terminal（自2009年起）
- en: 'Shell: zsh / oh-my-zsh (since 2014)'
  id: totrans-split-16
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Shell：zsh / oh-my-zsh（自2014年起）
- en: 'Mail: Gmail (since 2005)'
  id: totrans-split-17
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 邮箱：Gmail（自2005年起）
- en: Here are some new improvements to my home computer systems.
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
  zh: 这里有一些我家庭电脑系统的新改进。
- en: 'Backup management: syncthing (since 2022)'
  id: totrans-split-19
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 备份管理：syncthing（自2022年起）
- en: 'Home automation and energy management: home-assistant (since 2022)'
  id: totrans-split-20
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 家庭自动化和能源管理：home-assistant（自2022年起）
- en: 'Microcontroller management: espthing (since 2024)'
  id: totrans-split-21
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: 微控制器管理：espthing（自2024年起）
- en: 'Shell history management: atuin (trying it out since early 2024)'
  id: totrans-split-22
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
  zh: Shell 历史管理：atuin（自2024年初开始尝试）
- en: Being boring with tools is great. It gives you the freedom to be revolutionary
    in areas where you actually want to make a difference.
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
  zh: 使用无聊的工具是很棒的。这给了你在你真正想要有所作为的领域里革命的自由。
