- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:34:18'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'The unreasonable effectiveness of i3, or: ten years of a boring desktop environment'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://blog.waleson.com/2024/03/the-unreasonable-effectiveness-of-i3-or.html](https://blog.waleson.com/2024/03/the-unreasonable-effectiveness-of-i3-or.html)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: My wife uses Windows and over the years I've helped her move things to new systems.
    Win8, 10 and now 11\. With every change the UI changes. Now I can't right click
    the bottom right corner anymore to open Task Manager. The UI feels "fresh" and
    up-to-date I guess, but does it really matter?
  prefs: []
  type: TYPE_NORMAL
- en: My desktop has looked like this since 2008\. I love the picture of the gearbox,
    it's a testament to the hidden precision engineering that goes on inside the built
    world all the time.
  prefs: []
  type: TYPE_NORMAL
- en: 'I don''t see much of the gearbox though, because most of the time my screens
    look like this:'
  prefs: []
  type: TYPE_NORMAL
- en: The environment around my background picture has changed a little more, but
    has been stable for the last 10 years. My experience is very different to my wife's
    constantly changing system. In 2009 I moved from Windows to Ubuntu, then to Debian
    using Gnome. Then finally to i3 in 2013 after a brief affair with XMonad in 2012\.
    So by now in early 2024, I've had the same minimal UI for more than 10 years,
    and if I'd only had the guts to adopt i3 earlier it could have been 15\. I have
    made small changes but if I didn't like it I would revert back to the previous
    version. All the changes were conscious efforts and I had the freedom to go back
    when I wanted to.
  prefs: []
  type: TYPE_NORMAL
- en: This short post is in praise to boring stable systems, and a thank you to all
    the open source contributors that made my desktop environment possible.
  prefs: []
  type: TYPE_NORMAL
- en: 'OS: Debian (since 2011)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Window manager: i3 (since 2013)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Browser: Chrome (since 2008)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Editor: vim (since 2011, now actually neovim but I haven''t noticed a difference
    with vim)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Terminal: gnome-terminal (since 2009)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Shell: zsh / oh-my-zsh (since 2014)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Mail: Gmail (since 2005)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Here are some new improvements to my home computer systems.
  prefs: []
  type: TYPE_NORMAL
- en: 'Backup management: syncthing (since 2022)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Home automation and energy management: home-assistant (since 2022)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Microcontroller management: espthing (since 2024)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: 'Shell history management: atuin (trying it out since early 2024)'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Being boring with tools is great. It gives you the freedom to be revolutionary
    in areas where you actually want to make a difference.
  prefs: []
  type: TYPE_NORMAL
