- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-29 12:40:08'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: 'The surprising effect social media de-influencers might have on the environment
    : NPR'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.npr.org/2024/03/25/1239897929/influencers-deinfluencing-tiktok-instagram-shopping-environment](https://www.npr.org/2024/03/25/1239897929/influencers-deinfluencing-tiktok-instagram-shopping-environment)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Some TikTok creators have embraced the de-influencer movement, like Diana Wiebe,
    seen in a screenshot here, who goes by the TikTok handle @depressiondotgov and
    critiques social media influencing. **NPR** ****hide caption****
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: '****toggle caption****NPR'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: In the early days of the pandemic, Diana Wiebe spent a lot of time scrolling
    through Instagram and TikTok — and she started to notice something.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: '"I got influenced mostly by skin care stuff," she recalls. "I''d watch an influencer,
    and I''d be like, ''OK, yeah. This worked for them. I trust their opinion. Add
    to cart.''"'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: After a while, Wiebe began to realize just how much money she was spending on
    stuff she saw being pushed on social media. That's when she knew things had to
    change.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: 'Social media influencers aren''t new. But over the last few years, another
    trend has emerged: *de*-influencing. What started as a backlash to advertising
    could now have a surprising and real-world impact on the environment.'
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: A rejection of influencer culture
  id: totrans-split-12
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: The world of influencing is pretty simple.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: Companies from the likes of Airbnb to Amazon to Louis Vuitton pay people with
    a lot of followers on social media to promote their products. These creators then
    make content, typically videos, where they recommend the products and services,
    often adding a discount code their followers can use to sweeten the deal.
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
- en: '"They do it kind of more in the guise of being your friend or being relatable,"
    Wiebe said.'
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
- en: It has evolved over time and can now include things like [the "come shopping
    with me" trend that](https://www.tiktok.com/@theglowjourney/video/7290381817088085279)
    emulates the feeling of casually shopping with a friend. The influencers film
    themselves walking around stores and filling their carts with clothing, makeup,
    cute little bowls for your ramen noodles and, of course, Stanley cups.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
- en: '"They film their hands, and they throw stuff kind of willy-nilly in the cart,"
    Wiebe said. "I just kept saying stuff like ... ''This is garbage. Like, why is
    this person buying this?''"'
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: 'So Wiebe began to post her own videos on TikTok. Her videos don''t influence;
    rather, they seek to de-influence. And she is one of many who have found a foothold
    in the last few years as the #deinfluencing hashtag on TikTok has racked up more
    than 1.5 billion views.'
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
- en: De-influencing encourages people to buy less stuff and instead use what they
    already have.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
- en: '"Initially I saw the trend as something that was kind of like a response to
    the fatigue of influencing, of this constant messaging of buy, buy, buy," said
    content creator Christina Mychaskiw.'
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
- en: Mychaskiw defines herself as a former shopaholic who at one point had more than
    $120,000 in student loan debt. Even before the term "de-influencing" trended on
    TikTok, she was making videos about mindful spending and consumerist culture.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
- en: Mychaskiw said that when she was younger, she watched videos that normalized
    overconsumption — [videos like shopping hauls](https://www.youtube.com/watch?v=dkAvGY5Rl3I),
    where people show off what they have bought, sometimes dozens of pieces at once.
  id: totrans-split-22
  prefs: []
  type: TYPE_NORMAL
- en: '"I think when you watch those things over and over again and you continuously
    see people being like, ''Oh, I just picked this up and I bought this,'' and the
    quantities that people bought ... it kind of gives you this license to feel like,
    ''Oh, I can do that too,''" she said.'
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
- en: '"It was sort of a refreshing take to see, ''Hey, this thing didn''t change
    my life. This thing didn''t work the way it was supposed to. It didn''t live up
    to the hype. Save your money.''"'
  id: totrans-split-24
  prefs: []
  type: TYPE_NORMAL
- en: The feeling of de-influencing is refreshing for many. NPR asked readers about
    their relationship with social media and heard from dozens of people who relayed
    being fed up with constant advertising on social media, feeling buyer's remorse
    after following an influencer's recommendation or feeling forced to become influencers
    themselves.
  id: totrans-split-25
  prefs: []
  type: TYPE_NORMAL
- en: Heidi Kaluza falls into that last camp, as an influencer who now supports de-influencing.
  id: totrans-split-26
  prefs: []
  type: TYPE_NORMAL
- en: When she first came onto the scene, Kaluza remembers how some clothing brands
    would send her up to 20 items a month in various sizes. On top of that, she said
    her reviews didn't always feel genuine.
  id: totrans-split-27
  prefs: []
  type: TYPE_NORMAL
- en: '"They''re kind of forcing me to engage in wearing these clothes and promoting
    them and only saying good things about them and never critiquing," she said.'
  id: totrans-split-28
  prefs: []
  type: TYPE_NORMAL
- en: '"I see [de-influencing] as a growing movement. I think it''s going to be a
    foundational aspect of our society."'
  id: totrans-split-29
  prefs: []
  type: TYPE_NORMAL
- en: That's not to say the movement has been entirely pure.
  id: totrans-split-30
  prefs: []
  type: TYPE_NORMAL
- en: '"People saw it as just another trend for them to hop on and figure out how
    they can capitalize on it and use consumerism to capitalize on de-influencing,"
    said lifestyle content creator Mikayla Farwig.'
  id: totrans-split-31
  prefs: []
  type: TYPE_NORMAL
- en: '"They were like, ''Hey, I''m going to de-influence you from this lip gloss
    because this lip gloss is $42\. How about you buy this $10 lip gloss instead?'''
  id: totrans-split-32
  prefs: []
  type: TYPE_NORMAL
- en: '"It was still promoting this overconsumption."'
  id: totrans-split-33
  prefs: []
  type: TYPE_NORMAL
- en: And a focus on overconsumption is where the de-influencing movement is heading
    now. It has evolved from a response to mass advertising to a more nuanced discussion
    around overconsumption. And its adherents say de-influencing could have a positive
    effect on the environment.
  id: totrans-split-34
  prefs: []
  type: TYPE_NORMAL
- en: De-influencing's relationship with the environment
  id: totrans-split-35
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: With an online platform, today's de-influencers are spreading a deeper message
    to their followers about how to live sustainably in a way that helps the planet.
  id: totrans-split-36
  prefs: []
  type: TYPE_NORMAL
- en: They point to the plastic packaging encasing products hawked online, a small
    amount of which actually gets recycled; the shipping; and the fact that a lot
    of these products end up in landfills or being burned, which contributes to global
    greenhouse gas emissions.
  id: totrans-split-37
  prefs: []
  type: TYPE_NORMAL
- en: The stakes are high when it comes to the rapid consumption of goods and services,
    which can make people feel powerless, said Aja Barber, but she adds that talking
    about the issue is the first step for consumers.
  id: totrans-split-38
  prefs: []
  type: TYPE_NORMAL
- en: '"If you can get people to start thinking about the things that they buy, they
    start thinking about a lot of the bigger topics as well," she said.'
  id: totrans-split-39
  prefs: []
  type: TYPE_NORMAL
- en: 'Barber is author of the book *Consumed: The Need for Collective Change*. She''s
    kind of the original de-influencer, having spent years speaking to issues of sustainability
    in the context of fast fashion.'
  id: totrans-split-40
  prefs: []
  type: TYPE_NORMAL
- en: '"The conversation about fast fashion and consumer goods, I find it''s like
    a gateway," she said. "People are like, ''Oh, it''s just a frivolous dress,''
    and then they start to learn a little bit more about what''s behind it ... and
    it just keeps going. Before you know it, you''re like me and you have a compost
    and you won''t shut up about it."'
  id: totrans-split-41
  prefs: []
  type: TYPE_NORMAL
- en: This is the point where the de-influencing movement comes full circle and back
    to influencing — only, with a twist.
  id: totrans-split-42
  prefs: []
  type: TYPE_NORMAL
- en: '"This isn''t just about de-influencing. This is about using your influence
    in the right way," said Solitaire Townsend, a sustainability expert and co-founder
    of the change agency Futerra.'
  id: totrans-split-43
  prefs: []
  type: TYPE_NORMAL
- en: She has spent years working with communities, brands and even content creators
    to communicate environmental issues to wider audiences.
  id: totrans-split-44
  prefs: []
  type: TYPE_NORMAL
- en: Townsend said that the de-influencing trend describes something that has been
    discussed for years — living more sustainably — and that the people with a lot
    of social media followers have an "enormous outside ability to help us live more
    sustainably."
  id: totrans-split-45
  prefs: []
  type: TYPE_NORMAL
- en: '"We''ve known for decades that the number one influence on your behaviors is
    your friends and family. More than advertising, more than anything governments
    tell you to do, more than anything that educators tell you to do," she said.'
  id: totrans-split-46
  prefs: []
  type: TYPE_NORMAL
- en: '"It turns out we have a close relationship with creators. We hold them in that
    same friends-and-family bubble."'
  id: totrans-split-47
  prefs: []
  type: TYPE_NORMAL
- en: Townsend's company worked with Unilever on research that looks at the role of
    influencer content in impacting sustainable choices. The findings, [released in
    2023](https://www.unilever.com/news/press-and-media/press-releases/2023/unilever-reveals-influencers-can-switch-people-on-to-sustainable-living/),
    showed that 83% of respondents think TikTok and Instagram are good places to get
    advice about how to live sustainably and that 75% are more likely to change their
    behavior in a direction that is good for the environment after watching social
    media content.
  id: totrans-split-48
  prefs: []
  type: TYPE_NORMAL
- en: '"Most of us who are following [influencers] really want them to help us with
    this. We want them to model these behaviors," she said.'
  id: totrans-split-49
  prefs: []
  type: TYPE_NORMAL
