- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:39:28'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'The built environment and the determination of fault in urban pedestrian crashes:
    Toward a systems-oriented crash investigation | Journal of Transport and Land
    Use'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.jtlu.org/index.php/jtlu/article/view/2335](https://www.jtlu.org/index.php/jtlu/article/view/2335)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'The built environment and the determination of fault in urban pedestrian crashes:
    Toward a systems-oriented crash investigation'
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Jonathan Stiles
  prefs: []
  type: TYPE_NORMAL
- en: The Ohio State University
  prefs: []
  type: TYPE_NORMAL
- en: '[https://orcid.org/0000-0001-7613-1814](https://orcid.org/0000-0001-7613-1814)'
  prefs: []
  type: TYPE_NORMAL
- en: Harvey Miller
  prefs: []
  type: TYPE_NORMAL
- en: The Ohio State University
  prefs: []
  type: TYPE_NORMAL
- en: '[https://orcid.org/0000-0001-5480-3421](https://orcid.org/0000-0001-5480-3421)'
  prefs: []
  type: TYPE_NORMAL
- en: 'DOI: [https://doi.org/10.5198/jtlu.2024.2335](https://doi.org/10.5198/jtlu.2024.2335)'
  prefs: []
  type: TYPE_NORMAL
- en: 'Keywords: Pedestrian, Traffic Crashes, Safe Systems, Vision Zero, Transportation
    Equity'
  prefs: []
  type: TYPE_NORMAL
- en: '* * *'
  prefs: []
  type: TYPE_NORMAL
- en: Abstract
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: This study identifies built environmental factors that influence the determination
    of fault in urban pedestrian crashes in the United States, with implications for
    both safety and equity. Using data from Columbus, Ohio, we apply regression modeling,
    spatial analysis, and case studies, and find pedestrians are more likely to be
    found at fault on fast, high-volume arterial roads with bus stops. We also observe
    that better provision of crossings leads to more marked intersection crashes,
    which are less likely to be blamed on pedestrians. In addition, large differences
    in both the provision of crossings and fault exist between neighborhoods. We interpret
    findings through the lenses of the systems-oriented safety approaches Safe Systems
    and Vision Zero. The conclusion argues that the designation of individual responsibility
    for crashes preempts collective responsibility, preventing wider adoption of design
    interventions as well as systemic changes to the processes that determine the
    built environment of US roadways.
  prefs: []
  type: TYPE_NORMAL
- en: '* * *'
  prefs: []
  type: TYPE_NORMAL
- en: References
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: 'Al-Mahameed, F. J., Qin, X., Schneider, R. J., & Shaon, M. R. R. (2019). Analyzing
    pedestrian and bicyclist crashes at the corridor level: Structural equation modeling
    approach. Transportation Research Record, 2673(7), 308–318\.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Arrington, G. B., R. Cervero, National Research Council, Transportation Research
    Board, Abay, K. A. (2015). Investigating the nature and impact of reporting bias
    in road crash data. Transportation Research Part A: Policy and Practice, 71, 31–45\.'
  prefs: []
  type: TYPE_NORMAL
- en: Belin, M. Å., Tillgren, P., & Vedung, E. (2012). Vision Zero—A road safety policy
    innovation. International Journal of Injury Control and Safety Promotion, 19(2),
    171–179\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Bernhoft, I. M., & Carstensen, G. (2008). Preferences and behavior of pedestrians
    and cyclists by age and gender. Transportation Research Part F: Traffic Psychology
    and Behavior, 11(2), 83–95\.'
  prefs: []
  type: TYPE_NORMAL
- en: City of Columbus. (2018). Columbus communities. Retrieved from [https://opendata.columbus.gov/datasets/columbus-communities/](https://opendata.columbus.gov/datasets/columbus-communities/)
  prefs: []
  type: TYPE_NORMAL
- en: 'Clifton, K. J., Burnier, C. V., & Akar, G. (2009). Severity of injury resulting
    from pedestrian–vehicle crashes: What can we learn from examining the built environment?
    Transportation Research Part D: Transport and Environment, 14(6), 425–436\.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Corben, B. (2020). Integrating safe system with movement and place for vulnerable
    road users (No. AP-R611-20). Sydney, Australia: Austroads.'
  prefs: []
  type: TYPE_NORMAL
- en: Cottrill, C. D., & Thakuriah, P. V. (2010). Evaluating pedestrian crashes in
    areas with high low-income or minority populations. Accident Analysis & Prevention,
    42(6), 1718–1728\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Doecke, S. D., Kloeden, C. N., Dutschke, J. K., & Baldock, M. R. (2018). Safe
    speed limits for a safe system: The relationship between speed limit and fatal
    crash rate for different crash types. Traffic Injury Prevention, 19(4), 404–408\.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Dumbaugh, E., & Rae, R. (2009). Safe urban form: Revisiting the relationship
    between community design and traffic safety. Journal of the American Planning
    Association, 75(3), 309–329\.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Dumbaugh, E., Saha, D., & Merlin, L. (2020). Toward safe systems: Traffic safety,
    cognition, and the built environment. Journal of Planning Education and Research,
    0739456X20931915\.'
  prefs: []
  type: TYPE_NORMAL
- en: Dumbaugh, E., & Zhang, Y. (2013). The relationship between community design
    and crashes involving older drivers and pedestrians. Journal of Planning Education
    and Research, 33(1), 83–95\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Ewing, R., & Dumbaugh, E. (2009). The built environment and traffic safety:
    A review of empirical evidence. Journal of Planning Literature, 23(4), 347–367\.'
  prefs: []
  type: TYPE_NORMAL
- en: Fahlquist, J. N. (2006). Responsibility ascriptions and vision zero. Accident
    Analysis & Prevention, 38(6), 1113–1118\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Faria, J. J., Krause, S., & Krause, J. (2010). Collective behavior in road
    crossing pedestrians: The role of social information. Behavioral Ecology, 21(6),
    1236–1242\.'
  prefs: []
  type: TYPE_NORMAL
- en: Furbee, J., & Overking, D. (2018). Police legal advisor’s update—Summer in the
    city. Columbus, OHL Columbus City Attorney.
  prefs: []
  type: TYPE_NORMAL
- en: 'Gayah, V. V., Guler, S. I., Liu, H., Blackburn, L., & Hamilton, I. (2022).
    Quantification of systemic risk factors for pedestrian safety on North Carolina.
    Raleigh, NC: NCDOT.'
  prefs: []
  type: TYPE_NORMAL
- en: Goddard, T., Ralph, K., Thigpen, C. G., & Iacobucci, E. (2019). Does news coverage
    of traffic crashes affect perceived blame and preferred solutions? Evidence from
    an experiment. Transportation Research Interdisciplinary Perspectives, 3, 100073\.
  prefs: []
  type: TYPE_NORMAL
- en: Gooch, J., Hamilton, I., Polin, B., Tanzen, R., & Cohen, T. (2022). Systemic
    safety analysis of midblock pedestrian crashes in Massachusetts. Transportation
    Research Record, 2676(11), 722–730\.
  prefs: []
  type: TYPE_NORMAL
- en: Hauer, E. (2016). An exemplum and its road safety morals. Accident Analysis
    & Prevention, 94, 168–179\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Havard, C., & Willis, A. (2012). Effects of installing a marked crosswalk on
    road crossing behavior and perceptions of the environment. Transportation Research
    Part F: Traffic Psychology and Behavior, 15(3), 249–260\.'
  prefs: []
  type: TYPE_NORMAL
- en: Johansson, R. (2009). Vision Zero–Implementing a policy for traffic safety.
    Safety Science, 47(6), 826–831\.
  prefs: []
  type: TYPE_NORMAL
- en: Kim, K., Brunner, I. M., & Yamashita, E. (2008). Modeling fault among accident—Involved
    pedestrians and motorists in Hawaii. Accident Analysis & Prevention, 40(6), 2043–2049\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Kim, K., Li, L., Richardson, J., & Nitz, L. (1998). Drivers at fault: Influences
    of age, sex, and vehicle type. Journal of Safety Research, 29(3), 171–179\.'
  prefs: []
  type: TYPE_NORMAL
- en: Kumfer, W., LaJeunesse, S., Sandt, L., & Thomas, L. (2019). Speed, kinetic energy,
    and the Safe Systems approach to safer roadways. ITE Journal. 89(4).
  prefs: []
  type: TYPE_NORMAL
- en: 'Lee, D. J. (2014). The unbearable weight of irresponsibility and the lightness
    of tumbleweeds. In S. Zavestoski & J. Agyeman (Eds.), Incomplete streets: Processes,
    practices, and possibilities (pp. 77–93). London: Routledge.'
  prefs: []
  type: TYPE_NORMAL
- en: Leveson, N. (2004). A new accident model for engineering safer systems. Safety
    science, 42(4), 237–270\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Loukaitou-Sideris, A., Liggett, R., & Sung, H. G. (2007). Death on the crosswalk:
    A study of pedestrian-automobile collisions in Los Angeles. Journal of Planning
    Education and Research, 26(3), 338–351\.'
  prefs: []
  type: TYPE_NORMAL
- en: McFadden, D. (1974). The measurement of urban travel demand. Journal of Public
    Economics, 3(4), 303–328\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Merlin, L. A., Guerra, E., & Dumbaugh, E. (2020). Crash risk, crash exposure,
    and the built environment: A conceptual review. Accident Analysis & Prevention,
    134, 105244\.'
  prefs: []
  type: TYPE_NORMAL
- en: Medury, A., Grembek, O., Loukaitou-Sideris, A., & Shafizadeh, K. (2019). Investigating
    the underreporting of pedestrian and bicycle crashes in and around university
    campuses—A crowdsourcing approach. Accident Analysis & Prevention, 130, 99–107\.
  prefs: []
  type: TYPE_NORMAL
- en: Motor vehicles-aeronautics-watercraft, Section 4511.46, Right-of-way pedestrian
    within crosswalk. (2018). Retrieved from [https://codes.ohio.gov/ohio-revised-code/section-4511.46#:~:text=(A)%20When%20traffic%20control%20signals,the%20Revised%20Code%2C%20to%20a](https://codes.ohio.gov/ohio-revised-code/section-4511.46#:~:text=(A)%20When%20traffic%20control%20signals,the%20Revised%20Code%2C%20to%20a)
  prefs: []
  type: TYPE_NORMAL
- en: 'Naumann, R. B., Heiny, S., Evenson, K. R., LaJeunesse, S., Cooper, J. F., Doggett,
    S., & Marshall, S. W. (2019). Organizational networks in road safety: Case studies
    of US Vision Zero cities. Traffic Injury Prevention, 20(4), 378–385\.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Naumann, R. B., Sandt, L., Kumfer, W., LaJeunesse, S., Heiny, S., & Lich, K.
    H. (2020). Systems thinking in the context of road safety: Can systems tools help
    us realize a true “Safe Systems” approach? Current Epidemiology Reports, 7, 343–351\.'
  prefs: []
  type: TYPE_NORMAL
- en: Noland, R. B., Klein, N. J., & Tulach, N. K. (2013). Do lower income areas have
    more pedestrian casualties? Accident Analysis & Prevention, 59, 337–345\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Norton, P. D. (2011). Fighting traffic: The dawn of the motor age in the American
    city. Cambridge, MA; MIT Press.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Ohio Department of Public Safety. (n.d.). Ohio crash report procedure manual.
    Columbus, OH: Ohio Department of Public Safety.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Ohio Traffic Safety Office. (n.d.). OH-1 Resources for law enforcement. Columbus,
    OH: Ohio Department of Public Safety, Ohio Traffic Safety Office.'
  prefs: []
  type: TYPE_NORMAL
- en: Ralph, K., Iacobucci, E., Thigpen, C. G., & Goddard, T. (2019). Editorial patterns
    in bicyclist and pedestrian crash reporting. Transportation Research Record, 2673(2),
    663–671\.
  prefs: []
  type: TYPE_NORMAL
- en: Rosen, E., Stigson, H., & Sander, U. (2011). Literature review of pedestrian
    fatality risk as a function of car impact speed. Accident Analysis & Prevention,
    43(1), 25–33\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Sanders, R. L., Judelman, B., & Schooley, S. (2019). Pedestrian safety relative
    to traffic speed management. A synthesis of highway practice. Washington, DC:
    Transportation Research Board.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Sciortino, S., Vassar, M., Radetsky, M., & Knudson, M. M. (2005). San Francisco
    pedestrian injury surveillance: Mapping, under-reporting, and injury severity
    in police and hospital records. Accident Analysis & Prevention, 37(6), 1102–1113\.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Singh, S. (2015). Critical reasons for crashes investigated in the national
    motor vehicle crash causation survey (No. DOT HS 812 115). Washington, DC: National
    Highway Traffic Safety Administration.'
  prefs: []
  type: TYPE_NORMAL
- en: Schneider, R. J., Proulx, F. R., Sanders, R. L., & Moayyed, H. (2021). United
    States fatal pedestrian crash hot spot locations and characteristics. Journal
    of Transport and Land Use, 14(1), 1–23\.
  prefs: []
  type: TYPE_NORMAL
- en: Spainhour, L. K., & Wootton, I. A. (2007). Modeling fault in fatal pedestrian
    crashes by using various data sources. Transportation Research Record, 2002(1),
    64–71\.
  prefs: []
  type: TYPE_NORMAL
- en: Tao, W., Mehndiratta, S., & Deakin, E. (2010). Compulsory convenience? How large
    arterials and land use affect midblock crossing in Fushun, China. Journal of Transport
    and Land Use, 3(3), 61–82\.
  prefs: []
  type: TYPE_NORMAL
- en: Tefft, B. C. (2013). Impact speed and a pedestrian's risk of severe injury or
    death. Accident Analysis & Prevention, 50, 871–878\.
  prefs: []
  type: TYPE_NORMAL
- en: 'Thomas, L., Sandt, L., Zegeer, C., Kumfer, W., Lang, K., Lan, B., … & Schneider,
    R.J. (2018). Systemic pedestrian safety analysis (No. Project 17-73). Washington,
    DC: Transportation Research Board.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Tingvall, C., & Haworth, N. (1999). Vision Zero—An ethical approach to safety
    and mobility. Paper presented to the 6th ITE International Conference Road Safety
    & Traffic Enforcement: Beyond 2000, Melbourne, September 6–7\.'
  prefs: []
  type: TYPE_NORMAL
- en: Ukkusuri, S., Miranda-Moreno, L. F., Ramadurai, G., & Isa-Tavarez, J. (2012).
    The role of built environment on pedestrian crash frequency. Safety Science, 50(4),
    1141–1151\.
  prefs: []
  type: TYPE_NORMAL
- en: Ulfarsson, G. F., Kim, S., & Booth, K. M. (2010). Analyzing fault in pedestrian–motor
    vehicle crashes in North Carolina. Accident Analysis & Prevention, 42(6), 1805–1813\.
  prefs: []
  type: TYPE_NORMAL
- en: USDOT. (2022). U.S. Transportation Secretary Pete Buttigieg announces comprehensive
    national roadway safety strategy. Retrieved from [https://www.transportation.gov/briefing-room/us-transportation-secretary-pete-buttigieg-announces-comprehensive-national-roadway](https://www.transportation.gov/briefing-room/us-transportation-secretary-pete-buttigieg-announces-comprehensive-national-roadway)
  prefs: []
  type: TYPE_NORMAL
- en: Weinstein Agrawal, A., Schlossberg, M., & Irvin, K. (2008). How far, by which
    route and why? A spatial analysis of pedestrian preference. Journal of Urban Design,
    13(1), 81–98\.
  prefs: []
  type: TYPE_NORMAL
- en: Vision Zero Columbus. (2021a). Vision Zero Columbus crash data. Retrieved from
    [https://columbus.maps.arcgis.com/apps/MapSeries/index.html?appid=0ff6f8f1fa134b848959ba4fc3c35bbb](https://columbus.maps.arcgis.com/apps/MapSeries/index.html?appid=0ff6f8f1fa134b848959ba4fc3c35bbb)
  prefs: []
  type: TYPE_NORMAL
- en: Vision Zero Columbus. (2021b). Action plan 1.0\. Retrieved from [https://www.columbus.gov/vzactionplan](https://www.columbus.gov/vzactionplan)
  prefs: []
  type: TYPE_NORMAL
- en: Yannis, G., Golias, J., & Papadimitriou, E. (2007). Modeling crossing behavior
    and accident risk of pedestrians. Journal of Transportation Engineering, 133(11),
    634–644\.
  prefs: []
  type: TYPE_NORMAL
- en: Yu, C. Y., & Xu, M. (2018). Local variations in the impacts of built environments
    on traffic safety. Journal of Planning Education and Research, 38(3), 314–328\.
  prefs: []
  type: TYPE_NORMAL
