- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 13:08:57'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Fast, Declarative, Reproducible, and Composable Developer Environments - devenv
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://devenv.sh/](https://devenv.sh/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Pre-configured processes
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: Services define processes that are started when the service is enabled as part
    of `devenv up`.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: Configuration
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: Each service provides a number of options how to configure it and a hook to
    pass extra configuration, whatever the format.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: Extendable
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: Define your development processes as a service, allowing reuse and simplicity
    of a few lines of configuration.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
