- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 13:08:57'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Fast, Declarative, Reproducible, and Composable Developer Environments - devenv
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://devenv.sh/](https://devenv.sh/)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Pre-configured processes
  prefs: []
  type: TYPE_NORMAL
- en: Services define processes that are started when the service is enabled as part
    of `devenv up`.
  prefs: []
  type: TYPE_NORMAL
- en: Configuration
  prefs: []
  type: TYPE_NORMAL
- en: Each service provides a number of options how to configure it and a hook to
    pass extra configuration, whatever the format.
  prefs: []
  type: TYPE_NORMAL
- en: Extendable
  prefs: []
  type: TYPE_NORMAL
- en: Define your development processes as a service, allowing reuse and simplicity
    of a few lines of configuration.
  prefs: []
  type: TYPE_NORMAL
