- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 13:27:05'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'GitHub - hashicorp/hcl: HCL is the HashiCorp configuration language.'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://github.com/hashicorp/hcl](https://github.com/hashicorp/hcl)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
  prefs: []
  type: TYPE_NORMAL
- en: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># hashicorp/hcl
  prefs: []
  type: TYPE_NORMAL
- en: This commit does not belong to any branch on this repository, and may belong
    to a fork outside of the repository.
  prefs: []
  type: TYPE_NORMAL
- en: <include-fragment src="/hashicorp/hcl/spoofed_commit_check/212a40e528766634a1aa6dd1e820d7936762196e"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
  prefs: []
  type: TYPE_NORMAL
- en: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
  prefs: []
  type: TYPE_NORMAL
- en: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
  prefs: []
  type: TYPE_NORMAL
