- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 13:41:01'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'GitHub - cezaraugusto/extension.js: 🧩 Plug-and-play, zero-config, cross-browser
    extension development tool.'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://github.com/cezaraugusto/extension.js](https://github.com/cezaraugusto/extension.js)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
  prefs: []
  type: TYPE_NORMAL
- en: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># cezaraugusto/extension.js
  prefs: []
  type: TYPE_NORMAL
- en: This commit does not belong to any branch on this repository, and may belong
    to a fork outside of the repository.
  prefs: []
  type: TYPE_NORMAL
- en: <include-fragment src="/cezaraugusto/extension.js/spoofed_commit_check/0d488a084fd3ae166ac23e8588aca6390dc522f5"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
  prefs: []
  type: TYPE_NORMAL
- en: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
  prefs: []
  type: TYPE_NORMAL
- en: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
  prefs: []
  type: TYPE_NORMAL
