- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 13:31:28'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'GitHub - turingmotors/swan: This project aims to enable language model inference
    on FPGAs, supporting AI applications in edge devices and environments with limited
    resources.'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://github.com/turingmotors/swan](https://github.com/turingmotors/swan)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
  prefs: []
  type: TYPE_NORMAL
- en: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># turingmotors/swan
  prefs: []
  type: TYPE_NORMAL
- en: This commit does not belong to any branch on this repository, and may belong
    to a fork outside of the repository.
  prefs: []
  type: TYPE_NORMAL
- en: <include-fragment src="/turingmotors/swan/spoofed_commit_check/f9618b255fda466761ee1dd42d4cef3a57b8b05c"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
  prefs: []
  type: TYPE_NORMAL
- en: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
  prefs: []
  type: TYPE_NORMAL
- en: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
  prefs: []
  type: TYPE_NORMAL
