- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-27 13:09:58'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-27 13:09:58
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Government awards $45B to company treating over 50M gallons of leaking radioactive
    waste: ''One of our nation''s most important environmental challenges'''
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 政府向处理超过 5000 万加仑泄漏放射性废物的公司授予 450 亿美元奖项：“我们国家最重要的环境挑战之一”。
- en: 来源：[https://www.thecooldown.com/green-business/hanford-nuclear-site-contract-waste/](https://www.thecooldown.com/green-business/hanford-nuclear-site-contract-waste/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.thecooldown.com/green-business/hanford-nuclear-site-contract-waste/](https://www.thecooldown.com/green-business/hanford-nuclear-site-contract-waste/)
- en: 'Photo Credit: Getty Images'
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 照片来源：Getty Images
- en: A 10-year contract has been re-awarded to a Virginia company tasked with cleaning
    up millions of gallons of radioactive and chemical waste.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 弗吉尼亚州的一家公司获得了重新授予的 10 年合同，负责清理数百万加仑放射性和化学废物。
- en: The Tri-City Herald [reported](https://www.tri-cityherald.com/news/local/hanford/article286056551.html)
    Hanford Tank Waste Operations and Closure, or H2C, has been granted $45 billion
    by the U.S. Department of Energy to perform the work at the [Hanford Site](https://www.hanford.gov/).
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: '[三城先驱报](https://www.tri-cityherald.com/news/local/hanford/article286056551.html)
    报道，美国能源部授予汉福德储罐废物处理和闭环（H2C）项目 450 亿美元，用于在[汉福德基地](https://www.hanford.gov/)进行工作。'
- en: The 580-square-mile site, located in the state of Washington, produced almost
    two-thirds of the plutonium for the country's nuclear weapons program from World
    War II through the Cold War.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: 这个面积为 580 平方英里的场地位于华盛顿州，从二战到冷战期间为国家核武器项目生产了几乎三分之二的钚。
- en: This resulted in 56 million gallons of radioactive and hazardous waste being
    stored underground in tanks, raising fears of future contamination.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: 这导致了 5600 万加仑放射性和危险废物被储存在地下罐中，引发了未来污染的担忧。
- en: As detailed on Hanford's [official website](https://www.hanford.gov/page.cfm/HanfordTankB-109Overview),
    millions of gallons of the hazardous liquids had already seeped into the soil
    during the nuclear program, resulting in groundwater treatment systems eventually
    being installed to mitigate the issue.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 正如汉福德的[官方网站](https://www.hanford.gov/page.cfm/HanfordTankB-109Overview)详细说明的那样，数百万加仑的危险液体在核项目期间已经渗入土壤，最终安装了地下水处理系统来缓解这一问题。
- en: In [August 2022](https://www.hanford.gov/page.cfm/HanfordTankB-109Overview),
    the DOE and Washington State Department of Ecology also signed an Agreed Order
    with their eyes on responding to existing leaks and preventing further contamination.
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: '[2022 年 8 月](https://www.hanford.gov/page.cfm/HanfordTankB-109Overview)，美国能源部和华盛顿州生态环境部也签署了一项协议，旨在应对现有泄漏问题并预防进一步污染。'
- en: Good news, green hacks, and the latest cool clean tech — straight to your inbox
    every week!
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: 每周直接发送至您的收件箱，有好消息、绿色技巧和最新的环保技术！
- en: H2C was first awarded the Hanford Integrated Tank Disposition Contract in April
    2023, but Hanford Tank Disposition Alliance (HTDA) appealed the decision in hopes
    of securing the funds before losing its bid. H2C is now tasked with single-shell
    tank retrieval and closure and the design, construction, and operation of waste
    facilities, according to [the DOE](https://www.energy.gov/em/articles/doe-awards-integrated-tank-disposition-contract-hanford-site-0).
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
  zh: H2C 首次获得汉福德综合储罐处理合同是在 2023 年 4 月，但汉福德储罐处理联盟（HTDA）对此决定提出上诉，希望在失去竞标之前获得资金。现在，H2C
    的任务是单壳储罐的回收和封闭，以及根据[能源部](https://www.energy.gov/em/articles/doe-awards-integrated-tank-disposition-contract-hanford-site-0)的规划设计、建造和运营废物设施。
- en: Environmental health and safety are paramount to those aims, and security and
    emergency services are also part of the H2C's responsibilities. [Water contamination](https://guide.thecooldown.com/step/install-hydropanels/r/recMNv48ZH02XiHsf),
    whether through [plastic pollution](https://guide.thecooldown.com/step/explore-plastic-free-alternatives-for-everyday-products/r/recyyL53BQALKavvy)
    or [hazardous waste](https://www.thecooldown.com/green-business/southern-water-sewage-fine-raw-sewage-contamination-stream/),
    is known to have a wide range of harmful impacts on [local ecosystems](https://www.thecooldown.com/green-business/cape-fear-river-pollution-united-nations-human-rights/)
    and [human health](https://www.thecooldown.com/outdoors/plastic-pollution-microplastics-health-problem-ocean/).
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
  zh: 环境健康与安全对这些目标至关重要，而安全和紧急服务也是 H2C 负责的一部分。[水污染](https://guide.thecooldown.com/step/install-hydropanels/r/recMNv48ZH02XiHsf)，无论是通过[塑料污染](https://guide.thecooldown.com/step/explore-plastic-free-alternatives-for-everyday-products/r/recyyL53BQALKavvy)还是[危险废物](https://www.thecooldown.com/green-business/southern-water-sewage-fine-raw-sewage-contamination-stream/)，已知对[当地生态系统](https://www.thecooldown.com/green-business/cape-fear-river-pollution-united-nations-human-rights/)和[人类健康](https://www.thecooldown.com/outdoors/plastic-pollution-microplastics-health-problem-ocean/)产生广泛的有害影响。
- en: The Hanford site partially feeds into the Columbia River, whose basin goes through
    [seven U.S. states](https://www.americanrivers.org/river/columbia-river/), providing
    irrigation for crops, drinking water for multiple communities, and serving as
    home to millions of salmon — [a vital food source](https://www.thecooldown.com/outdoors/salmon-spawning-rivers-conditions-drought/)
    that is also being negatively impacted by changing global temperatures driven
    by [human-made pollution](https://www.thecooldown.com/green-tech/methane-overheating-the-planet/).
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
  zh: 汉福德（Hanford）地点部分地进入哥伦比亚河，其流域穿过[七个美国州](https://www.americanrivers.org/river/columbia-river/)，为多个社区提供灌溉水和饮用水，并为数百万条鲑鱼提供栖息地
    — [重要食物来源](https://www.thecooldown.com/outdoors/salmon-spawning-rivers-conditions-drought/)，同时也受到全球温度变化驱动的[人为污染](https://www.thecooldown.com/green-tech/methane-overheating-the-planet/)的负面影响。
- en: According to Washington's [Department of Ecology](https://ecology.wa.gov/waste-toxics/nuclear-waste/hanford-cleanup),
    significant progress has been made in cleaning up the Hanford Site, but roughly
    "60 square miles of groundwater remains contaminated above federal standards."
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
  zh: 根据华盛顿州[生态部门](https://ecology.wa.gov/waste-toxics/nuclear-waste/hanford-cleanup)，在清理汉福德地点方面取得了显著进展，但大约“60
    平方英里的地下水仍然超过联邦标准的污染物”。
- en: As part of its contract, H2C will turn much of the remaining hazardous waste
    into glass for "permanent disposal," as reported by the Tri-City Herald for [The
    Daily News](https://tdn.com/news/state-and-regional/10-year-45-billion-contract-awarded-for-hanford-nuclear-waste-cleanup-in-eastern-wa/article_eac5bed6-d7fb-11ee-8ad1-77e80039858f.html).
    The Herald [added](https://www.tri-cityherald.com/news/local/hanford/article286056551.html)
    that a 120-day transition period is in place as H2C takes over from Washington
    River Protection Solutions, which had been leading cleanup efforts on short-term
    contracts since 2008.
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
  zh: 根据《三城先驱报》的报道，作为其合同的一部分，H2C 将把剩余的大部分危险废物转化为玻璃进行“永久处置”。[每日新闻](https://tdn.com/news/state-and-regional/10-year-45-billion-contract-awarded-for-hanford-nuclear-waste-cleanup-in-eastern-wa/article_eac5bed6-d7fb-11ee-8ad1-77e80039858f.html)报道称，随着
    H2C 接管自 2008 年以来一直领导短期合同的华盛顿河保护解决方案，现已开始为期 120 天的过渡期。
- en: '"Amentum and our partners have a tremendous track record of treating waste
    and managing nuclear operations around the DOE complex," Amentum National Security
    Group president Mark Whitney [told](https://www.tri-cityherald.com/news/local/hanford/article286056551.html)
    the outlet. "We will bring the most advanced technologies and experienced team
    to help solve one of our nation''s most important environmental challenges."'
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
  zh: '"Amentum 和我们的合作伙伴在处理废物和管理 DOE 复合体核运营方面拥有卓越的业绩记录，" Amentum 国家安全集团总裁马克·惠特尼告诉该媒体。"我们将带来最先进的技术和经验丰富的团队，以帮助解决我国最重要的环境挑战之一。"'
- en: Some might be eager for H2C to spearhead the cleanup, but it appears things
    are tied up in court for the time being. At the end of March, HTDA [filed](https://washingtontechnology.com/media/general/2024/4/hanford_tank_disposition_alliance_redacted_complaint_20240326.pdf)
    a second appeal with the aim of securing the 10-year contract, per [Washington
    Technology](https://washingtontechnology.com/contracts/2024/04/court-fight-over-45b-hanford-tank-contract-resumes/395404/).
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
  zh: 有些人可能急于让H2C领导清理工作，但目前看来事情在法院里还在打官司。三月底，HTDA在[华盛顿技术](https://washingtontechnology.com/contracts/2024/04/court-fight-over-45b-hanford-tank-contract-resumes/395404/)上[提交了](https://washingtontechnology.com/media/general/2024/4/hanford_tank_disposition_alliance_redacted_complaint_20240326.pdf)第二次上诉，旨在获得为期十年的合同。
- en: Join our [free newsletter](https://www.thecooldown.com/future-newsletter/?recIkJRW0nJxqbcxd)
    for **cool news** and **actionable info** that makes it easy to **help yourself**
    while helping the planet.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
  zh: 加入我们的[免费新闻通讯](https://www.thecooldown.com/future-newsletter/?recIkJRW0nJxqbcxd)，获取容易**帮助自己**和帮助地球的**酷炫新闻**和**可行信息**。
