- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 13:09:58'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'Government awards $45B to company treating over 50M gallons of leaking radioactive
    waste: ''One of our nation''s most important environmental challenges'''
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.thecooldown.com/green-business/hanford-nuclear-site-contract-waste/](https://www.thecooldown.com/green-business/hanford-nuclear-site-contract-waste/)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: 'Photo Credit: Getty Images'
  prefs: []
  type: TYPE_NORMAL
- en: A 10-year contract has been re-awarded to a Virginia company tasked with cleaning
    up millions of gallons of radioactive and chemical waste.
  prefs: []
  type: TYPE_NORMAL
- en: The Tri-City Herald [reported](https://www.tri-cityherald.com/news/local/hanford/article286056551.html)
    Hanford Tank Waste Operations and Closure, or H2C, has been granted $45 billion
    by the U.S. Department of Energy to perform the work at the [Hanford Site](https://www.hanford.gov/).
  prefs: []
  type: TYPE_NORMAL
- en: The 580-square-mile site, located in the state of Washington, produced almost
    two-thirds of the plutonium for the country's nuclear weapons program from World
    War II through the Cold War.
  prefs: []
  type: TYPE_NORMAL
- en: This resulted in 56 million gallons of radioactive and hazardous waste being
    stored underground in tanks, raising fears of future contamination.
  prefs: []
  type: TYPE_NORMAL
- en: As detailed on Hanford's [official website](https://www.hanford.gov/page.cfm/HanfordTankB-109Overview),
    millions of gallons of the hazardous liquids had already seeped into the soil
    during the nuclear program, resulting in groundwater treatment systems eventually
    being installed to mitigate the issue.
  prefs: []
  type: TYPE_NORMAL
- en: In [August 2022](https://www.hanford.gov/page.cfm/HanfordTankB-109Overview),
    the DOE and Washington State Department of Ecology also signed an Agreed Order
    with their eyes on responding to existing leaks and preventing further contamination.
  prefs: []
  type: TYPE_NORMAL
- en: Good news, green hacks, and the latest cool clean tech — straight to your inbox
    every week!
  prefs: []
  type: TYPE_NORMAL
- en: H2C was first awarded the Hanford Integrated Tank Disposition Contract in April
    2023, but Hanford Tank Disposition Alliance (HTDA) appealed the decision in hopes
    of securing the funds before losing its bid. H2C is now tasked with single-shell
    tank retrieval and closure and the design, construction, and operation of waste
    facilities, according to [the DOE](https://www.energy.gov/em/articles/doe-awards-integrated-tank-disposition-contract-hanford-site-0).
  prefs: []
  type: TYPE_NORMAL
- en: Environmental health and safety are paramount to those aims, and security and
    emergency services are also part of the H2C's responsibilities. [Water contamination](https://guide.thecooldown.com/step/install-hydropanels/r/recMNv48ZH02XiHsf),
    whether through [plastic pollution](https://guide.thecooldown.com/step/explore-plastic-free-alternatives-for-everyday-products/r/recyyL53BQALKavvy)
    or [hazardous waste](https://www.thecooldown.com/green-business/southern-water-sewage-fine-raw-sewage-contamination-stream/),
    is known to have a wide range of harmful impacts on [local ecosystems](https://www.thecooldown.com/green-business/cape-fear-river-pollution-united-nations-human-rights/)
    and [human health](https://www.thecooldown.com/outdoors/plastic-pollution-microplastics-health-problem-ocean/).
  prefs: []
  type: TYPE_NORMAL
- en: The Hanford site partially feeds into the Columbia River, whose basin goes through
    [seven U.S. states](https://www.americanrivers.org/river/columbia-river/), providing
    irrigation for crops, drinking water for multiple communities, and serving as
    home to millions of salmon — [a vital food source](https://www.thecooldown.com/outdoors/salmon-spawning-rivers-conditions-drought/)
    that is also being negatively impacted by changing global temperatures driven
    by [human-made pollution](https://www.thecooldown.com/green-tech/methane-overheating-the-planet/).
  prefs: []
  type: TYPE_NORMAL
- en: According to Washington's [Department of Ecology](https://ecology.wa.gov/waste-toxics/nuclear-waste/hanford-cleanup),
    significant progress has been made in cleaning up the Hanford Site, but roughly
    "60 square miles of groundwater remains contaminated above federal standards."
  prefs: []
  type: TYPE_NORMAL
- en: As part of its contract, H2C will turn much of the remaining hazardous waste
    into glass for "permanent disposal," as reported by the Tri-City Herald for [The
    Daily News](https://tdn.com/news/state-and-regional/10-year-45-billion-contract-awarded-for-hanford-nuclear-waste-cleanup-in-eastern-wa/article_eac5bed6-d7fb-11ee-8ad1-77e80039858f.html).
    The Herald [added](https://www.tri-cityherald.com/news/local/hanford/article286056551.html)
    that a 120-day transition period is in place as H2C takes over from Washington
    River Protection Solutions, which had been leading cleanup efforts on short-term
    contracts since 2008.
  prefs: []
  type: TYPE_NORMAL
- en: '"Amentum and our partners have a tremendous track record of treating waste
    and managing nuclear operations around the DOE complex," Amentum National Security
    Group president Mark Whitney [told](https://www.tri-cityherald.com/news/local/hanford/article286056551.html)
    the outlet. "We will bring the most advanced technologies and experienced team
    to help solve one of our nation''s most important environmental challenges."'
  prefs: []
  type: TYPE_NORMAL
- en: Some might be eager for H2C to spearhead the cleanup, but it appears things
    are tied up in court for the time being. At the end of March, HTDA [filed](https://washingtontechnology.com/media/general/2024/4/hanford_tank_disposition_alliance_redacted_complaint_20240326.pdf)
    a second appeal with the aim of securing the 10-year contract, per [Washington
    Technology](https://washingtontechnology.com/contracts/2024/04/court-fight-over-45b-hanford-tank-contract-resumes/395404/).
  prefs: []
  type: TYPE_NORMAL
- en: Join our [free newsletter](https://www.thecooldown.com/future-newsletter/?recIkJRW0nJxqbcxd)
    for **cool news** and **actionable info** that makes it easy to **help yourself**
    while helping the planet.
  prefs: []
  type: TYPE_NORMAL
