- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 13:36:18'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 13:36:18'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'OSWorld: Benchmarking Multimodal Agents for Open-Ended Tasks in Real Computer
    Environments'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: OSWorld：在真实计算机环境中评估开放式任务的多模态代理基准
- en: 来源：[https://os-world.github.io/](https://os-world.github.io/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://os-world.github.io/](https://os-world.github.io/)
- en: Abstract
  id: totrans-split-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 摘要
- en: <md-block>Autonomous agents that accomplish complex computer tasks with minimal
    human interventions has the potential to transform human-computer interaction,
    significantly enhancing accessibility and productivity. However, existing benchmarks
    either lack an interactive environment or are limited to environments specific
    to certain applications or domains, failing to reflect the diverse and complex
    nature of real-world computer use, thereby limiting the scope of tasks and agent
    scalability. To address this issue, we introduce **OSWorld**, the first-of-its-kind
    scalable, real computer environment for multimodal agents, supporting task setup,
    execution-based evaluation, and interactive learning across various operating
    systems such as Ubuntu, Windows, and macOS. **OSWorld** can serve as a unified,
    integrated computer environment for assessing open-ended computer tasks that involve
    arbitrary applications. Building upon **OSWorld**, we create a benchmark of 369
    computer tasks involving real web and desktop apps in open domains, OS file I/O,
    and workflows spanning multiple applications. Each task example is derived from
    real-world computer use cases and includes a detailed initial state setup configuration
    and a custom execution-based evaluation script for reliable, reproducible evaluation.
    Extensive evaluation of state-of-the-art LLM/VLM-based agents on **OSWorld** reveals
    significant deficiencies in their ability to serve as computer assistants. While
    humans can accomplish over 72.36% of the tasks, the best model achieves only 12.24%
    success, primarily struggling with GUI grounding and operational knowledge. Comprehensive
    analysis using **OSWorld** provides valuable insights for developing multimodal
    generalist agents that were not possible with previous benchmarks.</md-block>
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: <md-block>通过最小的人工干预完成复杂计算机任务的自主代理，有潜力改变人机交互，显著提升可访问性和生产力。然而，现有的基准测试要么缺乏交互环境，要么仅限于特定应用或领域的环境，未能反映现实世界计算机使用的多样化和复杂性，从而限制了任务范围和代理的可扩展性。为了解决这个问题，我们引入了**OSWorld**，这是首个可扩展的真实计算机环境，适用于多模态代理，支持任务设置、基于执行的评估和跨Ubuntu、Windows和macOS等多个操作系统的交互学习。**OSWorld**可以作为一个统一的、集成的计算机环境，用于评估涉及任意应用程序的开放式计算机任务。在**OSWorld**的基础上，我们创建了一个基准测试，涵盖了369个计算机任务，包括真实的Web和桌面应用程序、操作系统文件I/O以及跨多个应用程序的工作流程。每个任务示例都源于真实的计算机使用案例，并包括详细的初始状态设置配置和可靠、可重复的执行基础评估脚本。对基于LLM/VLM的最新代理在**OSWorld**上进行的广泛评估显示，它们在作为计算机助手方面存在显著的不足。虽然人类可以完成超过72.36%的任务，但最佳模型仅能达到12.24%的成功率，主要困扰于GUI基础和操作知识。通过对**OSWorld**的全面分析，为开发以前基准测试无法实现的多模态通用代理提供了宝贵的见解。</md-block>
