- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 12:55:22'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: OWASP discloses breach due to a Wiki web server misconfig • The Register
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.theregister.com/2024/04/02/owasp_discloses_data_breach/](https://www.theregister.com/2024/04/02/owasp_discloses_data_breach/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: A misconfigured MediaWiki web server allowed digital snoops to access members'
    resumes containing their personal details at the Open Web Application Security
    Project (OWASP) Foundation.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: According to the nonprofit, which works to improve web app security, it became
    aware of the misconfig and subsequent data breach in late February after receiving
    "a few" report requests.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: '"If you were an OWASP member from 2006 to around 2014 and provided your resume
    as part of joining OWASP, we advise assuming your resume was part of this breach,"
    OWASP said in a Good Friday [notification](https://owasp.org/blog/2024/03/29/OWASP-data-breach-notification)
    posted on its website.'
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: '"We recognize the significance of this breach, especially considering the OWASP
    Foundation''s emphasis on cybersecurity," it added.'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: The resumes contained names, email addresses, phone numbers, physical addresses,
    "and other personally identifiable information," presumably people's places of
    employment, we're told.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: While the good news is that these resumes are at least a decade old in most
    cases, that's still a lot of individuals' details — OWASP boasts "tens of thousands
    of members" across more than 250 chapters worldwide.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: Presumably, at least some of these people still have the same identifiers that
    they did back in 2014, which can now be used for identity fraud and other nefarious
    purposes if they end up in the wrong hands or in a dark web database dump.
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: If you have the same email address or phone number, for example, OWASP urges
    caution when answering or receiving unsolicited emails and calls. These could
    lead to phishing attempts and financial crimes.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: According to the open source community, it no longer collects resumes as part
    of its membership application process and now uses two-factor authentication to
    protect member data.
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
- en: To make sure this doesn't happen again, OWASP said it disabled directory browsing
    and checked the web server for additional configuration and security issues, and
    removed all of the resumes from the site.
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
- en: Additionally, the foundation purged the CloudFlare caches, and requested that
    the accessed data be removed from the web archive.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
- en: While OWASP is attempting to notify affected individuals via email, the age
    of the resumes, between 10 and 18 years, makes it more difficult.
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: '"Regardless, we will contact the email addresses discovered during our investigations,"
    it pledged. ®'
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
