- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-27 12:55:22'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-27 12:55:22
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: OWASP discloses breach due to a Wiki web server misconfig • The Register
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: OWASP因Wiki Web服务器配置错误披露了此次数据泄露 • The Register
- en: 来源：[https://www.theregister.com/2024/04/02/owasp_discloses_data_breach/](https://www.theregister.com/2024/04/02/owasp_discloses_data_breach/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.theregister.com/2024/04/02/owasp_discloses_data_breach/](https://www.theregister.com/2024/04/02/owasp_discloses_data_breach/)
- en: A misconfigured MediaWiki web server allowed digital snoops to access members'
    resumes containing their personal details at the Open Web Application Security
    Project (OWASP) Foundation.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 一个配置错误的MediaWiki Web服务器允许数字窥探者访问Open Web应用安全项目（OWASP）基金会成员的简历，这些简历包含其个人详细信息。
- en: According to the nonprofit, which works to improve web app security, it became
    aware of the misconfig and subsequent data breach in late February after receiving
    "a few" report requests.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 根据致力于提高Web应用程序安全性的非营利组织，该组织在接收到“少量”报告请求后，于2月底意识到了配置错误和随后的数据泄露。
- en: '"If you were an OWASP member from 2006 to around 2014 and provided your resume
    as part of joining OWASP, we advise assuming your resume was part of this breach,"
    OWASP said in a Good Friday [notification](https://owasp.org/blog/2024/03/29/OWASP-data-breach-notification)
    posted on its website.'
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: '"如果您曾经在2006年至2014年期间是OWASP的成员，并作为加入OWASP的一部分提供了您的简历，我们建议您假设您的简历已包含在此次泄露中，"
    OWASP在其网站上发布的一份[通知](https://owasp.org/blog/2024/03/29/OWASP-data-breach-notification)中这样说。'
- en: '"We recognize the significance of this breach, especially considering the OWASP
    Foundation''s emphasis on cybersecurity," it added.'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: '"我们意识到这次数据泄露的重要性，特别是考虑到OWASP基金会对网络安全的强调。" 它补充道。'
- en: The resumes contained names, email addresses, phone numbers, physical addresses,
    "and other personally identifiable information," presumably people's places of
    employment, we're told.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: 简历中包含姓名、电子邮件地址、电话号码、物理地址，“以及其他可识别个人信息”，据称包括人们的就业地点。
- en: While the good news is that these resumes are at least a decade old in most
    cases, that's still a lot of individuals' details — OWASP boasts "tens of thousands
    of members" across more than 250 chapters worldwide.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 尽管好消息是，在大多数情况下，这些简历至少有十年的历史，但这仍然涉及大量个人的详细信息 — OWASP在全球超过250个章节中拥有“成千上万的成员”。
- en: Presumably, at least some of these people still have the same identifiers that
    they did back in 2014, which can now be used for identity fraud and other nefarious
    purposes if they end up in the wrong hands or in a dark web database dump.
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: 据推测，至少一些人仍然使用2014年的相同标识符，现在这些信息可能被用于身份欺诈和其他不正当目的，如果这些信息落入错误的手中或在暗网数据库中。
- en: If you have the same email address or phone number, for example, OWASP urges
    caution when answering or receiving unsolicited emails and calls. These could
    lead to phishing attempts and financial crimes.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: 如果您使用相同的电子邮件地址或电话号码，例如，OWASP建议在回答或接收未经请求的电子邮件和电话时要保持谨慎。这些可能导致钓鱼尝试和金融犯罪。
- en: According to the open source community, it no longer collects resumes as part
    of its membership application process and now uses two-factor authentication to
    protect member data.
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
  zh: 据开源社区称，它不再作为会员申请过程的一部分收集简历，现在使用两步验证来保护会员数据。
- en: To make sure this doesn't happen again, OWASP said it disabled directory browsing
    and checked the web server for additional configuration and security issues, and
    removed all of the resumes from the site.
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
  zh: 为了确保不再发生类似事件，OWASP表示禁用了目录浏览，并检查了Web服务器是否存在其他配置和安全问题，并从网站中删除了所有简历。
- en: Additionally, the foundation purged the CloudFlare caches, and requested that
    the accessed data be removed from the web archive.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
  zh: 此外，基金会清除了CloudFlare缓存，并要求从Web存档中删除访问的数据。
- en: While OWASP is attempting to notify affected individuals via email, the age
    of the resumes, between 10 and 18 years, makes it more difficult.
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
  zh: 尽管OWASP正尝试通过电子邮件通知受影响的个人，但简历的年龄在10到18年之间，使其变得更加困难。
- en: '"Regardless, we will contact the email addresses discovered during our investigations,"
    it pledged. ®'
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
  zh: '"不过，我们将联系在我们的调查中发现的电子邮件地址，" 它承诺道。 ®'
