- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 13:06:20'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 13:06:20'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Page not found – Krebs on Security
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: Krebs on Security 网站上找不到页面
- en: 来源：[https://krebsonsecurity.com/2024/04/why-cisa-is-warning-cisos-about-a-breach-at-sisense/https://www.macrumors.com/2024/04/11/m4-ai-chips-late-2024/](https://krebsonsecurity.com/2024/04/why-cisa-is-warning-cisos-about-a-breach-at-sisense/https://www.macrumors.com/2024/04/11/m4-ai-chips-late-2024/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://krebsonsecurity.com/2024/04/why-cisa-is-warning-cisos-about-a-breach-at-sisense/https://www.macrumors.com/2024/04/11/m4-ai-chips-late-2024/](https://krebsonsecurity.com/2024/04/why-cisa-is-warning-cisos-about-a-breach-at-sisense/https://www.macrumors.com/2024/04/11/m4-ai-chips-late-2024/)
- en: Kindly search your topic below or browse the recent posts.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 请在下方搜索您的主题或浏览最近的帖子。
