- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 12:56:00'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: 'Productivity Paradox: Background'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://cs.stanford.edu/people/eroberts/cs201/projects/productivity-paradox/background.html](https://cs.stanford.edu/people/eroberts/cs201/projects/productivity-paradox/background.html)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Background
  id: totrans-split-6
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: What is Information Technology
  id: totrans-split-7
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: "Perhaps we should start by first defining what IT really is. According to the\
    \ Information Technology Association of America, information technology is \x93\
    the study, design, development, implementation, support or management of computer-based\
    \ information systems, particularly software applications and computer hardware.\x94\
    \ Essentially anything that has to do with computers and computing is some form\
    \ of information technology. Therefore, whenever organizations choose to buy computers,\
    \ databases, networks, software, or many other computer related materials, they\
    \ are making an investment in IT. Although on the surface this seems like a great\
    \ thing, the reality is that it\x92s not immediately evident that investing in\
    \ IT is actually profitable. In fact, much of the evidence from the 1960s to the\
    \ 1980s indicated otherwise."
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: What about the Productivity Paradox
  id: totrans-split-9
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: The productivity paradox (also the Solow computer paradox) is the peculiar observation
    made in business process analysis that, as more investment is made in information
    technology, worker productivity may go down instead of up. This observation has
    been firmly supported with empirical evidence from the 1970s to the early 1990s.
    This is highly counter intuitive. Before investment in IT became widespread, the
    expected return on investment in terms of productivity was 3-4%. This average
    rate developed from the mechanization/automation of the farm and factory sectors.
    With IT though, the normal return on investment was only 1% from the 1970s to
    the early 1990s.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: There were a number of theories proposed that explained the productivity paradox.
    There ranged from ideas about inadequate measurement of productivity to the necessary
    lag period before actual gains in productivity could be seen. Until recently these
    explanations were little more than theories, but now many of them have hard evidence
    to support then due to studies that show a large increases in productivity in
    companies that invested heavily in IT.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: The Development of the Paradox
  id: totrans-split-12
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'The way the productivity paradox unfolded is best describes by Stuart MacDonald
    and his colleagues in his paper, [Measurement or Management?: Revisiting the Productivity
    Paradox of Information Technology](http://www.diw.de/documents/publikationen/73/38739/v_00_4_9.382949.pdf).
    According to MacDonald, the paradox began to take place in the early 1970s and
    progressed through 5 stages.'
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: Stage 1
  id: totrans-split-14
  prefs:
  - PREF_H4
  type: TYPE_NORMAL
- en: These were the early days, when not much was known about the implications of
    IT investment and expectations were huge. The idea of IT investment was so novel
    that there was a broad notion that IT was going displace labor entirely. Ever
    since this early period of investment in IT, it was assumed that labor productivity
    was the correct way to measure the impact IT had.
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
- en: Stage 2
  id: totrans-split-16
  prefs:
  - PREF_H4
  type: TYPE_NORMAL
- en: This stage started in the late 1970s and marked the first indications that the
    result of IT investment was less than expected. Even though this was the case,
    companies continued to funnel huge amounts of capitol into computing. Most companies
    didn't even bother to try and evaluate their IT investment. Those that did usually
    only used return on investment calculations.
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: Stage 3
  id: totrans-split-18
  prefs:
  - PREF_H4
  type: TYPE_NORMAL
- en: This stage, which spanned the early 1980s, was marked by the realization that
    IT was only to be used in terms of productivity. Instead, companies began to use
    IT strategy. Several comapanies (American Airlines, American Hospital Supplies,
    and Citibank) strategically used IT to create a competitive advantage over their
    competitors.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
- en: Stage 4
  id: totrans-split-20
  prefs:
  - PREF_H4
  type: TYPE_NORMAL
- en: By the late 1980s IT investments migrated to management information systems.
    In this new area IT was no longer expected to be directly productive. It was also
    during this time that numerous explanations for the productivity paradox emerged.
    Although none of them individually provided a concrete explanation, collectively
    they hinted at a larger problem.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
- en: Stage 5
  id: totrans-split-22
  prefs:
  - PREF_H4
  type: TYPE_NORMAL
- en: After the late 1980s, most of the investment in IT has been in telecommunications.
    With this new area of investment, expectations of productivity increases were
    further lowered.
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
