- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 12:49:36'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Ross Anderson - Schneier on Security
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.schneier.com/blog/archives/2024/03/ross-anderson.html](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Ross Anderson
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[Ross Anderson](https://www.cl.cam.ac.uk/~rja14/) unexpectedly passed away
    [Thursday night](https://www.lightbluetouchpaper.org/2024/03/29/rip-ross-anderson/)
    in, I believe, his home in Cambridge.'
  prefs: []
  type: TYPE_NORMAL
- en: I can’t remember when I first met Ross. Of course it was before 2008, when we
    created the [Security and Human Behavior](https://www.schneier.com/blog/archives/2023/06/security-and-human-behavior-shb-2023.html)
    workshop. It was well before 2001, when we created the [Workshop on Economics
    and Information Security](https://econinfosec.org/). (Okay, he created both—I
    helped.) It was before 1998, when we [wrote about](https://www.schneier.com/academic/archives/1997/04/the_risks_of_key_rec.html)
    the problems with key escrow systems. I was one of the people he brought to the
    Newton Institute, at Cambridge University, for the six-month cryptography residency
    program he ran (I mistakenly didn’t stay the whole time)—that was in 1996.
  prefs: []
  type: TYPE_NORMAL
- en: I know I was at the first [Fast Software Encryption](https://iacr.org/meetings/fse/)
    workshop in December 1993, another conference he created. There I presented the
    [Blowfish](https://www.schneier.com/academic/archives/1994/09/description_of_a_new.html)
    encryption algorithm. Pulling an old first-edition of *[Applied Cryptography](https://www.amazon.com/Applied-Cryptography-Protocols-Algorithms-Source/dp/0471597562)*
    (the one with the blue cover) down from the shelf, I see his name in the acknowledgments.
    Which means that sometime in early 1993—probably at Eurocrypt in Lofthus, Norway—I,
    as an unpublished book author who had only written a couple of crypto articles
    for *Dr. Dobb’s Journal*, asked him to read and comment on my book manuscript.
    And he said yes. Which means I mailed him a paper copy. And he read it. And mailed
    his handwritten comments back to me. In an envelope with stamps. Because that’s
    how we did it back then.
  prefs: []
  type: TYPE_NORMAL
- en: I have known Ross for over thirty years, as both a colleague and a friend. He
    was enthusiastic, brilliant, opinionated, articulate, curmudgeonly, and kind.
    Pick up any of his academic papers—there are [many](https://www.cl.cam.ac.uk/~rja14/#Research)—and
    odds are that you will find a least one unexpected insight. He was a cryptographer
    and security engineer, but also very much a generalist. He published on block
    cipher cryptanalysis in the 1990s, and the security of large-language models last
    year. He started conferences like nobody’s business. His masterwork book, *[Security
    Engineering](https://www.cl.cam.ac.uk/~rja14/book.html)*—now in its third edition—is
    as comprehensive a tome on cybersecurity and related topics as you could imagine.
    (Also note his fifteen-lecture video series on that same page. If you have never
    heard Ross lecture, you’re in for a treat.) He was the [first person](https://www.acsac.org/2001/papers/110.pdf)
    to understand that security problems are often actually [economic problems](https://www.cl.cam.ac.uk/~rja14/econsec.html).
    He was the first person to make a lot of those sorts of connections. He fought
    against surveillance and backdoors, and for academic freedom. He didn’t suffer
    fools in either government or the corporate world.
  prefs: []
  type: TYPE_NORMAL
- en: 'He’s listed in the acknowledgments as a reader of every one of my books from
    [*Beyond Fear*](https://www.schneier.com/books/beyond-fear/) on. Recently, we’d
    see each other a couple of times a year: at this or that workshop or event. The
    last time I saw him was last June, at [SHB 2023](https://www.heinz.cmu.edu/~acquisti/SHB2023/index.htm),
    in Pittsburgh. We were having dinner on [Alessandro Acquisti](https://www.heinz.cmu.edu/~acquisti/)‘s
    rooftop patio, celebrating another successful workshop. He was going to attend
    my [Workshop on Reimagining Democracy](https://www.schneier.com/blog/archives/2024/01/second-interdisciplinary-workshop-on-reimagining-democracy.html)
    in December, but he had to cancel at the last minute. (He sent me the talk he
    was going to give. I will see about posting it.) The day before he died, we were
    discussing how to accommodate everyone who registered for this year’s [SHB workshop](https://www.schneier.com/shb/2024/).
    I learned something from him every single time we talked. And I am not the only
    one.'
  prefs: []
  type: TYPE_NORMAL
- en: My heart goes out to his wife Shireen and his family. We lost him much too soon.
  prefs: []
  type: TYPE_NORMAL
- en: 'EDITED TO ADD (4/10): I wrote a [longer version](https://www.schneier.com/essays/archives/2024/04/in-memoriam-ross-anderson-1956-2024.html)
    for Communications of the ACM.'
  prefs: []
  type: TYPE_NORMAL
- en: 'EDITED TO ADD (4/11): Two weeks before he passed away, Ross gave an 80-minute
    [interview](https://www.youtube.com/watch?v=jkd-xp4xzlw) where he told his life
    story.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [cryptanalysis](https://www.schneier.com/tag/cryptanalysis/), [cryptography](https://www.schneier.com/tag/cryptography/),
    [cybersecurity](https://www.schneier.com/tag/cybersecurity/), [economics of security](https://www.schneier.com/tag/economics-of-security/),
    [security conferences](https://www.schneier.com/tag/security-conferences/), [security
    engineering](https://www.schneier.com/tag/security-engineering/)'
  prefs: []
  type: TYPE_NORMAL
- en: '[Posted on March 31, 2024 at 8:21 PM](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html)
    • [22 Comments](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html#comments)'
  prefs: []
  type: TYPE_NORMAL
