- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 12:49:36'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Ross Anderson - Schneier on Security
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.schneier.com/blog/archives/2024/03/ross-anderson.html](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Ross Anderson
  id: totrans-split-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '[Ross Anderson](https://www.cl.cam.ac.uk/~rja14/) unexpectedly passed away
    [Thursday night](https://www.lightbluetouchpaper.org/2024/03/29/rip-ross-anderson/)
    in, I believe, his home in Cambridge.'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: I can’t remember when I first met Ross. Of course it was before 2008, when we
    created the [Security and Human Behavior](https://www.schneier.com/blog/archives/2023/06/security-and-human-behavior-shb-2023.html)
    workshop. It was well before 2001, when we created the [Workshop on Economics
    and Information Security](https://econinfosec.org/). (Okay, he created both—I
    helped.) It was before 1998, when we [wrote about](https://www.schneier.com/academic/archives/1997/04/the_risks_of_key_rec.html)
    the problems with key escrow systems. I was one of the people he brought to the
    Newton Institute, at Cambridge University, for the six-month cryptography residency
    program he ran (I mistakenly didn’t stay the whole time)—that was in 1996.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: I know I was at the first [Fast Software Encryption](https://iacr.org/meetings/fse/)
    workshop in December 1993, another conference he created. There I presented the
    [Blowfish](https://www.schneier.com/academic/archives/1994/09/description_of_a_new.html)
    encryption algorithm. Pulling an old first-edition of *[Applied Cryptography](https://www.amazon.com/Applied-Cryptography-Protocols-Algorithms-Source/dp/0471597562)*
    (the one with the blue cover) down from the shelf, I see his name in the acknowledgments.
    Which means that sometime in early 1993—probably at Eurocrypt in Lofthus, Norway—I,
    as an unpublished book author who had only written a couple of crypto articles
    for *Dr. Dobb’s Journal*, asked him to read and comment on my book manuscript.
    And he said yes. Which means I mailed him a paper copy. And he read it. And mailed
    his handwritten comments back to me. In an envelope with stamps. Because that’s
    how we did it back then.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: I have known Ross for over thirty years, as both a colleague and a friend. He
    was enthusiastic, brilliant, opinionated, articulate, curmudgeonly, and kind.
    Pick up any of his academic papers—there are [many](https://www.cl.cam.ac.uk/~rja14/#Research)—and
    odds are that you will find a least one unexpected insight. He was a cryptographer
    and security engineer, but also very much a generalist. He published on block
    cipher cryptanalysis in the 1990s, and the security of large-language models last
    year. He started conferences like nobody’s business. His masterwork book, *[Security
    Engineering](https://www.cl.cam.ac.uk/~rja14/book.html)*—now in its third edition—is
    as comprehensive a tome on cybersecurity and related topics as you could imagine.
    (Also note his fifteen-lecture video series on that same page. If you have never
    heard Ross lecture, you’re in for a treat.) He was the [first person](https://www.acsac.org/2001/papers/110.pdf)
    to understand that security problems are often actually [economic problems](https://www.cl.cam.ac.uk/~rja14/econsec.html).
    He was the first person to make a lot of those sorts of connections. He fought
    against surveillance and backdoors, and for academic freedom. He didn’t suffer
    fools in either government or the corporate world.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: 我认识Ross已经三十多年了，既是同事也是朋友。他热情、聪明、有主见、口才流利、性情乖戾但又善良。随便拿起他的任何学术论文——有[很多](https://www.cl.cam.ac.uk/~rja14/#Research)——你很可能会找到至少一个意想不到的洞见。他是一名密码学家和安全工程师，但也是一位非常全面的学者。他在1990年代发表了有关块密码破译的文章，去年又发表了关于大语言模型安全性的文章。他如麻地创办了各种会议。他的巨著书籍，《[安全工程](https://www.cl.cam.ac.uk/~rja14/book.html)》，现已进入第三版，是关于网络安全及相关主题的全面巨著。
    （还要注意同一页上的他十五讲视频系列。如果你从未听过Ross讲课，你将有所收获。）他是[第一个](https://www.acsac.org/2001/papers/110.pdf)理解安全问题通常实际上是[经济问题](https://www.cl.cam.ac.uk/~rja14/econsec.html)的人。他是第一个做出这类联系的人。他反对监视和后门，并支持学术自由。他既不容忍政府也不容忍企业世界的愚蠢行为。
- en: 'He’s listed in the acknowledgments as a reader of every one of my books from
    [*Beyond Fear*](https://www.schneier.com/books/beyond-fear/) on. Recently, we’d
    see each other a couple of times a year: at this or that workshop or event. The
    last time I saw him was last June, at [SHB 2023](https://www.heinz.cmu.edu/~acquisti/SHB2023/index.htm),
    in Pittsburgh. We were having dinner on [Alessandro Acquisti](https://www.heinz.cmu.edu/~acquisti/)‘s
    rooftop patio, celebrating another successful workshop. He was going to attend
    my [Workshop on Reimagining Democracy](https://www.schneier.com/blog/archives/2024/01/second-interdisciplinary-workshop-on-reimagining-democracy.html)
    in December, but he had to cancel at the last minute. (He sent me the talk he
    was going to give. I will see about posting it.) The day before he died, we were
    discussing how to accommodate everyone who registered for this year’s [SHB workshop](https://www.schneier.com/shb/2024/).
    I learned something from him every single time we talked. And I am not the only
    one.'
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 他在致谢中列出他是我从[*超越恐惧*](https://www.schneier.com/books/beyond-fear/)开始的每一本书的读者。最近几年，我们每年都会见面几次：在这个或那个研讨会或活动上。我上次见到他是去年6月，在[Pittsburgh的SHB
    2023](https://www.heinz.cmu.edu/~acquisti/SHB2023/index.htm)上。我们正在[Alessandro
    Acquisti](https://www.heinz.cmu.edu/~acquisti/)的屋顶露台上吃晚餐，庆祝另一个成功的研讨会。他原本打算参加我在12月的[重新想象民主研讨会](https://www.schneier.com/blog/archives/2024/01/second-interdisciplinary-workshop-on-reimagining-democracy.html)，但他在最后一刻取消了。
    （他把他打算发表的演讲稿发给了我。我会考虑发布它。）他去世的前一天，我们正在讨论如何安排今年的[SHB研讨会](https://www.schneier.com/shb/2024/)的所有注册人员。每次我们交谈时，我都从他那里学到了一些东西。而我并不是唯一一个。
- en: My heart goes out to his wife Shireen and his family. We lost him much too soon.
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: 我对他的妻子Shireen和他的家人深感同情。我们失去了他，实在是太早了。
- en: 'EDITED TO ADD (4/10): I wrote a [longer version](https://www.schneier.com/essays/archives/2024/04/in-memoriam-ross-anderson-1956-2024.html)
    for Communications of the ACM.'
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: 编辑添加（4/10）：我为《ACM通讯》写了一个[更长版本](https://www.schneier.com/essays/archives/2024/04/in-memoriam-ross-anderson-1956-2024.html)。
- en: 'EDITED TO ADD (4/11): Two weeks before he passed away, Ross gave an 80-minute
    [interview](https://www.youtube.com/watch?v=jkd-xp4xzlw) where he told his life
    story.'
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
  zh: 编辑添加（4/11）：在他去世前两周，Ross参加了一个长达80分钟的[采访](https://www.youtube.com/watch?v=jkd-xp4xzlw)，讲述了他的一生。
- en: 'Tags: [cryptanalysis](https://www.schneier.com/tag/cryptanalysis/), [cryptography](https://www.schneier.com/tag/cryptography/),
    [cybersecurity](https://www.schneier.com/tag/cybersecurity/), [economics of security](https://www.schneier.com/tag/economics-of-security/),
    [security conferences](https://www.schneier.com/tag/security-conferences/), [security
    engineering](https://www.schneier.com/tag/security-engineering/)'
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
  zh: 标签：[密码分析](https://www.schneier.com/tag/cryptanalysis/)，[密码学](https://www.schneier.com/tag/cryptography/)，[网络安全](https://www.schneier.com/tag/cybersecurity/)，[安全经济学](https://www.schneier.com/tag/economics-of-security/)，[安全会议](https://www.schneier.com/tag/security-conferences/)，[安全工程](https://www.schneier.com/tag/security-engineering/)
- en: '[Posted on March 31, 2024 at 8:21 PM](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html)
    • [22 Comments](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html#comments)'
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
  zh: '[2024年3月31日晚上8:21发布](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html)
    • [22 条评论](https://www.schneier.com/blog/archives/2024/03/ross-anderson.html#comments)'
