- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 12:54:46'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Self-Hosted Applications and Alternatives
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://selfh.st/apps/](https://selfh.st/apps/)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Click
  prefs: []
  type: TYPE_NORMAL
- en: '[****here****](https://selfh.st/companions)'
  prefs: []
  type: TYPE_NORMAL
- en: for a directory of companion apps for the software below, or
  prefs: []
  type: TYPE_NORMAL
- en: '[****here****](https://selfh.st/about-apps/)'
  prefs: []
  type: TYPE_NORMAL
- en: for information and frequently asked questions about this list.
  prefs: []
  type: TYPE_NORMAL
