- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 12:54:46'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 12:54:46'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Self-Hosted Applications and Alternatives
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 自托管应用及替代方案
- en: 来源：[https://selfh.st/apps/](https://selfh.st/apps/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://selfh.st/apps/](https://selfh.st/apps/)
- en: Click
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 点击
- en: '[****here****](https://selfh.st/companions)'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: '[****这里****](https://selfh.st/companions)'
- en: for a directory of companion apps for the software below, or
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 查看以下软件的伴侣应用程序目录，或者
- en: '[****here****](https://selfh.st/about-apps/)'
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: '[****这里****](https://selfh.st/about-apps/)'
- en: for information and frequently asked questions about this list.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: 有关此列表的信息和常见问题，请查看。
