- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 12:57:23'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Surveillance by the New Microsoft Outlook App - Schneier on Security
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Surveillance by the New Microsoft Outlook App
  id: totrans-split-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'The ProtonMail people are accusing Microsoft’s new Outlook for Windows app
    of [conducting extensive surveillance](https://proton.me/blog/outlook-is-microsofts-new-data-collection-service)
    on its users. It shares data with advertisers, a lot of data:'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: 'The window informs users that Microsoft and those 801 third parties use their
    data for a number of purposes, including to:'
  id: totrans-split-8
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Store and/or access information on the user’s device
  id: totrans-split-9
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Develop and improve products
  id: totrans-split-10
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Personalize ads and content
  id: totrans-split-11
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Measure ads and content
  id: totrans-split-12
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Derive audience insights
  id: totrans-split-13
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Obtain precise geolocation data
  id: totrans-split-14
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Identify users through device scanning
  id: totrans-split-15
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: '[Commentary](https://www.ghacks.net/2024/01/12/proton-mail-says-that-the-new-outlook-app-for-windows-is-microsofts-new-data-collection-service/).'
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [data collection](https://www.schneier.com/tag/data-collection/), [geolocation](https://www.schneier.com/tag/geolocation/),
    [Microsoft](https://www.schneier.com/tag/microsoft/), [privacy](https://www.schneier.com/tag/privacy/),
    [surveillance](https://www.schneier.com/tag/surveillance/)'
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: '[Posted on April 4, 2024 at 7:07 AM](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
    • [42 Comments](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html#comments)'
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
- en: Sidebar photo of Bruce Schneier by Joe MacInnis.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
