- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 12:57:23'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 12:57:23'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Surveillance by the New Microsoft Outlook App - Schneier on Security
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 新版 Microsoft Outlook 应用的监控 - 施奈尔安全
- en: 来源：[https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
- en: Surveillance by the New Microsoft Outlook App
  id: totrans-split-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 新版 Microsoft Outlook 应用的监控
- en: 'The ProtonMail people are accusing Microsoft’s new Outlook for Windows app
    of [conducting extensive surveillance](https://proton.me/blog/outlook-is-microsofts-new-data-collection-service)
    on its users. It shares data with advertisers, a lot of data:'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: ProtonMail 的人们指责 Microsoft 新版 Outlook for Windows 应用 [大规模进行监控](https://proton.me/blog/outlook-is-microsofts-new-data-collection-service)
    其用户。它与广告商分享了大量数据：
- en: 'The window informs users that Microsoft and those 801 third parties use their
    data for a number of purposes, including to:'
  id: totrans-split-8
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 窗口通知用户，Microsoft 和 801 家第三方利用其数据进行多种目的，包括：
- en: Store and/or access information on the user’s device
  id: totrans-split-9
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
  zh: 存储和/或访问用户设备上的信息
- en: Develop and improve products
  id: totrans-split-10
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
  zh: 开发和改进产品
- en: Personalize ads and content
  id: totrans-split-11
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
  zh: 个性化广告和内容
- en: Measure ads and content
  id: totrans-split-12
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
  zh: 测量广告和内容
- en: Derive audience insights
  id: totrans-split-13
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
  zh: 推断观众见解
- en: Obtain precise geolocation data
  id: totrans-split-14
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
  zh: 获取精确的地理位置数据
- en: Identify users through device scanning
  id: totrans-split-15
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
  zh: 通过设备扫描识别用户
- en: '[Commentary](https://www.ghacks.net/2024/01/12/proton-mail-says-that-the-new-outlook-app-for-windows-is-microsofts-new-data-collection-service/).'
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
  zh: '[评论](https://www.ghacks.net/2024/01/12/proton-mail-says-that-the-new-outlook-app-for-windows-is-microsofts-new-data-collection-service/)。'
- en: 'Tags: [data collection](https://www.schneier.com/tag/data-collection/), [geolocation](https://www.schneier.com/tag/geolocation/),
    [Microsoft](https://www.schneier.com/tag/microsoft/), [privacy](https://www.schneier.com/tag/privacy/),
    [surveillance](https://www.schneier.com/tag/surveillance/)'
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
  zh: 标签：[数据收集](https://www.schneier.com/tag/data-collection/)，[地理位置](https://www.schneier.com/tag/geolocation/)，[Microsoft](https://www.schneier.com/tag/microsoft/)，[隐私](https://www.schneier.com/tag/privacy/)，[监控](https://www.schneier.com/tag/surveillance/)
- en: '[Posted on April 4, 2024 at 7:07 AM](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
    • [42 Comments](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html#comments)'
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
  zh: '[发布于 2024年4月4日上午7:07](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
    • [42 评论](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html#comments)'
- en: Sidebar photo of Bruce Schneier by Joe MacInnis.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
  zh: 侧边栏照片由乔·马基尼斯拍摄的布鲁斯·施奈尔。
