- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 12:57:23'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Surveillance by the New Microsoft Outlook App - Schneier on Security
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Surveillance by the New Microsoft Outlook App
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'The ProtonMail people are accusing Microsoft’s new Outlook for Windows app
    of [conducting extensive surveillance](https://proton.me/blog/outlook-is-microsofts-new-data-collection-service)
    on its users. It shares data with advertisers, a lot of data:'
  prefs: []
  type: TYPE_NORMAL
- en: 'The window informs users that Microsoft and those 801 third parties use their
    data for a number of purposes, including to:'
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: ''
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Store and/or access information on the user’s device
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Develop and improve products
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Personalize ads and content
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Measure ads and content
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Derive audience insights
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Obtain precise geolocation data
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: Identify users through device scanning
  prefs:
  - PREF_BQ
  - PREF_UL
  type: TYPE_NORMAL
- en: '[Commentary](https://www.ghacks.net/2024/01/12/proton-mail-says-that-the-new-outlook-app-for-windows-is-microsofts-new-data-collection-service/).'
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [data collection](https://www.schneier.com/tag/data-collection/), [geolocation](https://www.schneier.com/tag/geolocation/),
    [Microsoft](https://www.schneier.com/tag/microsoft/), [privacy](https://www.schneier.com/tag/privacy/),
    [surveillance](https://www.schneier.com/tag/surveillance/)'
  prefs: []
  type: TYPE_NORMAL
- en: '[Posted on April 4, 2024 at 7:07 AM](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html)
    • [42 Comments](https://www.schneier.com/blog/archives/2024/04/surveillance-by-the-new-microsoft-outlook-app.html#comments)'
  prefs: []
  type: TYPE_NORMAL
- en: Sidebar photo of Bruce Schneier by Joe MacInnis.
  prefs: []
  type: TYPE_NORMAL
