- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 13:25:46'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Trainee crashed a mainframe, taking a huge business down too • The Register
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.theregister.com/2024/04/19/on_call/](https://www.theregister.com/2024/04/19/on_call/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: On Call Welcome once more to On Call, *The Register*'s Friday foray into tech
    support memories contributed by you, our much-appreciated readers.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: This week, meet a *Reg*-admirer we'll anonymize as "Leanne" who once worked
    as a senior architect in a mainframe environment – a role that saw her keep an
    eye on several of internal chats in which colleagues would share news of glitches
    and oddities she would be asked to check out.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: One day a senior database administrator pinged one of those chats with the unwelcome
    observation that they were pretty sure some files had gone missing. Could Leanne
    check the mainframe?
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: Leanne's console told her all was well with the big box. But multiple threads
    soon reported problems. Severe problems.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: '"People couldn''t log in, the business was down, SEV-1 tickets were stacking
    up. Alarm bells were ringing," Leanne told On Call.'
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: But according to the screen she saw, the mainframe was alive and well.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: A little digging into system logs revealed the mainframe was upset because requests
    to the mighty machine's direct-access storage device (DASD) were failing.
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: Leanne got together with colleagues and her employer's outsourced maintenance
    provider to investigate the situation.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: 'The problem was obvious: the DASD had been deliberately taken offline. The
    mainframe was therefore unable to access its only source of storage.'
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
- en: Who had done this deed?
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
- en: A trainee from the mainframe vendor admitted they had flipped the switch.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
- en: '"I put in the wrong command, and then the system wouldn''t let me put in the
    right one," was the rookie''s excuse.'
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: Leanne assessed the situation and decided the trainee "had no idea what she
    was doing and did not know what she had done."
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
- en: What she had done was take a big chunk of a Fortune 500 company offline. On
    Monday morning, just as the week was getting busy.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
- en: Happily, Leanne's position meant she had privileges that allowed her to reconnect
    the DASD.
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
- en: Which she did ASAP, averting disaster.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
- en: '"The vendor was read the riot act for putting an unsupervised trainee on the
    console, and the trainee got to listen to her management get in trouble with the
    customer," Leanne told On Call, rating the incident as "Fun, fun all around."'
  id: totrans-split-22
  prefs: []
  type: TYPE_NORMAL
- en: And maybe, also, one of history's great debrief meetings and/or lessons in giving
    a vendor a kicking for doing exactly what they're paid not to do.
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
- en: Has an ignorant kid broken your boxes? Or has an outsourced supplier brought
    you undone? On Call wants your story so we can share it here on a future Friday,
    and the good news is sending it to us is as simple as [clicking here to send us
    an email](mailto:oncall@theregister.com). ®
  id: totrans-split-24
  prefs: []
  type: TYPE_NORMAL
