- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 13:25:46'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-27 13:25:46
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Trainee crashed a mainframe, taking a huge business down too • The Register
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 实习生摧毁了一台主机，导致一家大企业陷入困境 • The Register
- en: 来源：[https://www.theregister.com/2024/04/19/on_call/](https://www.theregister.com/2024/04/19/on_call/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.theregister.com/2024/04/19/on_call/](https://www.theregister.com/2024/04/19/on_call/)
- en: On Call Welcome once more to On Call, *The Register*'s Friday foray into tech
    support memories contributed by you, our much-appreciated readers.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: On Call再次欢迎您来到On Call，*The Register*的技术支持回忆录，由您，我们非常感激的读者，贡献。
- en: This week, meet a *Reg*-admirer we'll anonymize as "Leanne" who once worked
    as a senior architect in a mainframe environment – a role that saw her keep an
    eye on several of internal chats in which colleagues would share news of glitches
    and oddities she would be asked to check out.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 本周，让我们认识一位*Reg*的崇拜者，我们将匿名化为"Leanne"，她曾在一个主机环境中担任高级架构师的角色——这个角色让她关注几个内部聊天室，同事们会在其中分享她需要检查的故障和奇怪的事情。
- en: One day a senior database administrator pinged one of those chats with the unwelcome
    observation that they were pretty sure some files had gone missing. Could Leanne
    check the mainframe?
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 有一天，一位高级数据库管理员在其中一个聊天室中发出不受欢迎的观察，他非常确信一些文件已经丢失了。Leanne可以检查一下主机吗？
- en: Leanne's console told her all was well with the big box. But multiple threads
    soon reported problems. Severe problems.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: Leanne的控制台告诉她大盒子一切正常。但很快就有多个线程报告了问题。严重的问题。
- en: '"People couldn''t log in, the business was down, SEV-1 tickets were stacking
    up. Alarm bells were ringing," Leanne told On Call.'
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: '"人们无法登录，业务瘫痪，SEV-1票据堆积如山。警报正在响起，" Leanne告诉On Call。'
- en: But according to the screen she saw, the mainframe was alive and well.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 但根据她看到的屏幕，主机运行良好。
- en: A little digging into system logs revealed the mainframe was upset because requests
    to the mighty machine's direct-access storage device (DASD) were failing.
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: 通过对系统日志的一点挖掘，发现主机因为直接访问存储设备（DASD）的请求失败而感到不安。
- en: Leanne got together with colleagues and her employer's outsourced maintenance
    provider to investigate the situation.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: Leanne与同事和雇主外包的维护提供商一起调查了这一情况。
- en: 'The problem was obvious: the DASD had been deliberately taken offline. The
    mainframe was therefore unable to access its only source of storage.'
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
  zh: 问题显而易见：DASD被故意脱机了。因此，主机无法访问其唯一的存储源。
- en: Who had done this deed?
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
  zh: 是谁做了这件事？
- en: A trainee from the mainframe vendor admitted they had flipped the switch.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
  zh: 一位来自主机供应商的实习生承认他们已经转动了开关。
- en: '"I put in the wrong command, and then the system wouldn''t let me put in the
    right one," was the rookie''s excuse.'
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
  zh: '"我输入了错误的命令，然后系统不让我输入正确的命令，" 新手的借口如此说道。'
- en: Leanne assessed the situation and decided the trainee "had no idea what she
    was doing and did not know what she had done."
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
  zh: Leanne评估了情况，决定实习生"不知道她在做什么，也不知道她做了什么"。
- en: What she had done was take a big chunk of a Fortune 500 company offline. On
    Monday morning, just as the week was getting busy.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
  zh: 她所做的就是让一个财富500强企业的大部分设备脱机。就在星期一早上，一周开始变得繁忙的时候。
- en: Happily, Leanne's position meant she had privileges that allowed her to reconnect
    the DASD.
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
  zh: 令人高兴的是，Leanne的职位使她有特权可以重新连接DASD。
- en: Which she did ASAP, averting disaster.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
  zh: 她尽快处理了这些，避免了灾难。
- en: '"The vendor was read the riot act for putting an unsupervised trainee on the
    console, and the trainee got to listen to her management get in trouble with the
    customer," Leanne told On Call, rating the incident as "Fun, fun all around."'
  id: totrans-split-22
  prefs: []
  type: TYPE_NORMAL
  zh: '"供应商因为将一个没有监督的实习生放在控制台上而受到了严厉警告，实习生则听着她的管理层因顾客而惹上麻烦，" Leanne告诉On Call，将这一事件评为"有趣，全场欢呼。"'
- en: And maybe, also, one of history's great debrief meetings and/or lessons in giving
    a vendor a kicking for doing exactly what they're paid not to do.
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
  zh: 也许，这也是历史上一次伟大的总结会和/或给予供应商一记教训，让他们做了他们应该避免做的事情。
- en: Has an ignorant kid broken your boxes? Or has an outsourced supplier brought
    you undone? On Call wants your story so we can share it here on a future Friday,
    and the good news is sending it to us is as simple as [clicking here to send us
    an email](mailto:oncall@theregister.com). ®
  id: totrans-split-24
  prefs: []
  type: TYPE_NORMAL
  zh: 是一个无知的孩子搞砸了你的设备？还是外包供应商让你遭罪？On Call希望听到你的故事，这样我们就可以在未来的星期五在这里分享它，好消息是将其发送给我们就像[点击这里发送电子邮件](mailto:oncall@theregister.com)一样简单。®
