- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 14:53:32'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 14:53:32'
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: A pilot study of chlormequat in food and urine from adults in the United States
    from 2017 to 2023 | Journal of Exposure Science & Environmental Epidemiology
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 2017年至2023年美国成年人食物和尿液中氯石倍奎的初步研究 | 《接触科学与环境流行病学杂志》
- en: 来源：[https://www.nature.com/articles/s41370-024-00643-4](https://www.nature.com/articles/s41370-024-00643-4)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.nature.com/articles/s41370-024-00643-4](https://www.nature.com/articles/s41370-024-00643-4)
- en: This is the first report of urinary chlormequat measurements in adults residing
    in the U.S., and any population outside of the United Kingdom and Sweden. A time-course
    of pesticide biomonitoring in over 1000 adolescents from Sweden documented 100
    percent detection frequencies of chlormequat from 2000 to 2017\. The median concentrations
    in 2017 were 0.86 µg chlormequat per g creatinine and appeared to decrease over
    time, the highest median level was 2.77 in 2009 [[16](/articles/s41370-024-00643-4#ref-CR16
    "Noren E, Lindh C, Rylander L, Glynn A, Axelsson J, Littorin M, et al. Concentrations
    and temporal trends in pesticide biomarkers in urine of Swedish adolescents, 2000-2017\.
    J Expo Sci Environ Epidemiol. 2020;30:756–67.")]. In the UK from 2011 to 2012,
    biomonitoring detected much higher median concentrations at 15.1 µg chlormequat
    per g creatinine, and while these samples were collected from people residing
    in an agricultural area, there were no differences in exposure when levels were
    compared before and after chlormequat spray events [[15](/articles/s41370-024-00643-4#ref-CR15
    "Galea KS, MacCalman L, Jones K, Cocker J, Teedon P, Cherrie JW, et al. Urinary
    biomarker concentrations of captan, chlormequat, chlorpyrifos and cypermethrin
    in UK adults and children living near agricultural land. J Expo Sci Environ Epidemiol.
    2015;25:623–31.")]. Compared to these previous studies in Europe, the median levels
    measured in our study of U.S. samples from 2017 to 2022 were lower, while the
    median level in 2023 samples were comparable to samples from Sweden, and lower
    than UK samples (Table [1](/articles/s41370-024-00643-4#Tab1)).
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 这是美国居民和英国、瑞典以外的任何人群中首次报告的尿液氯石倍奎测量结果。瑞典超过1000名青少年的农药生物监测时间表记录了2000年至2017年氯石倍奎的100％检出频率。2017年的中位数浓度为每克肌酐0.86微克氯石倍奎，随着时间的推移似乎有所下降，最高的中位数水平为2009年的2.77
    [[16](/articles/s41370-024-00643-4#ref-CR16 "Noren E, Lindh C, Rylander L, Glynn
    A, Axelsson J, Littorin M, et al. Concentrations and temporal trends in pesticide
    biomarkers in urine of Swedish adolescents, 2000-2017. J Expo Sci Environ Epidemiol.
    2020;30:756–67.")]. 英国2011年至2012年，生物监测检测到中位数浓度明显更高，每克肌酐15.1微克氯石倍奎，虽然这些样本来自居住在农业区的人们，但在比较氯石倍奎喷雾事件之前和之后的水平时，暴露没有差异
    [[15](/articles/s41370-024-00643-4#ref-CR15 "Galea KS, MacCalman L, Jones K, Cocker
    J, Teedon P, Cherrie JW, et al. Urinary biomarker concentrations of captan, chlormequat,
    chlorpyrifos and cypermethrin in UK adults and children living near agricultural
    land. J Expo Sci Environ Epidemiol. 2015;25:623–31.")]. 与先前在欧洲进行的研究相比，我们对美国样本的研究从2017年至2022年的中位水平较低，而2023年样本的中位水平与瑞典的样本相当，并低于英国样本（表[1](/articles/s41370-024-00643-4#Tab1)）。
- en: Differences in exposure between these different regions and time points likely
    reflects differences in agricultural practices and regulatory status of chlormequat,
    ultimately impacting chlormequat levels in the food supply. For instance, the
    significantly higher concentrations of chlormequat in the 2023 urine samples compared
    to earlier years may reflect the likely recent introduction of chlormequat into
    the U.S. food supply due to EPA regulatory action changes involving chlormequat,
    including establishing limits on chlormequat in food in 2018 and raising those
    limits for oats in 2020\. These actions permitted import and sale of agricultural
    products that had been treated with chlormequat, for example from Canada. The
    time-lag between EPA regulatory changes and elevations in chlormequat concentrations
    found in the 2023 urine samples could be explained by several scenarios such as
    delays in adoption of agricultural practices that use chlormequat, delays in U.S.
    companies establishing trade agreements and exhausting old product stocks, and/or
    delays in individuals purchasing oats given the long expiration dates on oat products.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 这些不同地区和时间点的暴露差异可能反映了不同的农业实践和氯石倍奎的监管状况，最终影响了食品供应中的氯石倍奎水平。例如，与早期年份相比，2023年尿液样本中氯石倍奎浓度显著更高，可能反映了最近美国食品供应中氯石倍奎的引入，这是由于EPA对氯石倍奎进行了监管行动变更，包括在2018年设立氯石倍奎在食品中的限制，并在2020年提高了燕麦的限制。这些行动允许进口和销售经过氯石倍奎处理的农产品，例如来自加拿大的产品。
    EPA监管变化与2023年尿液样本中氯石倍奎浓度升高之间的时间延迟可以通过几种情况来解释，例如采用使用氯石倍奎的农业实践的延迟，美国公司建立贸易协议和耗尽旧产品库存的延迟，以及/或者个人购买燕麦的延迟，考虑到燕麦产品的长期有效期。
- en: To determine if the concentrations observed in U.S. urine samples were reflective
    of potential dietary exposure to chlormequat, we measured chlormequat in oat and
    wheat-based food products purchased in the U.S. in 2022 and 2023\. Oat products
    contained chlormequat more frequently than wheat products and the amount of chlormequat
    in different oat products varied, with a median level of 104 ppb, perhaps owing
    to sourcing from the U.S. versus Canada, potentially representing differences
    between products made with or without chlormequat-treated oats. Comparatively,
    in food samples from the United Kingdom, chlormequat is far more prevalent in
    wheat-based products such as bread in which 90% of samples collected in the UK
    between July and September 2022 had detectable levels of chlormequat with a median
    concentration of 60 ppb. Similarly, chlormequat was detected in 82% of UK oat
    samples from the same time with median concentrations of 1650 ppb, more than 15
    times higher than in U.S. samples, which may explain the higher urinary concentrations
    observed in UK samples [[20](/articles/s41370-024-00643-4#ref-CR20 "Department
    for Environment FaRA. Quarter 3 2022 PRIF Report Quartlery Data. United Kingdom
    Department for Environment Food & Rural Affairs2023.")].
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 为了确定美国尿液样本中观察到的浓度是否反映了氯喹潜在的膳食暴露，我们测量了在2022年和2023年购买的美国燕麦和小麦基食品中的氯喹含量。燕麦产品中的氯喹出现频率高于小麦产品，并且不同燕麦产品中的氯喹含量不同，其中位数水平为104 ppb，这可能是因为从美国与加拿大的采购来源不同，可能代表了使用或不使用氯喹处理的燕麦产品之间的差异。相比之下，在英国的食品样本中，氯喹在小麦基食品中更为普遍，例如面包，2022年7月至9月收集的英国样本中有90%的样本检测到了氯喹，中位浓度为60 ppb。同样，相同时间的英国燕麦样本中检测到了82%的样本含有氯喹，中位浓度为1650 ppb，比美国样本高出15倍以上，这可能解释了英国样本中观察到的尿液浓度较高。
- en: 'Our biomonitoring results indicate exposure to chlormequat before 2018, despite
    there being no established food tolerances set for chlormequat. Although there
    is no monitoring of chlormequat in food products in the U.S., and no historical
    data available for concentrations of chlormequat in foods sold in the U.S., we
    suspect these exposures were likely dietary given the short half-life of chlormequat.
    Additionally, natural formation of chlormequat from choline precursors in wheat
    products and egg powder has been shown to occur under high temperatures such as
    those used during food processing and production, resulting in chlormequat concentrations
    between 5 and 40 ng/g [[21](/articles/s41370-024-00643-4#ref-CR21 "Eriksen B,
    Desmarchelier A, Frank N, Stadler RH, Delatour T. Occurrence of the Plant Growth
    Regulator Chlormequat in Food May Be Due to Natural Formation: A Preliminary Mechanistic
    Study. J Agric Food Chem. 2020;68:7727–33.")]. Our food testing results indicate
    chlormequat levels in some samples, including one organic oat-based product, were
    similar to those reported in the study of naturally forming chlormequat, while
    many other samples were higher. Thus, our pre-2023 levels observed in urine could
    be a result of dietary exposure to chlormequat from formation via food processing
    and production. And the 2023 levels observed could be due to a combination of
    dietary exposure to chlormequat from spontaneous formation as well as imported
    products agriculturally treated with chlormequat. Differences in chlormequat exposure
    in our samples could also be due to geographic locations, differing dietary patterns,
    or occupational exposure from uses of chlormequat in greenhouses and nurseries.'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 我们的生物监测结果表明，在2018年之前暴露于氯喹，尽管对氯喹尚未设定食品容许量。尽管在美国没有对食品中的氯喹进行监测，也没有可用于美国销售的食品中氯喹浓度的历史数据，但我们怀疑这些暴露可能是膳食性的，考虑到氯喹的短半衰期。此外，在高温下（例如食品加工和生产过程中使用的温度）已经显示小麦制品和蛋粉中的胆碱前体可能自然形成氯喹，导致氯喹浓度在5到40 ng/g之间。我们的食品测试结果表明，一些样品中的氯喹含量，包括一种有机燕麦制品，与自然形成氯喹的研究中报告的相似，而许多其他样品则更高。因此，我们在尿液中观察到的2023年之前的水平可能是由于食品加工和生产中形成氯喹导致的膳食暴露。而在2023年观察到的水平可能是由于膳食暴露和农业产品使用氯喹的组合引起的。我们样本中氯喹暴露的差异也可能是由于地理位置、不同的饮食模式或在温室和苗圃中使用氯喹的职业暴露所致。
- en: Our study indicates that a greater sample size and more diverse sampling of
    processed foods for chlormequat is needed to fully assess potential dietary sources
    of chlormequat in the low exposure individuals. Future studies that include the
    analysis of historical urine and food samples, dietary and occupational questionnaires,
    and continued monitoring of chlormequat in the U.S. food supply for both conventional
    and organic foods, as well as samples for biomonitoring would help elucidate the
    determinants of total chlormequat exposure in the U.S. population.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 我们的研究表明，需要更大的样本量和更多样化的加工食品样本来充分评估低暴露个体中氯喹的潜在膳食来源。未来的研究应包括历史尿液和食品样本的分析、饮食和职业调查问卷，并继续监测美国传统和有机食品中氯喹的含量，以及生物监测样本，这将有助于阐明美国人口总氯喹暴露的决定因素。
- en: It remains to be determined whether chlormequat levels in U.S. urine and food
    samples may rise in the coming years. In the U.S., chlormequat is currently only
    allowed in imported oat and wheat products, but domestic agricultural uses on
    non-organic crops are currently under review by the U.S. EPA. It is possible that
    if such domestic uses were approved, combined with widespread adoption of agricultural
    practices that utilize chlormequat abroad and domestically, chlormequat levels
    would likely continue to increase in oats, wheat, and other grain foods, leading
    to higher levels of exposure for the U.S. general population.
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: 美国尿液和食品样本中氯喹盐（chlormequat）水平是否会在未来几年上升仍有待确定。目前，在美国，氯喹盐只允许在进口燕麦和小麦产品中使用，但美国国内非有机农作物的农业用途目前正在接受美国环保局的审查。如果这些国内用途得到批准，并且国内外广泛采用利用氯喹盐的农业实践，那么氯喹盐水平很可能会继续在燕麦、小麦和其他谷物食品中上升，从而导致美国普通人口接触量增加。
- en: Current chlormequat concentrations in urine from this study and others suggest
    that individual sample donors were exposed to chlormequat at levels several orders
    of magnitude below the reference dose (RfD) published by the U.S. EPA (0.05 mg/kg
    bw/day) and the acceptable daily intake (ADI) value published by the European
    Food Safety Authority (0.04 mg/kg bw/day). However, we note that published toxicological
    studies on chlormequat suggest reevaluation of these safety thresholds may be
    warranted. For instance, animals exposed to doses lower than the current RfD and
    ADI, of 0.024 and 0.0023 mg/kg bw/day in mice and pigs respectively, exhibited
    reduced fertility [[4](/articles/s41370-024-00643-4#ref-CR4 "Sorensen MT, Danielsen
    V. Effects of the plant growth regulator, chlormequat, on mammalian fertility.
    Int J Androl. 2006;29:129–33.")]. In another toxicological study, exposure during
    pregnancy at a dose equivalent to the No Observed Adverse Effect Level (NOAEL)
    of 5 mg/kg that was used to derive the U.S. EPA reference dose, caused altered
    fetal growth as well as metabolism and body composition in neonatal mice [[9](/articles/s41370-024-00643-4#ref-CR9
    "Xiagedeer B, Hou X, Zhang Q, Hu H, Kang C, Xiao Q, et al. Maternal chlormequat
    chloride exposure disrupts embryonic growth and produces postnatal adverse effects.
    Toxicology. 2020;442:152534.")]. Additionally, the regulatory thresholds do not
    consider the adverse effects of mixtures of chemicals that may impact the reproductive
    system, which have been shown to cause additive or synergistic effects at doses
    lower than for individual chemical exposures [[22](/articles/s41370-024-00643-4#ref-CR22
    "Conley JM, Lambright CS, Evans N, Cardon M, Medlock-Kakaley E, Wilson VS, et
    al. A mixture of 15 phthalates and pesticides below individual chemical no observed
    adverse effect levels (NOAELs) produces reproductive tract malformations in the
    male rat. Environ Int. 2021;156:106615.")], raising concerns about the potential
    health effects associated with current exposure levels, especially for individuals
    on the higher end of exposure in general populations of Europe and the U.S.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 本研究和其他研究中尿液中当前的氯喹盐浓度表明，个体样本供体暴露于远低于美国环保局公布的参考剂量（RfD）（0.05mg/kg bw/day）和欧洲食品安全局公布的可接受每日摄入量（ADI）值（0.04mg/kg
    bw/day）几个数量级的氯喹盐。然而，我们注意到，有关氯喹盐的毒理学研究表明，可能需要重新评估这些安全阈值。例如，动物暴露于低于当前RfD和ADI的剂量时，分别在小鼠和猪中为0.024和0.0023mg/kg
    bw/day，表现出生育能力降低。在另一项毒理学研究中，怀孕期间暴露于相当于用于制定美国环保局参考剂量的5mg/kg的无观察到不良影响水平（NOAEL）的剂量时，导致新生小鼠的胎儿生长以及代谢和体成分发生改变。此外，监管阈值不考虑可能影响生殖系统的化学物混合物的不良影响，这些化学物已被证明在比单个化学物暴露更低的剂量下产生加成或协同作用，引发对欧洲和美国一般人口中暴露水平较高个体的潜在健康影响的担忧。
- en: This pilot investigation into an emerging chemical exposure within the U.S.
    indicates that chlormequat chloride is present in the U.S. food supply, primarily
    in oat-based products, and is detectable in a majority of urine samples collected
    from nearly 100 individuals in the U.S., suggesting continuous exposure. Additionally,
    trends in these data suggest that exposure levels have increased and might continue
    to increase in the future. Given the toxicological concerns associated with chlormequat
    exposure in animal studies, and widespread exposure to the general population,
    in European countries, and now also likely in the U.S., monitoring of chlormequat
    in foods and people, in conjunction with epidemiological and animal studies, is
    urgently needed to understand the potential health harms of this agricultural
    chemical at environmentally relevant exposure levels, particularly during pregnancy.
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 这项针对美国新兴化学物暴露的试点调查表明，氯喹盐氯化物存在于美国食品供应中，主要存在于以燕麦为基础的产品中，并且在近100名美国个体的尿样中被检测到，表明持续暴露。此外，这些数据的趋势表明，暴露水平已经增加，并且未来可能继续增加。鉴于动物研究中与氯喹盐暴露相关的毒理学问题，以及在欧洲国家以及现在很可能在美国广泛暴露于普通人群中，急需监测食品和人体中的氯喹盐，结合流行病学和动物研究，以了解在环境相关暴露水平下这种农业化学品的潜在健康危害，尤其是在怀孕期间。
