- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:39:23'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Conditional Git Configuration - Scott's Weblog - The weblog of an IT pro focusing
    on cloud computing, Kubernetes, Linux, containers, and networking
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://blog.scottlowe.org/2023/12/15/conditional-git-configuration/](https://blog.scottlowe.org/2023/12/15/conditional-git-configuration/)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Conditional Git Configuration
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: '* Published on 15 Dec 2023 · * Filed in [Explanation](/categories/explanation)
    · * 304 words (estimated 2 minutes to read)*** ***Building on the earlier article
    on [automatically transforming Git URLs](/2023/12/11/automatically-transforming-git-urls/),
    I’m back with another article on a (potentially powerful) feature of [Git](https://www.git-scm.com)—the
    ability to conditionally include Git configuration files. This means you can configure
    Git to be configured (and behave) differently based on certain conditions, simply
    by including or not including Git configuration files. Let’s look at a pretty
    straightforward example taken from my own workflow.'
  prefs: []
  type: TYPE_NORMAL
- en: 'Here’s a configuration stanza from my own system-wide Git configuration:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE0]'
  prefs: []
  type: TYPE_PRE
- en: The key here is the `includeIf` keyword. In this case, Git will include the
    referenced configuration file specified by `path`, *if* the location of the Git
    repository matches the path specification after `gitdir`. Basically, what this
    means is that *all* repositories under `~/Work/Code/Repos` will trigger the inclusion
    of the additional configuration file.
  prefs: []
  type: TYPE_NORMAL
- en: 'Here’s the additional configuration file:'
  prefs: []
  type: TYPE_NORMAL
- en: '[PRE1]'
  prefs: []
  type: TYPE_PRE
- en: As long as I group all work-related repositories in the specified directory
    path, these values override the system-wide values. This means I can specify my
    work e-mail address as the e-mail address to be associated with commits to work-related
    repositories while all others use a different e-mail address. This configuration
    also allows me to disable GPG signing of commits for work-related repositories
    (i.e., repositories in the specified path), since I don’t have a GPG key associated
    with my work e-mail address.
  prefs: []
  type: TYPE_NORMAL
- en: Could you do this with per-repository configuration settings? *Absolutely.*
    This configuration mechanism allows you to apply configuration settings to groups
    of repositories based on their filesystem location, instead of having to do the
    same thing on a per-repository basis.
  prefs: []
  type: TYPE_NORMAL
- en: I hope you find this information useful. Do feel free to hit me up—[on the Fediverse](https://fosstodon.org/@scottslowe),
    [on Twitter](https://twitter.com/scott_lowe), or in any of a variety of Slack
    communities—if you have any questions or any feedback!
  prefs: []
  type: TYPE_NORMAL
- en: Metadata and Navigation
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: '* [Git](/tags/git) * [CLI](/tags/cli)'
  prefs: []
  type: TYPE_NORMAL
- en: '*Previous Post: [Automatically Transforming Git URLs](https://blog.scottlowe.org/2023/12/11/automatically-transforming-git-urls/)'
  prefs: []
  type: TYPE_NORMAL
- en: '*Next Post: [Dynamically Enabling the Azure CLI with Direnv](https://blog.scottlowe.org/2023/12/18/dynamically-enabling-azure-cli-with-direnv/)****
    ****Be social and share this post!'
  prefs: []
  type: TYPE_NORMAL
- en: '[](https://www.facebook.com/sharer/sharer.php?u=https%3a%2f%2fblog.scottlowe.org%2f2023%2f12%2f15%2fconditional-git-configuration%2f
    "Share on Facebook")*[](https://plus.google.com/share?url=https%3a%2f%2fblog.scottlowe.org%2f2023%2f12%2f15%2fconditional-git-configuration%2f
    "Share on Google Plus")********'
  prefs: []
  type: TYPE_NORMAL
