- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 14:53:19'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年05月27日 14:53:19
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Environmental and youth groups win climate court case against the Norwegian
    State  - Greenpeace International
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 环保和青年团体赢得针对挪威政府的气候法庭案件 - 绿色和平国际
- en: 来源：[https://www.greenpeace.org/international/press-release/64831/environmental-youth-groups-win-climate-court-case-against-norwegian-state/](https://www.greenpeace.org/international/press-release/64831/environmental-youth-groups-win-climate-court-case-against-norwegian-state/)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://www.greenpeace.org/international/press-release/64831/environmental-youth-groups-win-climate-court-case-against-norwegian-state/](https://www.greenpeace.org/international/press-release/64831/environmental-youth-groups-win-climate-court-case-against-norwegian-state/)
- en: Oslo, Norway – **Greenpeace Nordic and Natur og Ungdom (Young Friends of the
    Earth Norway) secured a historic win against the Norwegian State, rendering the
    approvals of three oil and gas fields in the North Sea invalid.**
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 奥斯陆，挪威 - **绿色和平北欧以及挪威地球之友（Young Friends of the Earth Norway）在与挪威政府的一场历史性胜利中获得了胜利，使北海三个油气田的批准无效。**
- en: In November 2023, environmental organisation Greenpeace Nordic and youth group
    Natur og Ungdom took the Norwegian State to court once again. The organisations
    argued that recent approvals of three new oil and gas fields, Breidablikk, Yggdrasil
    and Tyrving, all in the North Sea, violate the Norwegian Constitution, European
    Economic Area law and Norway’s international human rights commitments. They also
    argued the Ministry of Energy failed to consider the UN Convention on the Rights
    of the Child during the approval of the fields, thus rendering the approvals invalid.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 2023年11月，环境组织绿色和平北欧和青年团体挪威地球之友再次将挪威政府告上法庭。组织辩称，最近批准的三个新油气田，布雷达布利克、伊格德拉西尔和提尔文，都位于北海，违反了挪威宪法、欧洲经济区法律和挪威的国际人权承诺。他们还辩称，能源部在批准这些油田时未考虑联合国《儿童权利公约》，因此使得这些批准无效。
- en: “I am extremely pleased and relieved that the Court has delivered such a positive
    and thorough judgement. The judgement establishes that the Breidablikk, Yggdrasil
    and Tyrving oil and gas fields were approved on an illegal basis and that production
    must be stopped immediately. We expect a halt to all further developments,” said
    **Frode Pleym, Head of Greenpeace, Norway**
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: “我非常高兴和宽慰法院作出了如此积极和彻底的裁决。这一裁决确定布雷达布利克、伊格德拉西尔和提尔文油气田的批准是非法的，生产必须立即停止。我们期待所有进一步的发展都会停止，”**Frode
    Pleym，绿色和平挪威主席**说道。
- en: Specifically, the organisations pointed to the fact that impact assessments
    of the three oil and gas fields’ global climate effects, which the Ministry of
    Energy is required to carry out, are either highly inadequate or non-existent.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: 具体来说，组织指出三个油气田的全球气候影响评估，即能源部需要进行的评估，要么非常不足，要么根本不存在。
- en: The judgement delivered today by the Oslo District Court, has found the approvals
    of all three oil and gas fields invalid and issued an injunction forbidding the
    state from granting any new permits necessary to construct and produce from the
    fields.[1]
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 奥斯陆地方法院今天作出的裁决认定所有三个油气田的批准无效，并下令禁止国家授予任何新的许可证，以便从这些油田中进行建设和生产。[1]
- en: “This is an important victory for current and future generations and the environment.
    With this judgement, millions of barrels of oil will remain in the ground. During
    the trial, the State tried to diminish the impact of the emissions  Breidablikk,
    Tyrving and Yggdrasil would have globally. As confirmed by the court’s decision,
    emissions from the oil fields would have catastrophic effects on the global climate,
    on people and the planet. We are pleased the oil and gas will remain untouched
    in the ground, instead of further exacerbating climate disasters,” said **Gytis
    Blaževičius, Head of Natur og Ungdom.**
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: “这是对当前和未来几代人以及环境的重要胜利。通过这一判决，数百万桶石油将留在地下。在审判期间，国家试图减轻布雷达布利克（Breidablikk）、提尔文（Tyrving）和伊格德拉西尔（Yggdrasil）的排放对全球的影响。正如法院的决定所证实的那样，这些油田的排放将对全球气候、人类和地球产生灾难性影响。我们很高兴石油和天然气将留在地下，而不是进一步加剧气候灾难。”**Gytis
    Blaževičius，挪威地球之友主席**说道。
- en: The Court also emphasised procedural problems of the approval process, highlighting
    the lack of adequate public participation, and found that the approvals were inadequate
    under EU law. and that “combustion emissions [from] petroleum extraction are such
    a significant and particularly characteristic consequence of such projects that
    they must clearly be considered indirect climate impacts within the meaning of
    the (EU) Project Directive”.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 法院还强调了批准流程的程序问题，突出了公众参与不足，并认为批准违反了欧盟法律。并且“石油提取中的燃烧排放是这类项目的重大且特别特征性的后果，因此它们必须明确被视为《(EU)项目指令》中间接气候影响的一部分”。
- en: The Court confirmed that the government violated legal precedent from the Norwegian
    Supreme Court, by not subjecting combustion emissions to an environmental impact
    assessment.
  id: totrans-13
  prefs: []
  type: TYPE_NORMAL
  zh: 法院确认政府违反了挪威最高法院的法律先例，未将燃烧排放物纳入环境影响评估之列。
- en: The Court held that the children’s right to be heard would be safeguarded through
    public hearings that must take place in connection with lawfully required environmental
    impact assessments. Anticipating [clarifications from the Grand Chamber](https://www.greenpeace.org/international/press-release/58956/first-climate-case-heard-at-the-european-court-of-human-rights/)
    of the European Court of Human Rights, the District Court refrained from assessing
    violations of the Convention.
  id: totrans-14
  prefs: []
  type: TYPE_NORMAL
  zh: 法院裁定，孩子们有权发表意见将通过法定所需的环境影响评估进行的公开听证会来保护。挪威最高法院的[大法官室](https://www.greenpeace.org/international/press-release/58956/first-climate-case-heard-at-the-european-court-of-human-rights/)对于迎接的澄清保留了不评估公约违规的地区法院的判断。
- en: More and more people, particularly those most impacted by climate change, are
    using the law to protect their rights from the climate crisis. This ruling becomes
    another substantial reference point for all climate lawsuits pending around the
    world.
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
  zh: 越来越多的人，特别是那些受气候变化影响最严重的人，正在利用法律保护他们免受气候危机的影响。这一裁决成为全球正在进行的所有气候诉讼的另一个重要参考点。
- en: ENDS
  id: totrans-16
  prefs: []
  type: TYPE_NORMAL
  zh: 结束
- en: '[Media briefing: The new climate lawsuit – Greenpeace Norge](https://www.greenpeace.org/norway/nyheter/klimaendringer/media-briefing-the-new-climate-lawsuit/)'
  id: totrans-17
  prefs: []
  type: TYPE_NORMAL
  zh: '[媒体简报：新的气候诉讼 - Greenpeace Norge](https://www.greenpeace.org/norway/nyheter/klimaendringer/media-briefing-the-new-climate-lawsuit/)'
- en: Photos are available in the [Greenpeace Media Library](https://media.greenpeace.org/collection/27MZIFJFQIROK)
  id: totrans-18
  prefs: []
  type: TYPE_NORMAL
  zh: 照片可在[绿色和平媒体库](https://media.greenpeace.org/collection/27MZIFJFQIROK)中找到。
- en: '**Notes:**'
  id: totrans-19
  prefs: []
  type: TYPE_NORMAL
  zh: '**备注：**'
- en: '[1] Specifically, the court ruled that section 20 et seq. of the Petroleum
    Regulations, which provide the requirement on impact assessments, must be interpreted
    in light of Article 112 of the Norwegian Constitution. It referred to the 2020
    Supreme Court decision that found that Article 112 should cover both emissions
    from the production and consumption of petroleum, even if it is combusted outside
    of Norway. The Court found that the State must assess the real impact of both
    forms of greenhouse gas emissions resulting from the development and operation
    of petroleum deposits before approving oil and gas fields and that a real test
    must be carried out of whether approval would be contrary to Article 112 of the
    Norwegian Constitution.'
  id: totrans-20
  prefs: []
  type: TYPE_NORMAL
  zh: '[1] 具体来说，法院裁定，石油法规第20条及其后续条款，即要求进行影响评估的规定，必须根据挪威宪法第112条进行解释。它参考了2020年最高法院的判决，认为第112条应该涵盖石油生产和消费的排放，即使燃烧在挪威以外。法院裁定，国家必须在批准油气田之前评估由石油开发和运营产生的两种温室气体排放的实际影响，并且必须对是否批准违反挪威宪法第112条进行实际测试。'
- en: '**Contacts:**'
  id: totrans-21
  prefs: []
  type: TYPE_NORMAL
  zh: '**联系人：**'
- en: 'Frode Pleym, Head of Greenpeace in Norway: [[email protected]](/cdn-cgi/l/email-protection),
    +47 97 30 73 78'
  id: totrans-22
  prefs: []
  type: TYPE_NORMAL
  zh: Frode Pleym，挪威绿色和平组织负责人：[[email protected]](/cdn-cgi/l/email-protection)，+47
    97 30 73 78
- en: 'Gytis Blaževičius, Head of Natur og Ungdom (Young Friends of the Earth Norway):'
  id: totrans-23
  prefs: []
  type: TYPE_NORMAL
  zh: Gytis Blaževičius，挪威地球之友（Young Friends of the Earth Norway）负责人：
- en: '[[email protected]](/cdn-cgi/l/email-protection) , +47 452 97 542'
  id: totrans-24
  prefs: []
  type: TYPE_NORMAL
  zh: '[[email protected]](/cdn-cgi/l/email-protection)，+47 452 97 542'
- en: 'Greenpeace International Press Desk: [[email protected]](/cdn-cgi/l/email-protection),
    +31 (0) 20 718 2470 (available 24 hours). Follow [@greenpeacepress](https://twitter.com/Greenpeacepress)
    for our latest international press releases.'
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
  zh: 绿色和平国际新闻部：[[email protected]](/cdn-cgi/l/email-protection)，+31 (0) 20 718 2470（24小时服务）。关注[@greenpeacepress](https://twitter.com/Greenpeacepress)获取我们最新的国际新闻稿。
