- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 分类：未分类
- en: 'date: 2024-05-27 14:50:59'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年5月27日14:50:59
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'GitHub - SebastianMuskalla/ModelessVim: Configuration files to turn vim into
    a modeless editor.'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: GitHub - SebastianMuskalla/ModelessVim：将vim配置文件转换为无模式编辑器。
- en: 来源：[https://github.com/SebastianMuskalla/ModelessVim](https://github.com/SebastianMuskalla/ModelessVim)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://github.com/SebastianMuskalla/ModelessVim](https://github.com/SebastianMuskalla/ModelessVim)
- en: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
- en: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># SebastianMuskalla/ModelessVim
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># SebastianMuskalla/ModelessVim
- en: This commit does not belong to any branch on this repository, and may belong
    to a fork outside of the repository.
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 此提交不属于此存储库的任何分支，可能属于存储库外的分支。
- en: <include-fragment src="/SebastianMuskalla/ModelessVim/spoofed_commit_check/23b78d7f8f9936856b1684aa7eed79a0cc098a14"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: <include-fragment src="/SebastianMuskalla/ModelessVim/spoofed_commit_check/23b78d7f8f9936856b1684aa7eed79a0cc098a14"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
- en: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">目前无法执行此操作。
- en: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
