- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 15:02:13'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: NPS Data API (Application Programming Interface) - Digital (U.S. National Park
    Service)
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.nps.gov/subjects/digital/nps-data-api.htm](https://www.nps.gov/subjects/digital/nps-data-api.htm)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: The [NPS Data API](/subjects/developer/index.htm) is open and accessible to
    all developers who wish to use NPS data in their projects.
  prefs: []
  type: TYPE_NORMAL
- en: What's an API?
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: An application programming interface (API) is a set of requirements that allows
    one application to talk to another.
  prefs: []
  type: TYPE_NORMAL
- en: '**The NPS Data API allows official, authoritative data and content to be used
    not only on NPS.gov but also by internal and external developers in apps, maps,
    and websites.** We create the data once but, through the API, it can be used many
    times and in many products—no matter who creates those products.'
  prefs: []
  type: TYPE_NORMAL
- en: What data is available?
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: 'The [NPS API documentation](/subjects/developer/api-documentation.htm) includes
    detailed information about the type of data available, including:'
  prefs: []
  type: TYPE_NORMAL
- en: '**Alerts** - Announcements communicating information about hazardous, potentially
    hazardous, or changing conditions that may affect a visit to a national park'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Articles, People, and Places** - Titles, images, and short descriptions about
    shared content articles'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Campgrounds** - Location, contact, operating hours, site amenities, fee,
    and accessibility information for campgrounds in national parks'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Events** - Date, time, fee, and description of events taking place in national
    parks'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Lesson Plans** - Objectives, grade level, subject, duration, and standards
    information for lesson plans about national parks for teachers to use in their
    classrooms'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**News Releases** - Title, abstract, and link to national park news releases,
    as well as an optional image'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Parks** - Location, contact, operating hours, and entrance fee/pass information
    for each national park, as well as at least five photos of each park'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Visitor Centers** - Location, contact, and operating hours information for
    visitor centers and other visitor contact facilities in national parks'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: How can developers use the API?
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Developers can register for an API key, get familiar with the API request format,
    and review API resources on the [NPS Data API website](/subjects/developer/index.htm).
  prefs: []
  type: TYPE_NORMAL
- en: What's the future of the API?
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Check out the [NPS API roadmap](/subjects/developer/api-roadmap.htm) to find
    out what is in development and being considered for addition next.
  prefs: []
  type: TYPE_NORMAL
