- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
  zh: 类别：未分类
- en: 'date: 2024-05-27 14:47:06'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024年05月27日 14:47:06
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: Towards Modern Development of Cloud Applications | Proceedings of the 19th Workshop
    on Hot Topics in Operating Systems
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 关于云应用现代开发的探索 | 第19届操作系统热点主题研讨会论文集
- en: 来源：[https://dl.acm.org/doi/10.1145/3593856.3595909](https://dl.acm.org/doi/10.1145/3593856.3595909)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://dl.acm.org/doi/10.1145/3593856.3595909](https://dl.acm.org/doi/10.1145/3593856.3595909)
- en: Please download or close your previous search result export first before starting
    a new bulk export.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
  zh: 在开始新的批量导出之前，请先下载或关闭之前的搜索结果导出。
- en: Preview is not available.
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
  zh: 预览不可用。
- en: By clicking download,
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
  zh: 通过点击下载，
- en: '**a status dialog**'
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
  zh: '**一个状态对话框**'
- en: will open to start the export process. The process may take
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
  zh: 将打开以开始导出过程。该过程可能需要
- en: '**a few minutes**'
  id: totrans-11
  prefs: []
  type: TYPE_NORMAL
  zh: '**几分钟**'
- en: but once it finishes a file will be downloadable from your browser. You may
    continue to browse the DL while the export process is in progress.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
  zh: 但一旦完成，您可以从浏览器下载文件。您可以在导出过程进行中继续浏览 DL。
