- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:47:06'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Towards Modern Development of Cloud Applications | Proceedings of the 19th Workshop
    on Hot Topics in Operating Systems
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://dl.acm.org/doi/10.1145/3593856.3595909](https://dl.acm.org/doi/10.1145/3593856.3595909)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Please download or close your previous search result export first before starting
    a new bulk export.
  prefs: []
  type: TYPE_NORMAL
- en: Preview is not available.
  prefs: []
  type: TYPE_NORMAL
- en: By clicking download,
  prefs: []
  type: TYPE_NORMAL
- en: '**a status dialog**'
  prefs: []
  type: TYPE_NORMAL
- en: will open to start the export process. The process may take
  prefs: []
  type: TYPE_NORMAL
- en: '**a few minutes**'
  prefs: []
  type: TYPE_NORMAL
- en: but once it finishes a file will be downloadable from your browser. You may
    continue to browse the DL while the export process is in progress.
  prefs: []
  type: TYPE_NORMAL
