- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:53:32'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: A pilot study of chlormequat in food and urine from adults in the United States
    from 2017 to 2023 | Journal of Exposure Science & Environmental Epidemiology
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.nature.com/articles/s41370-024-00643-4](https://www.nature.com/articles/s41370-024-00643-4)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: This is the first report of urinary chlormequat measurements in adults residing
    in the U.S., and any population outside of the United Kingdom and Sweden. A time-course
    of pesticide biomonitoring in over 1000 adolescents from Sweden documented 100
    percent detection frequencies of chlormequat from 2000 to 2017\. The median concentrations
    in 2017 were 0.86 µg chlormequat per g creatinine and appeared to decrease over
    time, the highest median level was 2.77 in 2009 [[16](/articles/s41370-024-00643-4#ref-CR16
    "Noren E, Lindh C, Rylander L, Glynn A, Axelsson J, Littorin M, et al. Concentrations
    and temporal trends in pesticide biomarkers in urine of Swedish adolescents, 2000-2017\.
    J Expo Sci Environ Epidemiol. 2020;30:756–67.")]. In the UK from 2011 to 2012,
    biomonitoring detected much higher median concentrations at 15.1 µg chlormequat
    per g creatinine, and while these samples were collected from people residing
    in an agricultural area, there were no differences in exposure when levels were
    compared before and after chlormequat spray events [[15](/articles/s41370-024-00643-4#ref-CR15
    "Galea KS, MacCalman L, Jones K, Cocker J, Teedon P, Cherrie JW, et al. Urinary
    biomarker concentrations of captan, chlormequat, chlorpyrifos and cypermethrin
    in UK adults and children living near agricultural land. J Expo Sci Environ Epidemiol.
    2015;25:623–31.")]. Compared to these previous studies in Europe, the median levels
    measured in our study of U.S. samples from 2017 to 2022 were lower, while the
    median level in 2023 samples were comparable to samples from Sweden, and lower
    than UK samples (Table [1](/articles/s41370-024-00643-4#Tab1)).
  prefs: []
  type: TYPE_NORMAL
- en: Differences in exposure between these different regions and time points likely
    reflects differences in agricultural practices and regulatory status of chlormequat,
    ultimately impacting chlormequat levels in the food supply. For instance, the
    significantly higher concentrations of chlormequat in the 2023 urine samples compared
    to earlier years may reflect the likely recent introduction of chlormequat into
    the U.S. food supply due to EPA regulatory action changes involving chlormequat,
    including establishing limits on chlormequat in food in 2018 and raising those
    limits for oats in 2020\. These actions permitted import and sale of agricultural
    products that had been treated with chlormequat, for example from Canada. The
    time-lag between EPA regulatory changes and elevations in chlormequat concentrations
    found in the 2023 urine samples could be explained by several scenarios such as
    delays in adoption of agricultural practices that use chlormequat, delays in U.S.
    companies establishing trade agreements and exhausting old product stocks, and/or
    delays in individuals purchasing oats given the long expiration dates on oat products.
  prefs: []
  type: TYPE_NORMAL
- en: To determine if the concentrations observed in U.S. urine samples were reflective
    of potential dietary exposure to chlormequat, we measured chlormequat in oat and
    wheat-based food products purchased in the U.S. in 2022 and 2023\. Oat products
    contained chlormequat more frequently than wheat products and the amount of chlormequat
    in different oat products varied, with a median level of 104 ppb, perhaps owing
    to sourcing from the U.S. versus Canada, potentially representing differences
    between products made with or without chlormequat-treated oats. Comparatively,
    in food samples from the United Kingdom, chlormequat is far more prevalent in
    wheat-based products such as bread in which 90% of samples collected in the UK
    between July and September 2022 had detectable levels of chlormequat with a median
    concentration of 60 ppb. Similarly, chlormequat was detected in 82% of UK oat
    samples from the same time with median concentrations of 1650 ppb, more than 15
    times higher than in U.S. samples, which may explain the higher urinary concentrations
    observed in UK samples [[20](/articles/s41370-024-00643-4#ref-CR20 "Department
    for Environment FaRA. Quarter 3 2022 PRIF Report Quartlery Data. United Kingdom
    Department for Environment Food & Rural Affairs2023.")].
  prefs: []
  type: TYPE_NORMAL
- en: 'Our biomonitoring results indicate exposure to chlormequat before 2018, despite
    there being no established food tolerances set for chlormequat. Although there
    is no monitoring of chlormequat in food products in the U.S., and no historical
    data available for concentrations of chlormequat in foods sold in the U.S., we
    suspect these exposures were likely dietary given the short half-life of chlormequat.
    Additionally, natural formation of chlormequat from choline precursors in wheat
    products and egg powder has been shown to occur under high temperatures such as
    those used during food processing and production, resulting in chlormequat concentrations
    between 5 and 40 ng/g [[21](/articles/s41370-024-00643-4#ref-CR21 "Eriksen B,
    Desmarchelier A, Frank N, Stadler RH, Delatour T. Occurrence of the Plant Growth
    Regulator Chlormequat in Food May Be Due to Natural Formation: A Preliminary Mechanistic
    Study. J Agric Food Chem. 2020;68:7727–33.")]. Our food testing results indicate
    chlormequat levels in some samples, including one organic oat-based product, were
    similar to those reported in the study of naturally forming chlormequat, while
    many other samples were higher. Thus, our pre-2023 levels observed in urine could
    be a result of dietary exposure to chlormequat from formation via food processing
    and production. And the 2023 levels observed could be due to a combination of
    dietary exposure to chlormequat from spontaneous formation as well as imported
    products agriculturally treated with chlormequat. Differences in chlormequat exposure
    in our samples could also be due to geographic locations, differing dietary patterns,
    or occupational exposure from uses of chlormequat in greenhouses and nurseries.'
  prefs: []
  type: TYPE_NORMAL
- en: Our study indicates that a greater sample size and more diverse sampling of
    processed foods for chlormequat is needed to fully assess potential dietary sources
    of chlormequat in the low exposure individuals. Future studies that include the
    analysis of historical urine and food samples, dietary and occupational questionnaires,
    and continued monitoring of chlormequat in the U.S. food supply for both conventional
    and organic foods, as well as samples for biomonitoring would help elucidate the
    determinants of total chlormequat exposure in the U.S. population.
  prefs: []
  type: TYPE_NORMAL
- en: It remains to be determined whether chlormequat levels in U.S. urine and food
    samples may rise in the coming years. In the U.S., chlormequat is currently only
    allowed in imported oat and wheat products, but domestic agricultural uses on
    non-organic crops are currently under review by the U.S. EPA. It is possible that
    if such domestic uses were approved, combined with widespread adoption of agricultural
    practices that utilize chlormequat abroad and domestically, chlormequat levels
    would likely continue to increase in oats, wheat, and other grain foods, leading
    to higher levels of exposure for the U.S. general population.
  prefs: []
  type: TYPE_NORMAL
- en: Current chlormequat concentrations in urine from this study and others suggest
    that individual sample donors were exposed to chlormequat at levels several orders
    of magnitude below the reference dose (RfD) published by the U.S. EPA (0.05 mg/kg
    bw/day) and the acceptable daily intake (ADI) value published by the European
    Food Safety Authority (0.04 mg/kg bw/day). However, we note that published toxicological
    studies on chlormequat suggest reevaluation of these safety thresholds may be
    warranted. For instance, animals exposed to doses lower than the current RfD and
    ADI, of 0.024 and 0.0023 mg/kg bw/day in mice and pigs respectively, exhibited
    reduced fertility [[4](/articles/s41370-024-00643-4#ref-CR4 "Sorensen MT, Danielsen
    V. Effects of the plant growth regulator, chlormequat, on mammalian fertility.
    Int J Androl. 2006;29:129–33.")]. In another toxicological study, exposure during
    pregnancy at a dose equivalent to the No Observed Adverse Effect Level (NOAEL)
    of 5 mg/kg that was used to derive the U.S. EPA reference dose, caused altered
    fetal growth as well as metabolism and body composition in neonatal mice [[9](/articles/s41370-024-00643-4#ref-CR9
    "Xiagedeer B, Hou X, Zhang Q, Hu H, Kang C, Xiao Q, et al. Maternal chlormequat
    chloride exposure disrupts embryonic growth and produces postnatal adverse effects.
    Toxicology. 2020;442:152534.")]. Additionally, the regulatory thresholds do not
    consider the adverse effects of mixtures of chemicals that may impact the reproductive
    system, which have been shown to cause additive or synergistic effects at doses
    lower than for individual chemical exposures [[22](/articles/s41370-024-00643-4#ref-CR22
    "Conley JM, Lambright CS, Evans N, Cardon M, Medlock-Kakaley E, Wilson VS, et
    al. A mixture of 15 phthalates and pesticides below individual chemical no observed
    adverse effect levels (NOAELs) produces reproductive tract malformations in the
    male rat. Environ Int. 2021;156:106615.")], raising concerns about the potential
    health effects associated with current exposure levels, especially for individuals
    on the higher end of exposure in general populations of Europe and the U.S.
  prefs: []
  type: TYPE_NORMAL
- en: This pilot investigation into an emerging chemical exposure within the U.S.
    indicates that chlormequat chloride is present in the U.S. food supply, primarily
    in oat-based products, and is detectable in a majority of urine samples collected
    from nearly 100 individuals in the U.S., suggesting continuous exposure. Additionally,
    trends in these data suggest that exposure levels have increased and might continue
    to increase in the future. Given the toxicological concerns associated with chlormequat
    exposure in animal studies, and widespread exposure to the general population,
    in European countries, and now also likely in the U.S., monitoring of chlormequat
    in foods and people, in conjunction with epidemiological and animal studies, is
    urgently needed to understand the potential health harms of this agricultural
    chemical at environmentally relevant exposure levels, particularly during pregnancy.
  prefs: []
  type: TYPE_NORMAL
