- en: <!--yml
  id: totrans-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:30:26'
  id: totrans-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-3
  prefs: []
  type: TYPE_NORMAL
- en: 'CheerpJ 3.0 now available: A WebAssembly JVM to run real-world applications
    in the browser'
  id: totrans-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://labs.leaningtech.com/blog/cheerpj-3.0](https://labs.leaningtech.com/blog/cheerpj-3.0)
  id: totrans-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: CheerpJ 3.0, **a state-of-the-art WebAssembly JVM that runs in the browser**,
    is now available! In this post, we’ll give an overview of what CheerpJ is, what
    this new major release brings, and share an exciting demo we’ve been working on.
  id: totrans-6
  prefs: []
  type: TYPE_NORMAL
- en: CheerpJ 3.0 replaces CheerpJ 2.3 as our long-term supported version. Existing
    users can upgrade by following [the migration guide](/cheerpj3/migrating-from-cheerpj2).
  id: totrans-7
  prefs: []
  type: TYPE_NORMAL
- en: '* * *'
  id: totrans-8
  prefs: []
  type: TYPE_NORMAL
- en: CheerpJ 3.0 is a **full re-write** of CheerpJ that draws from the lessons learned
    from 7 years of enterprise and community use of the tool, as well as from several
    of our other WebAssembly-based projects, particularly [CheerpX](/cheerpx), an
    x86-to-WebAssembly virtualization solution.
  id: totrans-9
  prefs: []
  type: TYPE_NORMAL
- en: We believe that this release brings a new era for deploying large scale Java
    applications on the Web, and for integrating Java libraries into Web apps. This
    is a moment of great pride for us at Leaning Technologies, and is the culmination
    of two years of extremely focused work on the new CheerpJ 3.0 architecture.
  id: totrans-10
  prefs: []
  type: TYPE_NORMAL
- en: What is CheerpJ?[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#what-is-cheerpj)
  id: totrans-11
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: CheerpJ is a full WebAssembly-based JVM replacement for the browser, and comes
    with a complete OpenJDK runtime. Thanks to multiple architectural innovations
    CheerpJ is now an extremely powerful tool, designed to work at the scale of real-world
    Enterprise applications.
  id: totrans-12
  prefs: []
  type: TYPE_NORMAL
- en: '![](img/6960788f1cb5155cabef49e110edf2be.png)'
  id: totrans-13
  prefs: []
  type: TYPE_IMG
- en: Features[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#features)
  id: totrans-14
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: 'CheerpJ’s main capabilities are:'
  id: totrans-15
  prefs: []
  type: TYPE_NORMAL
- en: '**Running large-scale unmodified Java applications on modern browsers without
    plugins or a Java installation**. Legacy Java Applets and Java Web Start applications
    are supported as well. CheerpJ is a modern HTML5 solution based on secure and
    standard Web technologies available in all browsers.'
  id: totrans-16
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**No server side component** is required. All the code is run on the client
    via WebAssembly and JavaScript.'
  id: totrans-17
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Works from unmodified JAR files (no need for source code)**, no need for
    any compilation or preprocessing step. Works with obfuscated bytecode, independently
    of the obfuscator being used.'
  id: totrans-18
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Supports *very large* applications**, our stress test is IntelliJ IDEA 2019
    which ships ~400MBs of JARs. [Check it out.![](img/d33c4c2b3b320e4a308682879c95389b.png)](https://twitter.com/alexpignotti/status/1729915428258926713)'
  id: totrans-19
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Supports graphical applications**, both AWT- and Swing-based ones are supported,
    including third-party Look&Feels. Multiple applications, each with multiple windows,
    can run at the same time.'
  id: totrans-20
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Full support for reflection and classloaders**, including custom ones designed
    to support plugins or encrypted JARs.'
  id: totrans-21
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Powerful interoperability with JavaScript**'
  id: totrans-22
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '[Library mode](/cheerpj3/guides/library-mode): A new solution to integrate
    Java libraries into Web applications using a clean `async`/`await` interface'
  id: totrans-23
  prefs:
  - PREF_IND
  - PREF_UL
  type: TYPE_NORMAL
- en: '[JavaScript natives](/cheerpj3/guides/Implementing-Java-native-methods-in-JavaScript),
    where you can implement Java `native` methods (JNI) directly in JavaScript with
    a convenient interface. This feature can also be used to interact with JavaScript
    and DOM APIs from Java.'
  id: totrans-24
  prefs:
  - PREF_IND
  - PREF_UL
  type: TYPE_NORMAL
- en: In short, CheerpJ 3.0 can run most Java applications and libraries in the browser
    without any additional work or changes to the code.
  id: totrans-25
  prefs: []
  type: TYPE_NORMAL
- en: What’s the catch?[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#whats-the-catch)
  id: totrans-26
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: CheerpJ 3.0 only supports Java 8\. However, a major motivation for the new architecture
    was to support multiple Java versions, and multiple runtime environments. We plan
    to introduce support for more modern Java LTS versions later this year, starting
    from Java 11\. In the long term, we aim to reach parity with the most recent Java
    LTS version.
  id: totrans-27
  prefs: []
  type: TYPE_NORMAL
- en: CheerpJ is a commercial product and professionally supported, but it’s also
    free for personal use. View [licensing](/cheerpj3/licensing) for more details.
  id: totrans-28
  prefs: []
  type: TYPE_NORMAL
- en: How it works[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#how-it-works)
  id: totrans-29
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: '![](img/1e777ecd683e97a22dddb41cc6654f42.png)'
  id: totrans-30
  prefs: []
  type: TYPE_IMG
- en: CheerpJ 3.0 is a WebAssembly Java Virtual Machine for the browser, which JIT-compiles
    Java bytecode into JavaScript.
  id: totrans-31
  prefs: []
  type: TYPE_NORMAL
- en: 'It is a sophisticated tool with many moving parts, the main ones being:'
  id: totrans-32
  prefs: []
  type: TYPE_NORMAL
- en: A WebAssembly **JVM and Just-In-Time compiler** for Java bytecode. The code
    contained in class files is dynamically compiled and optimized. The JIT compiler
    supports advanced optimizations such as inlining and dynamic devirtualization.
  id: totrans-33
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: A complete and unmodified build of **OpenJDK.**
  id: totrans-34
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**A Virtualized system layer, including:**'
  id: totrans-35
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '[Virtualized file systems](/cheerpj3/guides/File-System-support), providing
    access to assets over HTTP, local persistent R/W storage via IndexedDB and interaction
    with JavaScript data via `/str/`.'
  id: totrans-36
  prefs:
  - PREF_IND
  - PREF_UL
  type: TYPE_NORMAL
- en: '[Virtualized networking](/cheerpj3/guides/Networking) support via Tailscale.
    Both server and client applications are supported.'
  id: totrans-37
  prefs:
  - PREF_IND
  - PREF_UL
  type: TYPE_NORMAL
- en: Readers familiar with the previous CheerpJ 2.3 architecture will notice the
    lack of AOT compilation, which has been removed in CheerpJ 3.0\. The performance
    impact of this change has been vastly positive in all real-world applications
    tested, with a particular benefit in the reduction of startup time.
  id: totrans-38
  prefs: []
  type: TYPE_NORMAL
- en: For more details, we recently published [a blog post diving deep into CheerpJ
    3.0’s architecture](/blog/cheerpj-3-deep-dive). You can also read the [architecture
    page](/cheerpj3/explanation/architecture) in the CheerpJ documentation.
  id: totrans-39
  prefs: []
  type: TYPE_NORMAL
- en: 'Demo: Minecraft[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#demo-minecraft)'
  id: totrans-40
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: </blog/cheerpj-3.0-browsercraft.mp4>
  id: totrans-41
  prefs: []
  type: TYPE_NORMAL
- en: To showcase the capabilities of CheerpJ 3.0, we have released [a fully browser-based
    demo of Minecraft![](img/d33c4c2b3b320e4a308682879c95389b.png)](https://browsercraft.cheerpj.com),
    probably one of the most well-known Java applications in the world. This experiment
    demonstrates how the capabilities of CheerpJ can be used to run real world applications
    as Web apps.
  id: totrans-42
  prefs: []
  type: TYPE_NORMAL
- en: We call this project “**Browsercraft**.”
  id: totrans-43
  prefs: []
  type: TYPE_NORMAL
- en: Browsercraft and CheerpJ are not official Minecraft products. They are not approved
    by or associated with Mojang or Microsoft.
  id: totrans-44
  prefs: []
  type: TYPE_NORMAL
- en: '**Unmodified JAR file**: CheerpJ can run the JAR file exactly as provided by
    Mojang. No decompilation or modification is required. As a matter of fact the
    JAR is downloaded from Mojang servers by the end-user’s browser (via `fetch`)
    and then stored locally in the `/files/` filesystem. We don’t host or redistribute
    the JAR in any way.'
  id: totrans-45
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Persistent data**: Minecraft will generate a “World” which is saved on the
    persistent local filesystem. If you reload the tab you will be able to continue
    playing from the same world.'
  id: totrans-46
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**JavaScript natives**: The main difficulties in running Minecraft do not come
    from its Java bytecode, but from the native code shipped as part of the Open Source
    LWJGL library. For this demo we have implemented a subset of the LWJGL functionalities
    on top of WebGL using the [JavaScript natives](/cheerpj3/guides/Implementing-Java-native-methods-in-JavaScript)
    feature.'
  id: totrans-47
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Networking**: Although not shown in the current demo, thanks to Tailscale
    networking it will be possible for multiple users to join the same minecraft world
    from their browser tab.'
  id: totrans-48
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: CheerpJ can run Minecraft code without any issues, but further work will be
    required to fully support LWJGL and achieve correct rendering. The implementation
    is sufficient to get in-game, but it’s not complete and a keen eye will notice
    that the rendering is not currently accurate. We welcome user contributions to
    improve the LWJGL implementation to run Minecraft in the browser in all its glory.
    [The source code is available on GitHub![](img/d33c4c2b3b320e4a308682879c95389b.png)](https://github.com/leaningtech/browsercraft).
  id: totrans-49
  prefs: []
  type: TYPE_NORMAL
- en: Other objectives for this project include multiplayer support and running a
    more modern version of Minecraft; for the sake of this demo we are using version
    1.2.5\. CheerpJ currently only supports Java 8, so we could at best reach version
    1.16.5\. More recent versions will need to wait for Java 11+ support, coming later
    in the year.
  id: totrans-50
  prefs: []
  type: TYPE_NORMAL
  zh: 本项目的其他目标包括多人支持以及运行更现代化版本的Minecraft；在此演示中，我们使用的是1.2.5版本。目前CheerpJ仅支持Java 8，所以我们最多能达到1.16.5版本。更新版本将等待Java
    11+的支持，预计将在年底推出。
- en: 'If you’re interested in contributing, or just curious, visit the [repository![](img/d33c4c2b3b320e4a308682879c95389b.png)](https://github.com/leaningtech/browsercraft)
    and join [the #browsercraft channel in our Discord server![](img/d33c4c2b3b320e4a308682879c95389b.png)](https://discord.leaningtech.com).'
  id: totrans-51
  prefs: []
  type: TYPE_NORMAL
  zh: 如果您对贡献感兴趣，或者只是好奇，请访问[存储库！[](img/d33c4c2b3b320e4a308682879c95389b.png)](https://github.com/leaningtech/browsercraft)，并加入我们的Discord服务器中的＃browsercraft频道！[](img/d33c4c2b3b320e4a308682879c95389b.png)(https://discord.leaningtech.com)。
- en: Get started[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#get-started)
  id: totrans-52
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 开始[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#get-started)
- en: CheerpJ is [free to use for personal projects and technical evaluation](/cheerpj3/licensing).
    Integrating it in a page can be done in two steps.
  id: totrans-53
  prefs: []
  type: TYPE_NORMAL
  zh: CheerpJ 可以 [免费用于个人项目和技术评估](/cheerpj3/licensing)。将其集成到页面中只需两个步骤。
- en: 1\. Add the loader[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#1-add-the-loader)
  id: totrans-54
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
  zh: 1\. 添加加载器[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#1-add-the-loader)
- en: '[PRE0]'
  id: totrans-55
  prefs: []
  type: TYPE_PRE
  zh: '[PRE0]'
- en: 2\. Initialize the virtual machine[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#2-initialize-the-virtual-machine)
  id: totrans-56
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
  zh: 2\. 初始化虚拟机[![](img/f1580f6559c1a55793afe9e81eee6923.png)](#2-initialize-the-virtual-machine)
- en: CheerpJ is [extensively documented](/cheerpj3), ranging from basic tutorials
    to the detailed API reference.
  id: totrans-57
  prefs: []
  type: TYPE_NORMAL
  zh: CheerpJ 的文档 [详尽而全面](/cheerpj3)，涵盖从基础教程到详细的API参考。
- en: '[Get started](/cheerpj3/getting-started) [Migration guide](/cheerpj3/migrating-from-cheerpj2)'
  id: totrans-58
  prefs: []
  type: TYPE_NORMAL
  zh: '[开始](/cheerpj3/getting-started) [迁移指南](/cheerpj3/migrating-from-cheerpj2)'
- en: For questions, discussion, and support, [join our Discord![](img/d33c4c2b3b320e4a308682879c95389b.png)](https://discord.leaningtech.com).
    It’s an active community where both Leaning Technologies developers and experienced
    users can provide help.
  id: totrans-59
  prefs: []
  type: TYPE_NORMAL
  zh: 如有问题、讨论和支持，请加入我们的Discord！[](img/d33c4c2b3b320e4a308682879c95389b.png)(https://discord.leaningtech.com)。这是一个活跃的社区，Leaning
    Technologies的开发人员和经验丰富的用户都可以提供帮助。
- en: '* * *'
  id: totrans-60
  prefs: []
  type: TYPE_NORMAL
  zh: '* * *'
- en: CheerpJ is a product built with passion and a lot of coffee by Leaning Technologies,
    an international team of WebAssembly hackers based in Amsterdam (NL) and Leeds
    (UK). We hope you’ll find it as exciting as we do.
  id: totrans-61
  prefs: []
  type: TYPE_NORMAL
  zh: CheerpJ 是由位于阿姆斯特丹（荷兰）和利兹（英国）的国际化WebAssembly黑客团队Leaning Technologies激情和大量咖啡构建的产品。我们希望您会像我们一样感到兴奋。
- en: '[Star CheerpJ on GitHub](https://github.com/leaningtech/cheerpj-meta)'
  id: totrans-62
  prefs: []
  type: TYPE_NORMAL
  zh: '[Star CheerpJ on GitHub](https://github.com/leaningtech/cheerpj-meta)'
