- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:34:26'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: EDE - light and fast desktop environment
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://edeproject.org/](https://edeproject.org/)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: EDE is small desktop environment built to be responsive, light in resource usage
    and to have familiar look and feel. It runs on Linux, *BSD, Solaris, Minix, Zaurus
    and even on XBox.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: '[Download version 2.1](/wiki/Download)'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: or you can [browse](http://sourceforge.net/projects/ede/files) for older releases.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
