- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:34:26'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: EDE - light and fast desktop environment
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://edeproject.org/](https://edeproject.org/)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: EDE is small desktop environment built to be responsive, light in resource usage
    and to have familiar look and feel. It runs on Linux, *BSD, Solaris, Minix, Zaurus
    and even on XBox.
  prefs: []
  type: TYPE_NORMAL
- en: '[Download version 2.1](/wiki/Download)'
  prefs: []
  type: TYPE_NORMAL
- en: or you can [browse](http://sourceforge.net/projects/ede/files) for older releases.
  prefs: []
  type: TYPE_NORMAL
