- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:51:03'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Feds will stop investing in 'large' road projects, environment minister says
    | CBC News
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.cbc.ca/news/politics/guilbeault-no-new-roads-1.7114867](https://www.cbc.ca/news/politics/guilbeault-no-new-roads-1.7114867)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Environment Minister Steven Guilbeault said Monday the federal government will
    stop investing in new road infrastructure — a comment that immediately drew attacks
    from the Opposition Conservatives and some premiers who said the climate activist
    turned politician is out of touch.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: Guilbeault later clarified his remarks, telling reporters Wednesday that he
    meant to say Ottawa will not put up the cash for "large" road projects.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: '"Of course we''re funding roads. We have programs to fund roads," he said.'
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: Guilbeault said Monday the federal government will be there to support provinces
    paying for maintenance but Ottawa has decided that existing road infrastructure
    "is perfectly adequate to respond to the needs we have."
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: '"There will be no more envelopes from the federal government to enlarge the
    road network," Guilbeault said, according to quotes published in the Montreal
    Gazette.'
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: '"We can very well achieve our goals of economic, social and human development
    without more enlargement of the road network."'
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: Guilbeault said the federal government is intent on moving people out of their
    cars and into public transportation, which the government has spent billions to
    build.
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: He said the federal government also wants to encourage "active transit," which
    means getting people to walk and cycle.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: The minister said federal money that's been spent on asphalt and concrete for
    roads in the past is "better invested into projects that will help fight climate
    change and adapt to its impacts."
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
- en: No funding for 'large projects'
  id: totrans-split-15
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Pressed by reporters to defend his comments Wednesday, Guilbeault said he should
    have been "more specific" by stating that the federal government will not be funding
    "large projects."
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
- en: He cited Quebec City's long-proposed [third link](https://www.cbc.ca/news/canada/montreal/quebec-third-link-public-transit-1.6814960)
    as one project that will not receive funding from Ottawa.
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: '"What we have said, and maybe I should have been more specific, is that we
    don''t have funds for large projects like the ''[3eme lien](https://www.cbc.ca/news/canada/montreal/quebec-third-link-public-transit-1.6814960)''
    that the CAQ has been trying to do for many years," he said of Quebec''s provincial
    government.'
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
- en: '***WATCH | Guilbeault faces backlash over road funding comment: *** ### Environment
    minister faces backlash over road funding comments'
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
- en: After a Quebec newspaper reported that Environment Minister Steven Guilbeault
    said the federal government would stop investing in new road infrastructure, the
    minister later clarified he was referring to a particularly large project in Quebec
    City. But the political uproar over the initial comment had already started.
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
- en: A senior government official told CBC News said "there are no changes to federal
    policy."
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
- en: In question period, Prime Minister Justin Trudeau said the government will continue
    to invest in "infrastructure."
  id: totrans-split-22
  prefs: []
  type: TYPE_NORMAL
- en: Asked if he'd condemn Guilbeault's assertion that the federal government is
    getting out of the business of funding some road projects, Trudeau said the minister
    "clarified" his remarks earlier and the government's "approach to infrastructure
    continues to be one of investing in the future for Canadians."
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
- en: Trudeau defended the government's record on infrastructure, saying Ottawa has
    helped fund the Champlain bridge in Montreal, the planned Gordie Howe bridge in
    Windsor and the twinning of the Trans-Canada highway in Newfoundland, among other
    projects.
  id: totrans-split-24
  prefs: []
  type: TYPE_NORMAL
- en: The government has spent hefty sums on roads in the past.
  id: totrans-split-25
  prefs: []
  type: TYPE_NORMAL
- en: The "gas tax fund," which was rebranded by the Liberals as [the Canada Community-Building
    Fund](https://www.infrastructure.gc.ca/plan/gtf-fte-eng.html), has routinely delivered
    billions of dollars to provinces and municipalities to support construction and
    maintenance of highways and local roads and bridges.
  id: totrans-split-26
  prefs: []
  type: TYPE_NORMAL
- en: Conservative Leader Pierre Poilievre said Guilbeault's a "radical" who seems
    intent on banning federal funds from road projects.
  id: totrans-split-27
  prefs: []
  type: TYPE_NORMAL
- en: Conservative MP Mark Strahl, the party's transport critic, said Guilbeault's talk
    about no more new funding for "large" roads is "outrageous" and an affront to
    the people who rely on cars to get to and from work.
  id: totrans-split-28
  prefs: []
  type: TYPE_NORMAL
- en: '"This isn''t something many Canadians do without. To simply say we''re not
    going to allow any federal money to go into that is extreme, it''s divisive and
    it''s right in line with what this government does," Strahl said.'
  id: totrans-split-29
  prefs: []
  type: TYPE_NORMAL
- en: '"But we should expect that from a guy who [scaled the CN Tower](https://www.cbc.ca/news/canada/greenpeace-activists-scale-cn-tower-1.262071),
    [climbed on top of a premier''s house](https://www.cbc.ca/news/canada/edmonton/greenpeace-installs-solar-panels-on-premier-s-roof-1.320610)
    and was led away in handcuffs. That''s the kind of extremism that he''s about,"
    Strahl said, referring to Guilbeault''s past activism, which led to arrests for
    stunts.'
  id: totrans-split-30
  prefs: []
  type: TYPE_NORMAL
- en: Guilbeault, second from right, scaled the CN Tower in Toronto in 2001 to protest
    Canada's environmental policies. He was arrested for the stunt. (Aaron Harris/The
    Canadian Press)
  id: totrans-split-31
  prefs: []
  type: TYPE_NORMAL
- en: Alberta Premier Danielle Smith, a frequent critic of Guilbeault, pounced on
    the remarks, saying in a social media post that the Montreal cabinet minister
    doesn't understand that many Canadians live in suburban, rural and remote areas
    where transit isn't as well-developed.
  id: totrans-split-32
  prefs: []
  type: TYPE_NORMAL
- en: '"Most of us can''t just head out the door in the snow and rain and just walk
    10 kilometres to work each day," Smith said.'
  id: totrans-split-33
  prefs: []
  type: TYPE_NORMAL
- en: At an unrelated press conference about tourism in Alberta, Smith said Wednesday
    that Guilbeault is "tone deaf."
  id: totrans-split-34
  prefs: []
  type: TYPE_NORMAL
- en: '"He''s losing credibility every single day. I don''t know why his caucus and
    his cabinet is putting up with it — that''s something they will have to deal with
    internally," she said.'
  id: totrans-split-35
  prefs: []
  type: TYPE_NORMAL
- en: Ontario Premier Doug Ford is another premier who has had choice words for Guilbeault
    in the past — he's called Guilbeault "[a real piece of work](https://www.thestar.com/politics/provincial/doug-ford-calls-federal-environment-minister-a-real-piece-of-work/article_dcd84801-737c-5c0d-abc5-7c03d7118bd1.html)"
    and an "[extremist](https://www.thestar.com/politics/federal/doug-ford-accuses-extremist-federal-environment-minister-of-stalling-highway-413-project/article_445871be-71fa-5d74-aa1a-bc9cf4088376.html#:~:text=Ford%20said%20it%20was%20%E2%80%9Cshocking,%E2%80%9Chandcuffs%20himself%20to%20trains.%E2%80%9D)."
    Ford said Wednesday he was "gobsmacked" by Guilbeault's latest policy pronouncement.
  id: totrans-split-36
  prefs: []
  type: TYPE_NORMAL
- en: '"A federal minister said they won''t invest in new roads or highways," Ford
    said in a social media post.'
  id: totrans-split-37
  prefs: []
  type: TYPE_NORMAL
- en: '"He doesn''t care that you''re stuck in bumper-to-bumper traffic. I do. We''re
    building roads and highways, with or without a cent from the feds."'
  id: totrans-split-38
  prefs: []
  type: TYPE_NORMAL
- en: '***WATCH: Canada aims to phase out sales of gas-powered cars and trucks by
    2035:***  ### Canada''s plan to phase out gas-powered car and truck sales by 2035'
  id: totrans-split-39
  prefs: []
  type: TYPE_NORMAL
- en: The federal government is laying out its final plan to phase out new, gas-powered
    passenger vehicles by 2035, with gradually increasing targets for manufacturers
    to meet.
  id: totrans-split-40
  prefs: []
  type: TYPE_NORMAL
- en: Guilbeault's comments put into question the future of Ford's promised Highway
    413 project, a new highway in the northwest part of the Greater Toronto Area that
    will connect two major arteries in the area and ease travel between booming areas
    like Vaughan and Brampton.
  id: totrans-split-41
  prefs: []
  type: TYPE_NORMAL
- en: Ontario has argued that the project should be fast-tracked because the population
    growth in these Toronto suburbs demands more infrastructure to ease congestion.
  id: totrans-split-42
  prefs: []
  type: TYPE_NORMAL
- en: Environmentalists and some local groups have vigorously opposed the 60-kilometre
    highway because it will cut through farmland and waterways and pave over parts
    of the province's protected greenbelt.
  id: totrans-split-43
  prefs: []
  type: TYPE_NORMAL
- en: Lengthy review
  id: totrans-split-44
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: In that context, the federal government decided in 2021 that the project should
    be subjected to Ottawa's impact assessment, which means it will go through a more
    stringent and lengthy environmental review.
  id: totrans-split-45
  prefs: []
  type: TYPE_NORMAL
- en: The Impact Assessment Agency of Canada, which carries out these reviews, reports
    to Guilbeault.
  id: totrans-split-46
  prefs: []
  type: TYPE_NORMAL
- en: Late last year, Ford said if Brampton Liberal MPs don't support the project,
    they risk losing their jobs in the next election because voters there want to
    see highways like this built.
  id: totrans-split-47
  prefs: []
  type: TYPE_NORMAL
- en: '"Just look at what happened when Highway 413 worked out for the Liberal and
    NDP candidates right here in Brampton — they all got swept because they didn''t
    agree with 413," he said, referring to his party''s victory in the 2022 provincial
    election.'
  id: totrans-split-48
  prefs: []
  type: TYPE_NORMAL
- en: Mixed record in the courts
  id: totrans-split-49
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Guilbeault has pursued an ambitious climate agenda since taking the job in 2021\.
    He's a keen proponent of the plan to [hike the federal carbon tax](https://www.cbc.ca/news/politics/carbon-tax-hike-new-climate-plan-1.5837709)
    to discourage the use of fossil fuels like oil and gas and he's the lead minister
    on the push to green the country's electricity grid.
  id: totrans-split-50
  prefs: []
  type: TYPE_NORMAL
- en: Guilbeault's clean electricity draft regulations require that the country's
    grid be [net-zero by 2035](https://www.canada.ca/en/services/environment/weather/climatechange/climate-plan/clean-electricity-regulation.html).
    That's a tall order for provinces like Alberta and Saskatchewan where [coal](https://www.saskpower.com/Our-Power-Future/Our-Electricity/Electrical-System/Balancing-Supply-Options/Coal#:~:text=We%20have%203%20power%20plant,of%20the%20world's%20power%20companies.)
    and [natural gas are key fuel sources](https://www.reuters.com/world/americas/alberta-minister-fears-electricity-shortfalls-after-grid-strain-2024-01-15/#:~:text=Alberta%20generates%20most%20of%20its,of%20Alberta's%20average%20electricity%20demand.) for
    power generation.
  id: totrans-split-51
  prefs: []
  type: TYPE_NORMAL
- en: The premiers of those provinces have called the measure an act of jurisdictional
    overreach on Ottawa's part and have [vowed to fight](https://lethbridgenewsnow.com/2023/11/28/saskatchewan-starts-tribunal-to-review-ottawas-clean-electricity-regulations/#:~:text=The%20regulations%20would%20require%20provinces,injunction%20application%20in%20the%20future.) it.
  id: totrans-split-52
  prefs: []
  type: TYPE_NORMAL
- en: Part of a carbon capture and storage facility is pictured at the Boundary Dam
    Power Station (background) in Estevan, Sask. The power station is fueled by coal.
    (Michael Bell/Canadian Press)
  id: totrans-split-53
  prefs: []
  type: TYPE_NORMAL
- en: The government's climate agenda has a mixed record in the courts.
  id: totrans-split-54
  prefs: []
  type: TYPE_NORMAL
- en: The Supreme Court of Canada [upheld the Liberal carbon pricing scheme](https://www.cbc.ca/news/politics/supreme-court-federal-carbon-tax-constitutional-case-1.5962687).
  id: totrans-split-55
  prefs: []
  type: TYPE_NORMAL
- en: But in a 2023 reference case, the top court found the government's impact assessment
    bill — which gives Ottawa the authority to review projects like Highway 413 —
    was largely [unconstitutional](https://www.cbc.ca/news/canada/calgary/supreme-court-richard-wagner-impact-assessment-act-1.6993720).
  id: totrans-split-56
  prefs: []
  type: TYPE_NORMAL
- en: The court said many provisions of [Bill C-69](https://www.cbc.ca/news/politics/tasker-c-69-senate-environmental-assessment-1.5057312)
    gave Ottawa powers that were too broad and not linked closely enough to what the
    Constitution calls federal business.
  id: totrans-split-57
  prefs: []
  type: TYPE_NORMAL
- en: A reference case is not legally binding, but the decision did force Ottawa to
    consider that ruling when crafting its [cap on oil and gas emissions](https://cbc.ca/news/politics/liberal-government-unveils-oil-gas-cap-1.7051803).
  id: totrans-split-58
  prefs: []
  type: TYPE_NORMAL
- en: As for the government's push to ban single-use plastics by deeming them "toxic,"
    the Federal Court ruled last year that the policy is "unreasonable and unconstitutional."
  id: totrans-split-59
  prefs: []
  type: TYPE_NORMAL
