- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 14:51:05'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 日期：2024-05-27 14:51:05
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'GitHub - traceloop/openllmetry-js: Sister project to OpenLLMetry, but in Typescript.
    Open-source observability for your LLM application, based on OpenTelemetry'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 'GitHub - traceloop/openllmetry-js: Sister project to OpenLLMetry, but in Typescript.
    Open-source observability for your LLM application, based on OpenTelemetry'
- en: 来源：[https://github.com/traceloop/openllmetry-js](https://github.com/traceloop/openllmetry-js)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://github.com/traceloop/openllmetry-js](https://github.com/traceloop/openllmetry-js)
- en: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
- en: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># traceloop/openllmetry-js
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># traceloop/openllmetry-js
- en: This commit does not belong to any branch on this repository, and may belong
    to a fork outside of the repository.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 本次提交不属于该代码库的任何分支，可能属于代码库之外的一个分支。
- en: <include-fragment src="/traceloop/openllmetry-js/spoofed_commit_check/f30c012bf1762d88d2637ab5e0379ab0b0df9a72"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: <include-fragment src="/traceloop/openllmetry-js/spoofed_commit_check/f30c012bf1762d88d2637ab5e0379ab0b0df9a72"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
- en: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
- en: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
