- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:44:43'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: 'GitHub - Textualize/toolong: A terminal application to view, tail, merge, and
    search log files (plus JSONL).'
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://github.com/Textualize/toolong](https://github.com/Textualize/toolong)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: <include-fragment class="js-notification-shelf-include-fragment" data-base-src="https://github.com/notifications/beta/shelf"></include-fragment>
  prefs: []
  type: TYPE_NORMAL
- en: <main id="js-repo-pjax-container"> <turbo-frame id="repo-content-turbo-frame"
    target="_top" data-turbo-action="advance" class=""># Textualize/toolong
  prefs: []
  type: TYPE_NORMAL
- en: This commit does not belong to any branch on this repository, and may belong
    to a fork outside of the repository.
  prefs: []
  type: TYPE_NORMAL
- en: <include-fragment src="/Textualize/toolong/spoofed_commit_check/5aa22ee878026f46d4d265905c4e1df4d37842ae"
    data-test-selector="spoofed-commit-check"></include-fragment></turbo-frame></main>
  prefs: []
  type: TYPE_NORMAL
- en: <ghcc-consent id="ghcc" class="position-fixed bottom-0 left-0" data-initial-cookie-consent-allowed=""
    data-cookie-consent-required="false">You can’t perform that action at this time.
  prefs: []
  type: TYPE_NORMAL
- en: <template id="site-details-dialog"></template><template id="snippet-clipboard-copy-button"></template><template
    id="snippet-clipboard-copy-button-unpositioned"></template></ghcc-consent>
  prefs: []
  type: TYPE_NORMAL
