- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:44:08'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: How QUIC Is Displacing TCP for Speed and Security
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://engineeringatscale.substack.com/p/how-quic-is-displacing-tcp-for-speed](https://engineeringatscale.substack.com/p/how-quic-is-displacing-tcp-for-speed)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Over the past three decades, **HTTP** (Hyper Text Transfer Protocol) has been
    the backbone of the internet. We are able to browse the web, download files, stream
    movies, etc due to HTTP. The protocol has evolved over the years and witnessed
    major enhancements.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: The HTTP protocol is an application protocol and works on top of **TCP (**Transmission
    Control Protocol**)**. The TCP protocol has several limitations and results in
    less responsive web applications.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: Google developed a game changing transport protocol called QUIC to overcome
    TCP’s downsides. **QUIC** was standardised and added to **IETF** (Internet Engineering
    Task Force) few years ago.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: The adoption of QUIC has grown exponentially in the last few years. Majority
    of the tech companies such as Google, Facebook, Pinterest, etc have started adopting
    HTTP/3.0 which uses QUIC at the transport level. These companies have seen significant
    improvements in the performance of their websites with HTTP/3.0 & QUIC.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: Let’s embark on our journey to understand how QUIC will displace TCP. We will
    first go through few fundamental networking concepts of TCP & UDP. Later, we will
    look at the evolution of HTTP and how each version overcame the limitations of
    the previous release. We will then see what QUIC is and how it works. We will
    explore why QUIC is highly performant as compared to TCP.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: TCP (**Transmission Control Protocol**) and UDP (**User Datagram Protocol**)
    are transport level protocols. These protocols manage the flow of internet packets
    to and from any electronic device. Let’s understand in detail how both the protocols
    work.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: '**TCP** is a connection based protocol. The client establishes a connection
    with the server and then sends the data. TCP connection is established through
    a mechanism known as Three-Way Handshake. The below diagram illustrates the Three-Way
    Handshake process :-'
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: '**TCP 3-Way Handshake Process**'
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: The process consists of three steps :-
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
- en: SYN - The client sends a **SYN** packet to the server.
  id: totrans-split-15
  prefs:
  - PREF_OL
  type: TYPE_NORMAL
- en: ACK - On receiving the **SYN**, the server sends an acknowledgement back to
    the client through the **ACK** packet.
  id: totrans-split-16
  prefs:
  - PREF_OL
  type: TYPE_NORMAL
- en: SYN-ACK - After receiving the **ACK** packet from the server, the client finally
    sends the acknowledgement via **SYN-ACK** to the server.
  id: totrans-split-17
  prefs:
  - PREF_OL
  type: TYPE_NORMAL
- en: TCP is a stateful and a reliable protocol. It guarantees delivery of all the
    packets from one device to another. Additionally, it allows both client and the
    server to use the same connection for communication.
  id: totrans-split-18
  prefs: []
  type: TYPE_NORMAL
- en: '**UDP** is a connectionless protocol. Unlike TCP, there is no Three-Way Handshake
    between the client and the server. The client sends the packets to the server
    and doesn’t wait for server’s acknowledgement.'
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
- en: UDP doesn’t guarantee 100% delivery of packets. Packets can get lost and may
    not reach the other device. UDP isn’t reliable like TCP.
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
- en: Since there is no initial handshake, UDP is much faster than TCP. For performance
    reasons, UDP is mostly used in streaming data applications such as music/video.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
- en: Here is a popular internet meme that takes a dig on TCP/UDP :-
  id: totrans-split-22
  prefs: []
  type: TYPE_NORMAL
- en: Till now, we have understood how TCP and UDP protocols work. Let’s now explore
    the HTTP protocol which is an application level protocol.
  id: totrans-split-23
  prefs: []
  type: TYPE_NORMAL
- en: The first version of HTTP was developed by [Tim Berners-Lee](https://en.wikipedia.org/wiki/Tim_Berners-Lee)
    at [CERN](https://en.wikipedia.org/wiki/CERN) in 1989\. There have been multiple
    optimisations and performance improvements in the protocol since then. Most of
    the modern devices use ***HTTP 1.1***/***HTTP 2.0*** and ***HTTP 3.0***. Let’s
    walkthrough the history of HTTP and understand major changes that the protocol
    underwent.
  id: totrans-split-24
  prefs: []
  type: TYPE_NORMAL
- en: After the initial HTTP/0.9 version, HTTP/1.0 started supporting headers, request
    body, txt files, etc. The clients had to create a TCP connection every time they
    fetched data from the server using HTTP. This resulted in significant wastage
    of resources for establishing the connection.
  id: totrans-split-25
  prefs: []
  type: TYPE_NORMAL
- en: This protocol added support for reusing the existing TCP connection between
    the client and the server for fetching new data. This was implemented with the
    help of the HTTP header `keep-alive`.
  id: totrans-split-26
  prefs: []
  type: TYPE_NORMAL
- en: If the client wanted to fetch 10 Javascript files, then it would establish one
    connection with the server. Then, it would reuse the same connection and fetch
    the 10 files instead of creating a new connection for each file.
  id: totrans-split-27
  prefs: []
  type: TYPE_NORMAL
- en: This results in reduced resource wastage and performance improvements, as it
    avoids creating redundant connections. However, a major downside was a problem
    known as *Head of the line blocking*.
  id: totrans-split-28
  prefs: []
  type: TYPE_NORMAL
- en: The following diagram illustrates the *Head of the line blocking* problem.
  id: totrans-split-29
  prefs: []
  type: TYPE_NORMAL
- en: '**Head of the Line Blocking**'
  id: totrans-split-30
  prefs: []
  type: TYPE_NORMAL
- en: Let’s understand this concept with an example. As shown in the above diagram,
    you have three files - image, text and video. The video file has a larger size
    and would take more time to transmit. Since the video file takes more time, it
    would block the image and text file from being sent.
  id: totrans-split-31
  prefs: []
  type: TYPE_NORMAL
- en: The **HTTP 2.0** solved the *Head of the line blocking* problem by multiplexing.
    With the help of multiplexing, multiple files could be sent over the same TCP
    connection.
  id: totrans-split-32
  prefs: []
  type: TYPE_NORMAL
- en: This resulted in performance gains and solved the Head of line blocking problem
    at the application level. However, at the TCP layer, in case there was a packet
    loss, it had to wait for packet retransmission.
  id: totrans-split-33
  prefs: []
  type: TYPE_NORMAL
- en: The multiplexing solution didn’t work as expected in case of packet losses.
    In fact, HTTP 1.1 performed better than HTTP 2.0 if the packet loss was more than
    5%. The *Head of the line blocking* problem transitioned from the application
    layer to the transport layer.
  id: totrans-split-34
  prefs: []
  type: TYPE_NORMAL
- en: The below diagram illustrates how a single packet loss resulted in multiple
    streams getting delayed :-
  id: totrans-split-35
  prefs: []
  type: TYPE_NORMAL
- en: '**Packet loss in HTTP/2.0 results in retransmission & stream delays**'
  id: totrans-split-36
  prefs: []
  type: TYPE_NORMAL
- en: When a single packet gets lost, TCP stores the subsequent packets in it’s buffer
    until it receives the lost packet. TCP then uses retransmission to get the lost
    packet. HTTP doesn’t have visibility into TCP retransmission. As a result, different
    streams see a delivery delay in such cases.
  id: totrans-split-37
  prefs: []
  type: TYPE_NORMAL
- en: In the past few sections, we saw that TCP has certain inherent limitations such
    as Three-way handshake & Head of the line blocking. These limitations can be solved
    by either enhancing TCP or replacing TCP with a new protocol.
  id: totrans-split-38
  prefs: []
  type: TYPE_NORMAL
- en: Although, it’s simple to enhance TCP but TCP is present in the lowest layer
    of tightly coupled with the Operating system. In simple words, the code for TCP
    exists in the kernel layer and not in the user space. Considering the vast number
    of devices, implementing changes in the kernel space would require a significant
    amount of time to reach all users.
  id: totrans-split-39
  prefs: []
  type: TYPE_NORMAL
- en: Hence, Google came up with a new protocol **QUIC**, which served as a replacement
    for TCP. Just like TCP, QUIC is also a transport level protocol. However, it resides
    in the user space instead of the kernel space. This makes it easy to change and
    enhance unlike TCP.
  id: totrans-split-40
  prefs: []
  type: TYPE_NORMAL
- en: QUIC works on top of UDP. It overcomes the limitations of TCP by using UDP.
    It’s just a layer or wrapper on top of UDP. The wrapper adds features of TCP such
    as congestion control, packet retransmission, multiplexing etc. It internally
    uses UDP and adds best features from TCP on top of it.
  id: totrans-split-41
  prefs: []
  type: TYPE_NORMAL
- en: The below image shows how QUIC fits in the networking stack :-
  id: totrans-split-42
  prefs: []
  type: TYPE_NORMAL
- en: '**Networking stack with QUIC**'
  id: totrans-split-43
  prefs: []
  type: TYPE_NORMAL
- en: Since we now understand the basics of QUIC, let’s dive into the working of this
    protocol.
  id: totrans-split-44
  prefs: []
  type: TYPE_NORMAL
- en: QUIC works on UDP & it doesn’t have to go through the Three-way handshake process.
    The Three-way handshake process adds an extra overhead and adds to the latency.
    As a result, QUIC improves the performance by reducing the connection latency.
  id: totrans-split-45
  prefs: []
  type: TYPE_NORMAL
- en: In case of TCP, there is an additional handshake used for TLS which adds to
    the latency. QUIC combines the TLS handshake and QUIC handshake in a single call.
    It thereby optimizes the handshake process and improves the performance.
  id: totrans-split-46
  prefs: []
  type: TYPE_NORMAL
- en: You might wonder “*Do packets get lost since QUIC works on UDP ?*”. The answer
    is No. QUIC adds reliability on top of the UDP stack. It implements packet retransmission
    in case it doesn’t receive the necessary packets. For eg:- If the server doesn’t
    receive packet no 5 from the client, the protocol will detect it and server will
    ask the client to resend the same packet.
  id: totrans-split-47
  prefs: []
  type: TYPE_NORMAL
- en: Similar to TCP, QUIC also implements multiplexing. Clients can transfer multiple
    files at the same time using a single channel. QUIC creates an UUID for each stream
    (file that gets transferred). It uses the UUID to identify the stream. Multiple
    streams are then sent over a single channel.
  id: totrans-split-48
  prefs: []
  type: TYPE_NORMAL
- en: The below diagram illustrates how multiplexing works in QUIC :-
  id: totrans-split-49
  prefs: []
  type: TYPE_NORMAL
- en: QUIC also solves the Head of Line blocking problem faced by TCP through it’s
    multiplexing. In case a stream suffers packet loss, only that stream would be
    impacted. The streams in QUIC are independent & don’t impact the working of each
    other.
  id: totrans-split-50
  prefs: []
  type: TYPE_NORMAL
- en: Moreover, QUIC also supports TLS 1.3 (Transport level security). This guarantees
    the security and confidentiality of the data. TLS encrypts large parts of the
    QUIC protocol such as packet numbers and connection close signals.
  id: totrans-split-51
  prefs: []
  type: TYPE_NORMAL
- en: '**Reduced latency** - QUIC minimizes the latency by combining the TLS handshake
    with the connection setup. This is also known as **0-RTT** (Zero Round Trip Time).
    It results in faster connection establishment and improves performance of web
    applications.'
  id: totrans-split-52
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Multiplexing** - With multiplexing, QUIC can send multiple streams of data
    over a single channel. It greatly helps client applications which download multiple
    files i.e images, Javascript, CSS, etc.'
  id: totrans-split-53
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Connection migration** - Using QUIC, you can switch from one network interface
    to another (wifi to mobile data) without any glitch. This is important for mobile
    devices and improves the user experience.'
  id: totrans-split-54
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Improved Security** - QUIC works on TLS 1.3, which offers better security.
    Additionally, it also encrypts large parts of the protocol unlike TCP with TLS,
    which encrypts only the HTTP payload. It is more resilient to security attacks
    as compared to TCP.'
  id: totrans-split-55
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Wide support** - It has seen a rise in adoption right since it’s inception.
    This has further strengthened it’s effectiveness.'
  id: totrans-split-56
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: HTTP/3 is the latest version of Hypertext Transfer Protocol (HTTP). It internally
    uses QUIC instead of TCP. It's designed to provide a more efficient and secure
    foundation for the modern web. It has all the benefits that QUIC provides.
  id: totrans-split-57
  prefs: []
  type: TYPE_NORMAL
- en: HTTP/3 is standardised by IETF. A large portion of the internet traffic relies
    on HTTP/3 today. Here is the graph that shows the adoption rate for HTTP/3 :-
  id: totrans-split-58
  prefs: []
  type: TYPE_NORMAL
- en: As seen from the above graph, the adoption has spiked to 30% and is gradually
    overtaking **HTTP/1.1**. With the given growth rate, **HTTP/3.0** will gradually
    overtake **HTTP/2.0** in the coming few years.
  id: totrans-split-59
  prefs: []
  type: TYPE_NORMAL
- en: The internet has come a long way since the inception of HTTP three decades ago.
    The evolution of HTTP has made the online experience more efficient and responsive.
    With the growing demands of modern applications, we realised inherent limitations
    of underlying protocols such as TCP.
  id: totrans-split-60
  prefs: []
  type: TYPE_NORMAL
- en: Google developed the game changing protocol, QUIC. It leveraged UDP and addressed
    all the shortcomings of TCP. Reduced latency, multiplexing, enhanced security,
    & connection migration are some of the striking features of QUIC. The innovations
    bought by QUIC have addressed problems like head of the line blocking.
  id: totrans-split-61
  prefs: []
  type: TYPE_NORMAL
- en: Big Tech companies like Google and Facebook have seen drastic improvements in
    performance by adopting QUIC in HTTP/3\. With the rising adoption and growing
    support, HTTP/3 will become a standard for internet communication. In the coming
    years, the internet will evolve and transition to HTTP/3 for efficiency, reliability
    and performance.
  id: totrans-split-62
  prefs: []
  type: TYPE_NORMAL
- en: 'Thanks for reading the article! Before you go:'
  id: totrans-split-63
  prefs: []
  type: TYPE_NORMAL
- en: Thank you for reading Engineering At Scale. This post is public so feel free
    to share it.
  id: totrans-split-64
  prefs: []
  type: TYPE_NORMAL
- en: '[Share](https://engineeringatscale.substack.com/p/how-quic-is-displacing-tcp-for-speed?utm_source=substack&utm_medium=email&utm_content=share&action=share)'
  id: totrans-split-65
  prefs: []
  type: TYPE_NORMAL
- en: '[TCP VS UDP meme](https://www.obiikriationz.com/tcp-vs-udp-meme-version.xhtml)'
  id: totrans-split-66
  prefs:
  - PREF_OL
  type: TYPE_NORMAL
- en: '[Why HTTP/3.0 is eating the world ?](https://blog.apnic.net/2023/09/25/why-http-3-is-eating-the-world/)'
  id: totrans-split-67
  prefs:
  - PREF_OL
  type: TYPE_NORMAL
- en: '[Pinterest is now on HTTP/3.0](https://medium.com/pinterest-engineering/pinterest-is-now-on-http-3-608fb5581094)'
  id: totrans-split-68
  prefs:
  - PREF_OL
  type: TYPE_NORMAL
- en: '[Peering with Google - QUIC](https://peering.google.com/#/learn-more/quic)'
  id: totrans-split-69
  prefs:
  - PREF_OL
  type: TYPE_NORMAL
