- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 15:01:44'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: Microsoft Is Spying on Users of Its AI Tools - Schneier on Security
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.schneier.com/blog/archives/2024/02/microsoft-is-spying-on-users-of-its-ai-tools.html](https://www.schneier.com/blog/archives/2024/02/microsoft-is-spying-on-users-of-its-ai-tools.html)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Microsoft Is Spying on Users of Its AI Tools
  id: totrans-split-6
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Microsoft announced that it [caught](https://www.washingtonpost.com/technology/2024/02/14/us-adversaries-using-artificial-intelligence-boost-hacking-efforts/)
    Chinese, Russian, and Iranian hackers using its AI tools—presumably coding tools—to
    improve their hacking abilities.
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: 'From their [report](https://www.microsoft.com/en-us/security/business/security-insider/reports/cyber-signals/cyber-signals-issue-6-navigating-cyberthreats-and-strengthening-defenses/):'
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: In collaboration with OpenAI, we are sharing threat intelligence showing detected
    state affiliated adversaries—tracked as Forest Blizzard, Emerald Sleet, Crimson
    Sandstorm, Charcoal Typhoon, and Salmon Typhoon—using LLMs to augment cyberoperations.
  id: totrans-split-9
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: The only way Microsoft or OpenAI would know this would be to spy on chatbot
    sessions. I’m sure the terms of service—if I bothered to read them—gives them
    that permission. And of course it’s no surprise that Microsoft and OpenAI (and,
    presumably, everyone else) are spying on our usage of AI, but this confirms it.
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: 'EDITED TO ADD (2/22): [Commentary](https://ioc.exchange/@invisv/111970414897990787)
    on my use of the word “spying.”'
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: 'Tags: [artificial intelligence](https://www.schneier.com/tag/artificial-intelligence/),
    [cyberespionage](https://www.schneier.com/tag/cyberespionage/), [espionage](https://www.schneier.com/tag/espionage/),
    [Microsoft](https://www.schneier.com/tag/microsoft/)'
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: '[Posted on February 20, 2024 at 7:02 AM](https://www.schneier.com/blog/archives/2024/02/microsoft-is-spying-on-users-of-its-ai-tools.html)
    • [26 Comments](https://www.schneier.com/blog/archives/2024/02/microsoft-is-spying-on-users-of-its-ai-tools.html#comments)'
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: Sidebar photo of Bruce Schneier by Joe MacInnis.
  id: totrans-split-14
  prefs: []
  type: TYPE_NORMAL
