- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
  zh: <!--yml
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
  zh: 'category: 未分类'
- en: 'date: 2024-05-27 14:52:57'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
  zh: 'date: 2024-05-27 14:52:57'
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
  zh: -->
- en: 'Online anonymity: study found ‘stable pseudonyms’ created a more civil environment
    than real user names'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
  zh: 在线匿名性：研究发现，“稳定的化名”比真实用户名创建了更文明的环境。
- en: 来源：[https://theconversation.com/online-anonymity-study-found-stable-pseudonyms-created-a-more-civil-environment-than-real-user-names-171374](https://theconversation.com/online-anonymity-study-found-stable-pseudonyms-created-a-more-civil-environment-than-real-user-names-171374)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
  zh: 来源：[https://theconversation.com/online-anonymity-study-found-stable-pseudonyms-created-a-more-civil-environment-than-real-user-names-171374](https://theconversation.com/online-anonymity-study-found-stable-pseudonyms-created-a-more-civil-environment-than-real-user-names-171374)
- en: The ability to remain anonymous when commenting online is a double-edged sword.
    It is valuable because it enables people to speak without fear of social and legal
    discrimination. But this is also what makes it dangerous. Someone from a repressive
    religious community can use anonymity to talk about their sexuality, for example.
    But someone else can use anonymity to hurl abuse at them with impunity.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
  zh: 在线评论的匿名能力是一把双刃剑。它有价值，因为它使人们能够在不担心社会和法律歧视的情况下发言。但这也是它危险的所在。比如，来自压抑宗教社区的人可以利用匿名性来谈论他们的性取向。但其他人也可以利用匿名性毫不顾忌地对他们进行谩骂。
- en: 'Many people focus on the dangers of online anonymity. Back in 2011, Randi Zuckerberg,
    sister of Mark and (then) marketing director of Facebook, said that for safety’s
    sake, [“anonymity on the internet has to go away”](https://www.huffingtonpost.co.uk/entry/randi-zuckerberg-anonymity-online_n_910892).
    Such calls appear [again](https://www.theguardian.com/society/2018/jun/11/labour-mp-jess-phillips-calls-for-end-to-online-anonymity-after-600-threats)
    and [again](https://www.politico.eu/article/ending-anonymity-is-not-easy-for-uk-ministers/).
    Behind them is a common intuition: that debate would be more civil and constructive
    if people used their real names.'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
  zh: 许多人关注在线匿名性的危险。2011年，马克·扎克伯格的姐姐兰迪·扎克伯格（当时是Facebook的市场总监）曾表示，出于安全考虑，[“互联网上的匿名必须消失”](https://www.huffingtonpost.co.uk/entry/randi-zuckerberg-anonymity-online_n_910892)。这类呼声一再出现，背后的共同直觉是：如果人们使用真实姓名，辩论将更加文明和建设性。
- en: But my research with colleagues suggests that anonymity – under certain conditions
    – can actually make for more civil and productive online discussion. This surprising
    result came out of a [study](https://onlinelibrary.wiley.com/doi/full/10.1111/jopp.12149)
    looking at the deliberative quality of comments on online news articles under
    a range of different identity rules.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
  zh: 但是我与同事进行的研究表明，特定条件下的匿名性实际上可以促进更文明和更有建设性的在线讨论。这一出人意料的结果来自一项研究，该研究观察了在不同身份规则下在线新闻评论的辩论质量。
- en: We built a data set of 45 million comments on news articles on the Huffington
    Post website between January 2013 and February 2015\. During this period, the
    site moved from a regime of easy anonymity to registered pseudonyms and finally
    to outsourcing their comments to Facebook. This created three distinct phases.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
  zh: 我们构建了一个数据集，涵盖了2013年1月至2015年2月期间在赫芬顿邮报网站上的新闻文章评论，总计4500万条评论。在此期间，该网站从轻松匿名的制度过渡到注册化的化名，最终将评论外包给Facebook。这形成了三个明显的阶段。
- en: In the initial phase users could easily set up multiple accounts. The comment
    space was, at that time, a troll’s paradise. People could read an article, quickly
    create a username, and post whatever they wanted. If moderators blocked that username
    for abusive behaviour, the person (or even bot) behind it could just make another,
    and then another, and so on. This led to a space that was unpleasant for users.
    So the website [began to make changes](https://www.huffpost.com/entry/why-is-huffpost-ending-an_b_3817979?guccounter=1).
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
  zh: 在最初阶段，用户可以轻松创建多个账户。评论空间当时是恶搞者的天堂。人们可以阅读一篇文章，快速创建一个用户名，并发布任何他们想说的话。如果管理员因滥用行为封锁了该用户名，背后的人（甚至是机器人）可以简单地再创建一个，再创建一个，依此类推。这导致用户感到不愉快的空间。因此，该网站开始进行了一些变革。
- en: In the second phase, users had to authenticate their accounts, but did not have
    to use their real name with their comments. That meant they could be anonymous
    to other users but could be identified by the platform. If they behaved badly
    and were blocked, they couldn’t just make a new account and carry on – at least,
    not without creating a new authenticating account on Facebook. This made personas
    on this commenting space less disposable. They became “stable pseudonyms”.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
  zh: 在第二阶段，用户必须验证他们的帐户，但在评论中不必使用他们的真实姓名。这意味着他们对其他用户可以匿名，但可以被平台识别。如果他们表现不佳被屏蔽，他们不能简单地创建新帐户继续
    —— 至少不会在Facebook上创建新的验证帐户。这使得在这个评论空间中的角色不那么一次性。它们变成了“稳定的假名”。
- en: Some have called for online anonymity to be banned in the UK after the murder
    of MP David Amess. Alamy
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
  zh: 在英国议员大卫·艾米斯遇害后，一些人呼吁禁止网络匿名性。Alamy
- en: In the third phase, the commenting system was outsourced to Facebook. Huffington
    Post usernames were replaced with user’s Facebook names and avatars. Depending
    on settings, comments might appear on users’ Facebook feeds. While not everyone
    has their own face on their profile picture, and not everyone even uses their
    real name on their account, many users do. This third phase therefore roughly
    approximates a real-name environment.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
  zh: 在第三阶段，评论系统被外包给了Facebook。赫芬顿邮报的用户名被用户的Facebook姓名和头像取代。根据设置，评论可能会出现在用户的Facebook动态中。虽然不是每个人的个人资料图片都有自己的脸，也不是每个人在其帐户上都使用真实姓名，但许多用户确实这样做。因此，这第三阶段大致等同于真实姓名环境。
- en: Keeping it friendly
  id: totrans-split-14
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 保持友好
- en: We looked initially at the use of swear words and offensive terms – a crude
    measure of civility. We found that after the first change the use of these words
    dropped significantly. This was not just because some of the worst offenders left
    the site. Among those who stayed, language was cleaner after the change than before.
    We describe this as a sort of “broken-windows” effect, after the famous theory
    that cleaning up a neighbourhood can help reduce crime. Here, a cleaner environment
    [improves everyone’s behaviour](https://dl.acm.org/doi/pdf/10.1145/2786451.2786459).
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
  zh: 我们最初关注的是脏话和冒犯性词语的使用 —— 这是文明程度的粗略衡量标准。我们发现，在第一次变更后，这些词语的使用显著减少了。这不仅仅是因为一些最坏的行为者离开了该网站。在留下的人中，语言在变更后比之前更加清洁。我们描述这种现象类似于“破窗效应”，源自于一个著名理论，即清理社区可以帮助减少犯罪。在这里，一个更干净的环境
    [改善了每个人的行为](https://dl.acm.org/doi/pdf/10.1145/2786451.2786459)。
- en: We then looked across all three phases at other features of individual comments,
    including the length of words, causation words (for example, “because”), words
    indicating tentative conclusions (for example, “perhaps”), and more. We were able
    to automate this analysis and use it to construct a measure of the “cognitive
    complexity” of comments. This method has been tested on the [deliberations of
    the Swiss parliament](https://onlinelibrary.wiley.com/doi/full/10.1111/spsr.12179)
    and shown to be a good proxy for deliberative quality. We could not, of course,
    see the context and meaning of each individual comment, but using this method
    at least allowed us to do the analysis at a very large scale.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
  zh: 然后，我们跨越了这三个阶段，研究了个别评论的其他特征，包括单词的长度、因果性词（例如“因为”）、表达不确定结论的词（例如“也许”）等等。我们能够自动化这种分析，并用它来构建评论“认知复杂性”的度量标准。这种方法已在[瑞士议会的讨论中进行了测试](https://onlinelibrary.wiley.com/doi/full/10.1111/spsr.12179)，并显示出是辩论质量的良好代理。当然，我们无法看到每个个体评论的上下文和意义，但至少使用这种方法可以在非常大的规模上进行分析。
- en: Our results suggest that the quality of comments was highest in the middle phase.
    There was a great improvement after the shift from easy or disposable anonymity
    to what we call “durable pseudonyms”. But instead of improving further after the
    shift to the real-name phase, the quality of comments actually got worse – not
    as bad as in the first phase, but still worse [by our measure](https://journals.sagepub.com/doi/full/10.1177/0032321719891385).
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
  zh: 我们的研究结果表明，在中期阶段，评论的质量最高。从简单或一次性匿名到我们所谓的“持久化假名”后，评论质量有了很大的改善。但在转向真实姓名阶段后，评论的质量实际上变得更糟了
    —— 尽管没有像第一阶段那样糟糕，但仍然变差了 [根据我们的测量](https://journals.sagepub.com/doi/full/10.1177/0032321719891385)。
- en: A surprise finding
  id: totrans-split-18
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
  zh: 一个意外发现
- en: This complicates the common assumption that people behave better with their
    real names on display. We don’t know exactly what explains our results, but one
    possibility is that under durable pseudonyms the users orient their comments primarily
    at their fellow commentators as an audience. They then perhaps develop a concern
    for their own reputation within that forum, as has been [suggested elsewhere](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1430-9134.2001.00173.x).
    It’s possible that a real-name environment shifts the dynamic. When you make comments
    that can be seen not only by other Huffington Post readers but also by your Facebook
    friends, it seems plausible that you might speak differently.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
  zh: 这使得人们普遍认为使用真实姓名会使人们表现更好的观点变得复杂起来。我们并不确切地知道是什么解释了我们的结果，但有一个可能性是，在持久化的化名下，用户主要将他们的评论定位于他们的同行评论者作为观众。然后，他们可能会对自己在该论坛中的声誉产生关注，正如[其他地方建议的](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1430-9134.2001.00173.x)那样。真实姓名的环境可能会改变动态。当你发表的评论不仅被其他《赫芬顿邮报》读者看到，还可能被你的Facebook朋友看到时，你可能会表达不同的观点。
- en: What matters, it seems, is not so much whether you are commenting anonymously,
    but whether you are invested in your persona and accountable for its behaviour
    in that particular forum. There seems to be [value](https://demos.co.uk/project/whats-in-a-name/)
    in enabling people to speak on forums without their comments being connected,
    via their real names, to other contexts. The online comment management company
    Disqus, in a similar vein, found that comments made under conditions of durable
    pseudonymity were rated by other users as having the [highest quality](https://disqus.com/research/pseudonyms/).
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
  zh: 看起来，重要的不是你是否匿名评论，而是你是否对你的角色投入并对其在特定论坛中的行为负责。在[这里](https://demos.co.uk/project/whats-in-a-name/)，似乎有一定的价值，让人们在论坛上发言时不会通过他们的真实姓名连接到其他背景。在线评论管理公司Disqus也发现，以持久化的化名发表的评论被其他用户评为[质量最高](https://disqus.com/research/pseudonyms/)。
- en: There is obviously more to online discussion spaces than just their identity
    rules. But we can at least say that calls to end anonymity online by forcing people
    to reveal their real identities might not have the effects people expect – even
    if it appears to be the most obvious answer.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
  zh: 显然，在线讨论空间还有比身份规则更多的内容。但我们至少可以说，要求在线结束匿名性，通过强制人们揭示他们的真实身份，可能不会产生人们预期的效果——即使它看起来是最明显的答案。
