- en: <!--yml
  id: totrans-split-0
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  id: totrans-split-1
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 14:52:57'
  id: totrans-split-2
  prefs: []
  type: TYPE_NORMAL
- en: -->
  id: totrans-split-3
  prefs: []
  type: TYPE_NORMAL
- en: 'Online anonymity: study found ‘stable pseudonyms’ created a more civil environment
    than real user names'
  id: totrans-split-4
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://theconversation.com/online-anonymity-study-found-stable-pseudonyms-created-a-more-civil-environment-than-real-user-names-171374](https://theconversation.com/online-anonymity-study-found-stable-pseudonyms-created-a-more-civil-environment-than-real-user-names-171374)
  id: totrans-split-5
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: The ability to remain anonymous when commenting online is a double-edged sword.
    It is valuable because it enables people to speak without fear of social and legal
    discrimination. But this is also what makes it dangerous. Someone from a repressive
    religious community can use anonymity to talk about their sexuality, for example.
    But someone else can use anonymity to hurl abuse at them with impunity.
  id: totrans-split-6
  prefs: []
  type: TYPE_NORMAL
- en: 'Many people focus on the dangers of online anonymity. Back in 2011, Randi Zuckerberg,
    sister of Mark and (then) marketing director of Facebook, said that for safety’s
    sake, [“anonymity on the internet has to go away”](https://www.huffingtonpost.co.uk/entry/randi-zuckerberg-anonymity-online_n_910892).
    Such calls appear [again](https://www.theguardian.com/society/2018/jun/11/labour-mp-jess-phillips-calls-for-end-to-online-anonymity-after-600-threats)
    and [again](https://www.politico.eu/article/ending-anonymity-is-not-easy-for-uk-ministers/).
    Behind them is a common intuition: that debate would be more civil and constructive
    if people used their real names.'
  id: totrans-split-7
  prefs: []
  type: TYPE_NORMAL
- en: But my research with colleagues suggests that anonymity – under certain conditions
    – can actually make for more civil and productive online discussion. This surprising
    result came out of a [study](https://onlinelibrary.wiley.com/doi/full/10.1111/jopp.12149)
    looking at the deliberative quality of comments on online news articles under
    a range of different identity rules.
  id: totrans-split-8
  prefs: []
  type: TYPE_NORMAL
- en: We built a data set of 45 million comments on news articles on the Huffington
    Post website between January 2013 and February 2015\. During this period, the
    site moved from a regime of easy anonymity to registered pseudonyms and finally
    to outsourcing their comments to Facebook. This created three distinct phases.
  id: totrans-split-9
  prefs: []
  type: TYPE_NORMAL
- en: In the initial phase users could easily set up multiple accounts. The comment
    space was, at that time, a troll’s paradise. People could read an article, quickly
    create a username, and post whatever they wanted. If moderators blocked that username
    for abusive behaviour, the person (or even bot) behind it could just make another,
    and then another, and so on. This led to a space that was unpleasant for users.
    So the website [began to make changes](https://www.huffpost.com/entry/why-is-huffpost-ending-an_b_3817979?guccounter=1).
  id: totrans-split-10
  prefs: []
  type: TYPE_NORMAL
- en: In the second phase, users had to authenticate their accounts, but did not have
    to use their real name with their comments. That meant they could be anonymous
    to other users but could be identified by the platform. If they behaved badly
    and were blocked, they couldn’t just make a new account and carry on – at least,
    not without creating a new authenticating account on Facebook. This made personas
    on this commenting space less disposable. They became “stable pseudonyms”.
  id: totrans-split-11
  prefs: []
  type: TYPE_NORMAL
- en: Some have called for online anonymity to be banned in the UK after the murder
    of MP David Amess. Alamy
  id: totrans-split-12
  prefs: []
  type: TYPE_NORMAL
- en: In the third phase, the commenting system was outsourced to Facebook. Huffington
    Post usernames were replaced with user’s Facebook names and avatars. Depending
    on settings, comments might appear on users’ Facebook feeds. While not everyone
    has their own face on their profile picture, and not everyone even uses their
    real name on their account, many users do. This third phase therefore roughly
    approximates a real-name environment.
  id: totrans-split-13
  prefs: []
  type: TYPE_NORMAL
- en: Keeping it friendly
  id: totrans-split-14
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: We looked initially at the use of swear words and offensive terms – a crude
    measure of civility. We found that after the first change the use of these words
    dropped significantly. This was not just because some of the worst offenders left
    the site. Among those who stayed, language was cleaner after the change than before.
    We describe this as a sort of “broken-windows” effect, after the famous theory
    that cleaning up a neighbourhood can help reduce crime. Here, a cleaner environment
    [improves everyone’s behaviour](https://dl.acm.org/doi/pdf/10.1145/2786451.2786459).
  id: totrans-split-15
  prefs: []
  type: TYPE_NORMAL
- en: We then looked across all three phases at other features of individual comments,
    including the length of words, causation words (for example, “because”), words
    indicating tentative conclusions (for example, “perhaps”), and more. We were able
    to automate this analysis and use it to construct a measure of the “cognitive
    complexity” of comments. This method has been tested on the [deliberations of
    the Swiss parliament](https://onlinelibrary.wiley.com/doi/full/10.1111/spsr.12179)
    and shown to be a good proxy for deliberative quality. We could not, of course,
    see the context and meaning of each individual comment, but using this method
    at least allowed us to do the analysis at a very large scale.
  id: totrans-split-16
  prefs: []
  type: TYPE_NORMAL
- en: Our results suggest that the quality of comments was highest in the middle phase.
    There was a great improvement after the shift from easy or disposable anonymity
    to what we call “durable pseudonyms”. But instead of improving further after the
    shift to the real-name phase, the quality of comments actually got worse – not
    as bad as in the first phase, but still worse [by our measure](https://journals.sagepub.com/doi/full/10.1177/0032321719891385).
  id: totrans-split-17
  prefs: []
  type: TYPE_NORMAL
- en: A surprise finding
  id: totrans-split-18
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: This complicates the common assumption that people behave better with their
    real names on display. We don’t know exactly what explains our results, but one
    possibility is that under durable pseudonyms the users orient their comments primarily
    at their fellow commentators as an audience. They then perhaps develop a concern
    for their own reputation within that forum, as has been [suggested elsewhere](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1430-9134.2001.00173.x).
    It’s possible that a real-name environment shifts the dynamic. When you make comments
    that can be seen not only by other Huffington Post readers but also by your Facebook
    friends, it seems plausible that you might speak differently.
  id: totrans-split-19
  prefs: []
  type: TYPE_NORMAL
  zh: 这使得人们普遍认为使用真实姓名会使人们表现更好的观点变得复杂起来。我们并不确切地知道是什么解释了我们的结果，但有一个可能性是，在持久化的化名下，用户主要将他们的评论定位于他们的同行评论者作为观众。然后，他们可能会对自己在该论坛中的声誉产生关注，正如[其他地方建议的](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1430-9134.2001.00173.x)那样。真实姓名的环境可能会改变动态。当你发表的评论不仅被其他《赫芬顿邮报》读者看到，还可能被你的Facebook朋友看到时，你可能会表达不同的观点。
- en: What matters, it seems, is not so much whether you are commenting anonymously,
    but whether you are invested in your persona and accountable for its behaviour
    in that particular forum. There seems to be [value](https://demos.co.uk/project/whats-in-a-name/)
    in enabling people to speak on forums without their comments being connected,
    via their real names, to other contexts. The online comment management company
    Disqus, in a similar vein, found that comments made under conditions of durable
    pseudonymity were rated by other users as having the [highest quality](https://disqus.com/research/pseudonyms/).
  id: totrans-split-20
  prefs: []
  type: TYPE_NORMAL
  zh: 看起来，重要的不是你是否匿名评论，而是你是否对你的角色投入并对其在特定论坛中的行为负责。在[这里](https://demos.co.uk/project/whats-in-a-name/)，似乎有一定的价值，让人们在论坛上发言时不会通过他们的真实姓名连接到其他背景。在线评论管理公司Disqus也发现，以持久化的化名发表的评论被其他用户评为[质量最高](https://disqus.com/research/pseudonyms/)。
- en: There is obviously more to online discussion spaces than just their identity
    rules. But we can at least say that calls to end anonymity online by forcing people
    to reveal their real identities might not have the effects people expect – even
    if it appears to be the most obvious answer.
  id: totrans-split-21
  prefs: []
  type: TYPE_NORMAL
  zh: 显然，在线讨论空间还有比身份规则更多的内容。但我们至少可以说，要求在线结束匿名性，通过强制人们揭示他们的真实身份，可能不会产生人们预期的效果——即使它看起来是最明显的答案。
