- en: <!--yml
  prefs: []
  type: TYPE_NORMAL
- en: 'category: 未分类'
  prefs: []
  type: TYPE_NORMAL
- en: 'date: 2024-05-27 15:05:46'
  prefs: []
  type: TYPE_NORMAL
- en: -->
  prefs: []
  type: TYPE_NORMAL
- en: Product Engineer at Stepful | Y Combinator
  prefs:
  - PREF_H1
  type: TYPE_NORMAL
- en: 来源：[https://www.ycombinator.com/companies/stepful/jobs/iLjGDJ0-product-engineer](https://www.ycombinator.com/companies/stepful/jobs/iLjGDJ0-product-engineer)
  prefs:
  - PREF_BQ
  type: TYPE_NORMAL
- en: Stepful partners with healthcare institutions to build talent pipelines and
    career pathways. We are reimagining allied healthcare training with a digital-first
    environment for student cohorts that prepare job-ready graduates five times faster
    at a fraction of the cost. Stepful graduates, primarily from underrepresented
    communities, go on to work at leading healthcare institutions and report an average
    25% income increase after just four months of training.
  prefs: []
  type: TYPE_NORMAL
- en: Stepful is backed by Y Combinator and recently closed a round led by AlleyCorp,
    Reach Capital, and Sempervirens.
  prefs: []
  type: TYPE_NORMAL
- en: Us
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: We are successful only if our students are successful, we are successful if
    they keep studying, graduate, and ultimately if they find a job. Everything you
    will be building at Stepful will directly influence our outcomes and impact the
    lives of thousands of students.
  prefs: []
  type: TYPE_NORMAL
- en: 'Here is what you can expect to be working on:'
  prefs: []
  type: TYPE_NORMAL
- en: '**World Class Learning Experience**: Develop and iterate on an advanced Learning
    Management System that generates outcomes! Focus on seamless UX, adaptive learning,
    peer-to-peer engagement, gamification and motivational mechanisms..'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Innovative Career Services**: Empower graduates to find jobs and match our
    growing network of clinical partners. Apply generative AI to the job-seeking process,
    from resume generation to interview training.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Empower the Internal Workforce**: Design and maintain platforms for instructors,
    TAs, coaches, and operators to optimize student success. Leverage generative AI
    to maximize its impact on students'' lives.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Cutting Edge Content Management**: Generate and maintain content at scale
    that adapts to evolving educational needs. Build the technology to create new
    curricula in a fraction of the time and iterate to maximize students'' learning.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Data Pipelines**: Make data reliable and accessible to everyone at Stepful,
    and empower the business, learning, and operation teams at Stepful to make data-driven
    decisions.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: You
  prefs:
  - PREF_H2
  type: TYPE_NORMAL
- en: Are strongly driven to make an impact in people's lives
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Relentlessly obsess over solving complex problems with cutting-edge technology
    and willing to learn something new every day
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Find excitement in joining an early-stage company and are not afraid of building
    something new
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Have built something meaningful to you, before
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Eat, sleep and breathe at least one of part of our stack (React, Typescript,
    Ruby on Rails, PostgreSQL), you will learn the rest
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Can take ownership of the whole development lifecycle (this means you are comfortable
    operating full-stack)
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: You will be successful if
  prefs:
  - PREF_H3
  type: TYPE_NORMAL
- en: '**Care first**: We do everything it takes for our students to succeed.'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Learn quickly**: We test, learn with data, and iterate'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Build together**: We win when we rely on each other'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: '**Own it**: We show up, we take initiative, and pride'
  prefs:
  - PREF_UL
  type: TYPE_NORMAL
- en: Join our team for a unique opportunity to make an impact
  prefs: []
  type: TYPE_NORMAL
- en: We offer competitive salaries, equity packages, 401k, health insurance
  prefs: []
  type: TYPE_NORMAL
- en: Stepful is an equal opportunity employer, welcoming applicants from all backgrounds.
    We value diversity and inclusion and are committed to creating a supportive and
    inclusive workplace for all.
  prefs: []
  type: TYPE_NORMAL
- en: '*Note: Salary ranges are indicative and applicable to US-based employment.*'
  prefs: []
  type: TYPE_NORMAL
